### ISSUE TITLE
[BUG] Docker Compose embeds the quotes in th bash variables when passing .env file to Dockerfile yaml.

### ISSUE THREAD

**Issue by wyattbiker** [docker/compose#10040]
### Description

Docker Compose does not consider quotes as a quotes in bash variables when passing env file to container in yaml file #8479      Still a bug but was closed by Stale.

Additional Info:
It is not a bug on Mac OS X,  Only on Linux.

**Comment by ndeloof** [comment]
While `docker run` parse env-file are a raw KEY=VALUE text file, and doing so don't skip quotes, compose has way more advanced support for env file syntax, including nested variable interpolation, multi-line values, etc. For this purpose, quotes are used to escape some content that would otherwise be parsed.

please note if you set an env file as
```
BASH_VARIABLE="This is a variable with quotes"
```
and use it from a shell you'll get the same:
```
$ source .env
$ env | grep BASH_VARIABLE
BASH_VARIABLE=This is a variable with quotes
```

If you **need** quotes to be preserved, you have to escape them in your dot env file with ... quotes:
```
BASH_VARIABLE='"This is a variable with quotes"'
```

I'm closing this issue as "works as designed, won't fix"

**Comment by ernstki** [comment]
@ndeloof You're accurately describing the _expected_ behavior, but that's not the issue in #8479. I'm seeing the same thing #8479 describes with `docker-compose` 1.25.x from the Ubuntu 20.04 repositories.

I get that this was probably fixed in a later version of Docker Compose, or a newer version of the underlying library ([godotenv](https://github.com/joho/godotenv), I think), so from a maintainer point of view this issue is probably moot. It's not _Docker's_ fault that Debian hasn't backported a fix, and so on down the line. I get that.

For people stuck with `docker-compose` of this older vintage, though, if you run into this problem:

* Assume everything after the `=` in your `.env` file will be treated literally, with no special interpolation.
* If you're seeing extraneous literal quotes in environment variables defined in the container, remove those quotes from the `.env`.
* The behavior currently (early 2024) described [in the docs](https://docs.docker.com/compose/environment-variables/env-file/) doesn't pertain to the older version you have.

**Comment by ndeloof** [comment]
@ernstki don't rely on debian's `docker-compose` package installing End-of-life Docker Compose v1, we have debian packages for docker products as decribed on https://docs.docker.com/engine/install/

**Comment by ernstki** [comment]
@ndeloof Yes, I fully understand, and that's good advice from Docker, Inc.'s and the developer community's point of view.

If someone else has a legitimate need or desire to stick with the repository packages in a long-term support release of their preferred Linux distribution, I hope the above context helps.

Those LTS packages are still technically, if tenuously, supported by the distro/vendor, and are a sane choice if you want to build something upon a stable foundation, where backward-incompatible changes occur on a predictable schedule.
