### ISSUE TITLE
build with pull does not tag base images in Docker Engine

### ISSUE THREAD

**Issue by danielpanteleit** [docker/compose#10206]
### Description

When running `docker compose build --pull` the base images are not tagged (images will not be updated/added in `docker images`). This can lead to inconsistent builds when a build is later started without `--pull`. It could reload a newer version or use an older version of the base image if it was already available.

Notes:
- This also applies to `docker compose build` (without pull) when the base image was not previously fetched
- In Compose v1 this did work for both `build` and `build --pull`

### Steps To Reproduce

docker-compose.yml:
```
services:
  app:
    build: .
```

Dockerfile:
```
FROM ubuntu:22.04
```

1. Run `docker compose build --pull`
2. Run `docker images`
3. Only the image for the build will appear, ubuntu:22.04 won't.

### Compose Version

```Text
Docker Compose version v2.15.1
```

**Comment by kramerrs** [comment]
Yes, I have been struggling with something like this.  We recently just upgraded portainer to 2.16.2 which I believe also upgrades docker compose under the hood.  I am unable to launch the images.  It pulls down the images but does not tag them.  Somehow portainer can launch them, but other processes such as ShinyProxy cannot find them.  I am not sure where the ball is being dropped.

**Comment by milas** [comment]
Compose uses BuildKit for image builds, which maintains its own builder cache independent from the Docker Engine image store. When you build an image with Compose & BuildKit, only the final image will be "exported" back to the Docker Engine so that it's available for `docker run...` etc. This is different than the classic Docker builder, where everything from base images to intermediary build artifacts was directly visible.

This behavior is working as designed. If you want to guarantee a consistent base image, consider pinning to a particular digest, for example.
