### ISSUE TITLE
Docker-compose with dockerfile / watchtower

### ISSUE THREAD

**Issue by kekec777** [docker/compose#10333]
### Description

So i'm hoping you guys can figure this one out..

I have 4 images , where i use dockerfile and one of them is wordpress , just to give an example..
Dockerfile:
FROM wordpress:latest RUN chmod o+r /etc/resolv.conf && apt-get update

Here i use "docker-compose up -d wordpress" to pull & build and start the images , this goes fine..

So here's the issue..

When watchtower checks for newer images for wordpress , it fails:
Could not do a head request for "dockercompose-wordpress:latest", falling back to regular pull. Reason: registry responded to head request with "401 Unauthorized", auth: "Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\",scope=\"repository:library/dockercompose-wordpress:pull\",error=\"insufficient_scope\"" Unable to update container "/wordpress": Error response from daemon: pull access denied for dockercompose-wordpress, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

and for me it seems the name is wrong = dockercompose-wordpress.:latest
And thats a name my docker-compose is setting and i dont know how to change it or if i could would it solve the problem..

Any input is appreciated and thanks in advice :)

### Steps To Reproduce

Build with docker-compose:
docker-compose up -d wordpress
`  wordpress:
    build: 
      context: ./dockerfiles/wordpress
      dockerfile: Dockerfile`

Dockerfile:
`FROM wordpress:latest 
RUN chmod o+r /etc/resolv.conf && apt-get update`

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 29
  Running: 29
  Paused: 0
  Stopped: 0
 Images: 75
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.0.0-0.deb11.6-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 94.13GiB
 Name: kekecserver
 ID: 5CKV:ZMIX:LO4J:XCB7:HR7F:56S3:AFFE:JCR3:2JRL:N7TK:3MIS:FPJW
 Docker Root Dir: /srv/dev-disk-by-uuid-2d63569d-15a7-41a3-8009-e9b487095e11/docker
 Debug Mode: false
 Username: kekec777
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment]
Hello @kekec777 
Can you share your compose file, especially the `wordpress` service declaration? Regarding the error you either don't defined an `image` attribute or used name without the repository where our image is pushed (ie: `myaccount/dockercompose-wordpress`)

**Comment by thaJeztah** [comment]
I think the issue here is that your compose file does not "use" the `wordpress` image, but it uses an image that's built (as part of the compose file + Dockerfile); that image gets its own name, and usually that image would be pushed to a registry (e.g. as `myname/mywordpressite`). If no explicit name is set for the image, compose defaults to using  `<projectname>-<service name>` (`dockercompose-wordpress` in the example you gave).

So watchtower "correctly" checks Docker Hub if there's a new version of "your image" available on Docker Hub, and that image doesn't exist, which causes the error.

Instead of using watchtower for this, you could consider setting the `pull` option in your compose file, which forces docker to pull the image before building (making sure that the local image is up-to-date before building your image); https://docs.docker.com/compose/compose-file/build/#pull

Alternatively, you could configure watchtower to not check for updates of the image you built, but setting a label to exclude it (which can be set in your compose-file or in the Dockerfile);
https://containrrr.dev/watchtower/container-selection/

**Comment by kekec777** [comment]
> Hello @kekec777 Can you share your compose file, especially the `wordpress` service declaration? Regarding the error you either don't defined an `image` attribute or used name without the repository where our image is pushed (ie: `myaccount/dockercompose-wordpress`)

Here is my docker-compose.yml file
[wordpress.docker-compose.txt](https://github.com/docker/compose/files/10859565/wordpress.docker-compose.txt)

**Comment by kekec777** [comment]
> I think the issue here is that your compose file does not "use" the `wordpress` image, but it uses an image that's built (as part of the compose file + Dockerfile); that image gets its own name, and usually that image would be pushed to a registry (e.g. as `myname/mywordpressite`). If no explicit name is set for the image, compose defaults to using `<projectname>-<service name>` (`dockercompose-wordpress` in the example you gave).
> 
> So watchtower "correctly" checks Docker Hub if there's a new version of "your image" available on Docker Hub, and that image doesn't exist, which causes the error.
> 
> Instead of using watchtower for this, you could consider setting the `pull` option in your compose file, which forces docker to pull the image before building (making sure that the local image is up-to-date before building your image); https://docs.docker.com/compose/compose-file/build/#pull
> 
> Alternatively, you could configure watchtower to not check for updates of the image you built, but setting a label to exclude it (which can be set in your compose-file or in the Dockerfile); https://containrrr.dev/watchtower/container-selection/

Hmm that has crossed my mind. 
I really want to use watchtower to update my images automatically .. So watchtower is a must..
And i know about the label you can set so watchtower doesnt update it.. But i really want to update the images , both security reason and be able to get new features ... 

> I think the issue here is that your compose file does not "use" the wordpress image, but it uses an image that's built (as part of the compose file + Dockerfile); that image gets its own name, and usually that image would be pushed to a registry (e.g. as myname/mywordpressite). If no explicit name is set for the image, compose defaults to using <projectname>-<service name> (dockercompose-wordpress in the example you gave).
>

any way to resolve this?

**Comment by thaJeztah** [comment]
> I really want to use watchtower to update my images automatically .. So watchtower is a must..

So, that's what it does; your compose file uses an image named `dockercompose-wordpress`, and it checks if a newer image of `dockercompose-wordpress` is available on Docker Hub. watchtower wouldn't be able to update your image, unless it also automatically re-builds your image.

So in this case you _don't_ want it to check for the image itself (so probably you want that image to be excluded from watchtower) because for this scenario the "locally built image" would always be the "latest" build of that image.

But when _building_ that image, it should check if the image it's based on (`wordpress` in this example) is up-to date. The `pull` option allows you to make sure that the image is up-to-date, so every time you build the image, it would be with the latest wordpress image.

But yes, if you're not building that image frequently, then the base-image may be outdated. So the tricky bit here would be to know when a newer version of the wordpress image is available, so when it's time for you to rebuild your image.

It's been a while since I looked at watchtower; I know it supports notifications (https://containrrr.dev/watchtower/notifications/), but I'm not sure if it supports a "list of images to check" instead of "checking image that you have for updates").

I _think_ Diun has that option though; https://crazymax.dev/diun/, but @crazy-max can probably tell more.

**Comment by kekec777** [comment]
> list of images to check

I have looked at  https://crazymax.dev/diun/ but this is not resolving my issue here..
It helps , but not resolving.. 
i have found scripts that can do this for me aswell - a scrip that take the local digits and compare it to docker.hub image digits.

But what i want is more like, let watchtower check my custom wordpress and update it if there's a new wordpress image from what i used to build with..

OR maybe change or set digits on my own build? so it matches wordpress image from docker.hub?

**Comment by kekec777** [comment]
> > I really want to use watchtower to update my images automatically .. So watchtower is a must..
> 
> So, that's what it does; your compose file uses an image named `dockercompose-wordpress`, and it checks if a newer image of `dockercompose-wordpress` is available on Docker Hub. watchtower wouldn't be able to update your image, unless it also automatically re-builds your image.
> 
> So in this case you _don't_ want it to check for the image itself (so probably you want that image to be excluded from watchtower) because for this scenario the "locally built image" would always be the "latest" build of that image.
> 
> But when _building_ that image, it should check if the image it's based on (`wordpress` in this example) is up-to date. The `pull` option allows you to make sure that the image is up-to-date, so every time you build the image, it would be with the latest wordpress image.
> 
> But yes, if you're not building that image frequently, then the base-image may be outdated. So the tricky bit here would be to know when a newer version of the wordpress image is available, so when it's time for you to rebuild your image.
> 
> It's been a while since I looked at watchtower; I know it supports notifications (https://containrrr.dev/watchtower/notifications/), but I'm not sure if it supports a "list of images to check" instead of "checking image that you have for updates").
> 
> I _think_ Diun has that option though; https://crazymax.dev/diun/, but @crazy-max can probably tell more.

I have looked at https://crazymax.dev/diun/ but this is not resolving my issue here..
It helps , but not resolving..
i have found scripts that can do this for me aswell - a scrip that take the local digits and compare it to docker.hub image digits.

But what i want is more like, let watchtower check my custom wordpress and update it if there's a new wordpress image from what i used to build with..

OR maybe change or set digits on my own build? so it matches wordpress image from docker.hub?

**Comment by ndeloof** [comment]
Docker compose builds a local image based on your Dockerfile. But this image is not updated, nor is it published on a registry, so don't expect watchtower to help you here.
To support what you expect, you'll need to configure adequate tool to watch registry for your base image to be updated, then `docker compose up --build` to force rebuild image and refresh service. https://crazymax.dev/diun/notif/script/ might be a solution here, as you can run a script after update has been detected.

Anyway, this is out of the scope of docker compose, so I'm closing this issue
