### ISSUE TITLE
Volume mount doesn't work on a Mac in /tmp/ directory

### ISSUE THREAD

**Issue by toli** [docker/compose#1039]
When following the Compose example at http://docs.docker.com/compose/#installation-and-set-up in the ```/tmp/composetest``` directory on a Mac, i'm seeing the following error: 
```
web_1   | python: can't open file 'app.py': [Errno 2] No such file or directory
```

On a Mac, /tmp/ is actually in /private/tmp/. 
If i move the underlying ```/tmp/composetest``` to any other location (ie /Users/toli/dev/composetest), the example works without any changes.

**Comment by kojiromike** [comment]
When you say _on a Mac_ you mean Boot2Docker, right? If so, then, your Docker host is the Boot2Docker virtual machine, not your Mac. Volumes are on the host. Volumes within `/Users` usually work because modern Boot2Docker creates a share between the Mac and the Docker host at the same path.

![screen shot 2015-02-28 at 11 56 40 am](https://cloud.githubusercontent.com/assets/1566303/6427011/2e010ec2-bf41-11e4-8016-dbe537a0bc94.png)

But `/tmp` is harder, because it is needed by the VM OS itself, and it is permissions-sensitive, so you can't simply share it with the VM.

**Comment by toli** [comment]
ah, seems like use error. thanks

**Comment by j2kun** [comment]
The problem here is that docker-compose silently fails (and mounts an empty volume!) instead of giving an error. This issue should be re-opened.

**Comment by salaev-privo** [comment]
Stuck with the same issue on Linux - can't map directory in /tmp
