### ISSUE TITLE
There are no online resources on how to access a docker compose application from the internet

### ISSUE THREAD

**Issue by crawlchange** [docker/compose#10410]
### Description

A docker compose application, started with "docker compose up", can be accessed from the localhost.

Please provide instructions or enable the feature to access the application from another machine, so that docker compose can be used to deploy applications in production.

Thank you.

**Comment by ndeloof** [comment]
There's no such documentation because this is out of the scope of Docker engine / Docker compose to manage your computer exposure to a public network, and also because there's no simple/single answer: depending your infrastructure, gateway, router, firewalls, this can take many forms. This basically is the same requirements as exposing a non-docker application, up to you to check your infrastructure for this purpose.
