### ISSUE TITLE
There are no online resources on how to access a docker compose application from the internet

### ISSUE THREAD

**Issue by crawlchange** [docker/compose#10422]
### Description

Description

A docker compose application, started with "docker compose up", can be accessed from the localhost.

Please provide instructions or enable the feature to access the application from another machine, so that docker compose can be used to deploy applications in production.

Thank you.

**Comment by crawlchange** [comment]
This ticket was opened before:

https://github.com/docker/compose/issues/10410

but it was "closed as completed", even though it is not completed and no resolution was given.

@ndeloof stated that: "There's no such documentation because this is out of the scope of Docker engine / Docker compose to manage your computer exposure to a public network, and also because there's no simple/single answer: depending your infrastructure, gateway, router, firewalls, this can take many forms. This basically is the same requirements as exposing a non-docker application, up to you to check your infrastructure for this purpose." before closing the ticket.

Answering @ndeloof comment:

@ndeloof Flask maintainers did not think it is out of scope for Flask to manage my computer exposure to a public network. In fact, they provided precise instructions here, and also tell what to expect:

https://flask.palletsprojects.com/en/2.2.x/quickstart/

See the section "Externally Visible Server". I would expect something similar from docker compose documentation, even if it is just to say that it is externally visible out of the box.

Now, running "flask --app hello-world run --host=0.0.0.0 --port 3000" makes the app visible from the external network. However, running a docker composer application AND BINDING IT TO THE SAME PORT makes it visible locally but not externally. So yes, this IS docker composer specific, because I can deploy any application written in any language to this exact same server in this exact same port, as I've been doing for years, but I can't for docker composer.

I didn't open this as a bug (and it should be opened as a bug) because I'm doing first things first. First thing is: provide in the documentation a clear step by step on how, IN GENERAL, to make a docker composer application visible from an external server (such as "flask --app `server` run --host=0.0.0.0" does for flask), so that I can properly open a bug ticket by following a pre-defined well-documented set of instructions.

And yes, I am forwarding my ports on the docker-compose.yml file

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
      
and I tried 0.0.0.0 too. Now if the procedure is something different, >>>please document that<<<.

**Comment by crawlchange** [comment]
To add on that, I just uninstalled the recommended version of docker:

https://docs.docker.com/engine/install/ubuntu/

and installed the snap one by doing 

apt-get remove docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
snap install docker

and the server works normally! It is visible from the outside!

SO THAT IS DEFINITELY A BUG ON THE APT-GET VERSION OF DOCKER!

So please add documentation (so that people know that it SHOULD work out of the box, as it does with the snap version!!) and let me know if you need me to open a new ticket, or if you can move this to a bug ticket!

By the way, I followed the EXACT instructions on that link for installation on a brand new and clean ubuntu machine.

**Comment by glours** [comment]
Hello @crawlchange 

Please try to stay calm, even if I can understand you're frustrated about the situation, injunction like `>>>please document that<<<.` or affirmation like `SO THAT IS DEFINITELY A BUG ON THE APT-GET VERSION OF DOCKER!` really don't make us want to help you.

First, when you create an issue there's a template, if you follow this template it's give us way more context to understand your problem and try to figure out what could happen. Giving a compose file and the steps to reproduce the issue is also very helpful.

When Compose run a multi-containers application, it create a internal network to be sure each containers could reach all the others, they are communicating in a close network. 
The port binding option you used, give you access from the host machine to the `frontend` service container via port `3000`, so you're able to interact from the host with your application via the `frontend` service. 

That's it, no more! If you want your service port to be reachable outside of your host,  it's now a server configuration purpose! It's up to you, regarding your infrastructure, to open dedicated port with your firewall or use a dedicated routing configuration to be able to reach your `localhost:3000` or `0.0.0.0:3000`

if this answer does not suit you, please provide us the information described in [the issue template](https://github.com/docker/compose/blob/v2/.github/ISSUE_TEMPLATE/bug_report.yml).

**Comment by ndeloof** [comment]
> installed the snap one ... and the server works normally!

This is EXACTLY what I mean by "_depending your infrastructure, gateway, router, firewalls, this can take many forms_". Thounsands Docker installations run without any issue with the official Docker deb package, but in your case there's probably some mismatch with another network-related component. Also would need first to check this is a Docker Compose or a plain Docker issue: if `docker run -p 5000:80 nginx` doesn't work either, then you should ask for assistance on github.com/moby/moby, not on compose repository (we also have a community slack channel by the way to ask for help)

**Comment by davidmozeler** [comment]
At this point, notice that this is not a bug that is going to tie me up anymore, since I completely resolved the issue for my server by running the snap version. Three points:

1- The instructions given above by glours must be in the README, and written very clearly. The fact that docker compose is served to external traffic by default (unlike, say, flask, that needs the 0.0.0.0 host) must absolutely be documented.

2- This bug is not affecting me anymore right now, since I moved to the snap version. However, this absolutely must be affecting or will affect thousands of people in a near future. I will check whether the issue happens with docker without compose, but I really don't have the extra time in the next few days. Again, this isn't affecting me, so at this point I will be just helping other people facing this extremely serious issue with the apt-get version of docker.

3- The only steps taken were the officially recommended steps on how to install docker on ubuntu, and the "ubuntu" here is a brand new and clean digital ocean droplet. I can provide more details in the near future but please notice how serious that issue is. It's still not clear whether the issue is in docker or docker compose. I will figure it out when I have some time available.

**Comment by crawlchange** [comment]
At this point, notice that this is not a bug that is going to tie me up anymore, since I completely resolved the issue for my server by running the snap version. Three points:

1- The instructions given above by glours must be in the README, and written very clearly. The fact that docker compose is served to external traffic by default (unlike, say, flask, that needs the 0.0.0.0 host) must absolutely be documented.

2- This bug is not affecting me anymore right now, since I moved to the snap version. However, this absolutely must be affecting or will affect thousands of people in a near future. I will check whether the issue happens with docker without compose, but I really don't have the extra time in the next few days. Again, this isn't affecting me, so at this point I will be just helping other people facing this extremely serious issue with the apt-get version of docker.

3- The only steps taken were the officially recommended steps on how to install docker on ubuntu, and the "ubuntu" here is a brand new and clean digital ocean droplet. I can provide more details in the near future but please notice how serious that issue is. It's still not clear whether the issue is in docker or docker compose. I will figure it out when I have some time available.

**Comment by crawlchange** [comment]
@ndeloof I can confirm, the issue applies even for docker run -p 5000:80 nginx!

Port 5000 is exposed to outside net (e.g. the flask example). Nginx from command above is accessible on wget 127.0.0.1:5000, but not from outside net. Massive bug in docker itself.

I will follow your advice regarding moby/moby. But I think this is something everyone who has any minimal stake in docker applications IN GENERAL should be very concerned with.
