### ISSUE TITLE
Dynamic Binding: Extending or Contracting an Application's Cooperative Network of Containers

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/compose#105]
Fig's documentation indicated "if there are existing containers for a service, fig up will stop and recreate them.." in order to process changes applied to the application's YML, for example, to add another component.  What are your thoughts on permitting dynamic application composition such that a new container with a desired service can be added to the existing cooperative network of docker containers that comprise the applicaion  without having to conceptually "restart" the entire network?  It seems to me that fig's operation/design focuses on statically defining the image and bindings between cooperative containers defined by images.  This certainly helps my effort as my application statically relies on a certain mix of containers, but once it my application is running, I'd like to dynamically extend or contract the application's feature set.

**Comment by dnephin** [comment]
The introduction of "smart recreate" in 1.4.0 made some progress here, but links still require some extra container restarts. The new docker networking support (which should be in soon) will fix the remaining issues.   I think #1676 will cover the rest of the work required to make this happen.

Since we're tracking work in other tickets, I'm going to close this one.
