### ISSUE TITLE
[BUG] Docker has deployed breaking changes preventing network access.

### ISSUE THREAD

**Issue by crawlchange** [docker/compose#10584]
### Description

This has been reported multiple times.

https://github.com/docker/compose/issues/10581
https://github.com/docker/compose/issues/10422
https://github.com/docker/compose/issues/10410

Some insider is working to suppress reporting.

I'm in contact with hundreds of companies facing the exact same issue. This is causing billion-dollar losses already. Docker is a liable company and we're considering a class-action lawsuit.

There are no "network configuration issues". This happens across all networks, all operating systems. It only happens with the latest distributions of docker. Downgrading is an instant fix.

### Steps To Reproduce

1. docker run -p 5000:80 nginx
2. The server is not accessible outside of the host machine

### Compose Version

```Text
Docker Compose version v2.17.2
```

### Docker Environment

```Text
Client:
 Context:    ***
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version:
 init version: N/A
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-67-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.763GiB
 Name: ubuntu-s-1vcpu-512mb-10gb-nyc1-01
 ID: 27BN:GQAJ:LWHE:VFJE:CBPP:P67V:QDU4:24AU:YJ56:5NAE:SJ7S:R2RR
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by polarathene** [comment]
Since all your issues are getting locked quickly, it's difficult to chime in :sweat_smile: 

## Response

### Communication

> I'm in contact with hundreds of companies facing the exact same issue. This is causing billion-dollar losses already. Docker is a liable company and we're considering a class-action lawsuit.

You know that attitude isn't doing you favours when you are seeking assistance? Threatening legal action works against your benefit, as engaging with you becomes a concern.

It's also very difficult to take seriously.. If such losses were actually happening, the tech talent at those companies is missing some important skillsets.

---

### Misleading information

> There are no "network configuration issues". This happens across all networks, all operating systems. It only happens with the latest distributions of docker. Downgrading is an instant fix.

This is another questionable statement. It's already been communicated to you that if what you've experienced was true, it would be affecting a much larger audience and there would be more activity reporting on it. Yet when I saw all your referenced issues, they're all from you over the past few months.

You've identified that the issue doesn't affect public access to services not running within a Docker container, that's good. You've only explicitly mentioned Digital Ocean as a service provider though.

I have been frequently using various versions of Docker and across a variety of operating systems (and releases). I don't experience this issue.

I mostly use Vultr with Ubuntu or Fedora instances (_other vendors: RamNode, Contabo_), but also look after a server running SUSE, and personal systems with Arch. I've not experienced the issue you're describing, so that doesn't add up?

---

### Conclusion

Clearly you have a misconfiguration issue on your end, which as has been relayed to you previously.

It is not the responsibility of Docker to educate you on how to resolve that (_that can vary by environment_). You were directed to community platforms to seek guidance, as this isn't considered an actual bug.

If you still felt that Docs should be improved after doing so and finding a solution, you'd be welcome to contribute them to assist others; most usually lose interest due to additional time/effort that requires (_much like you did earlier when the snap solution worked for you until recently_).

## Reproduction (_attempt unsuccessful_)

Out of curiosity, I created a droplet on Digital Ocean, Ubuntu 22.10 basic (1vCPU + 512MB RAM), I then did the following:

```bash
apt-get update
apt install docker.io
docker run --rm -p 80:80 traefik/whoami
```

I then went to the public IP in the browser at port 80 and no problems, connection successful and the returned response was the expected content.

<details>
<summary>docker info</summary>

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-23-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 465.7MiB
 Name: ubuntu-s-1vcpu-512mb-10gb-nyc1-01
 ID: AQRY:I6Z4:PHQH:NASA:IGL2:2DMD:GQIF:ZQ3J:RC4N:SOEH:HEEJ:CC73
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</details>

For added measure, I installed the latest release as per [Docker's official docs on installing for Ubuntu](https://docs.docker.com/engine/install/ubuntu/)

<details>
<summary>docker info (latest)</summary>

```
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-23-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 465.7MiB
 Name: ubuntu-s-1vcpu-512mb-10gb-nyc1-01
 ID: 33a59e0e-ad24-4ad2-bda7-69c56edf8c73
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Again, **no problems reaching the droplet container from my system**.

I'm not going to bother with compose, as this is already enough to contrast against what you're claiming is affecting so many when the problem is clearly on your end.

This rules out Digital Ocean at fault. If you're actually reproducing on a clean droplet like I just did with a simple container (_`docker run -p 5000:80 nginx` works just as well btw_), then that rules out anything to do with your own projects, despite the failure you experience. Unfortunate, since that'd be easier to troubleshoot the cause.

Potentially an issue with your own network/router. I've had problems with router hardware in the past where no matter what you did with your systems, network issues occurred for anything not cached (_eg: DNS, or I assume mac address related if machine specific_). I know of others that have had bizarre networking issues and resetting the router usually fixes it at least temporarily.

..But then you cite being able to connect to the same remote host (droplet) without issue, so long as it's not running within a Docker container. That seems odd, especially since I cannot reproduce it... are you sure you actually did a fresh instance and test like I just did?

---

Goodluck with figuring it out :sunglasses:

The money for attempting to take legal action would be better spent on talent that can assist you directly.

I just wanted to reach out so you didn't feel "suppressed", everything is working fine elsewhere and it sounds more like a configuration or environment issue on your end somewhere (_especially since information you've relayed seems very misleading, and threats likely empty_).
