### ISSUE TITLE
Watch action: restart

### ISSUE THREAD

**Issue by Korijn** [docker/compose#11062]
### Description

Right now I believe the `docker compose watch` command supports two action types, `rebuild` and `sync`. I'd like to see one more option: `restart`.

There are application binaries (in my case it's the python framework `celery`) which don't support hot reloading when source code files change. So `sync` is not enough to pick up the changed source code, and `rebuild` is overkill because the dependencies did not change.

All I need is a quick `restart`!

**Comment by rollsover** [comment]
I would also like this feature, but I think just `docker compose restart {SERVICE}` is not enough, since file synchronization is also needed.

For this reason I use `reduild` in such cases.

But `rebuild` has a problem - during build it does not restart the build due to repeated changes in the given context. Therefore, updating two files in a row we will not get the result we need.

What to do? – Use `sync` and detect changes at the application level.
Or wait for this feature, but I don’t see an adequate implementation. The only thing in my mind is `sync-and-restart`.

**Comment by Korijn** [comment]
Restart could be enough combined with a bind mount though right?

**Comment by rollsover** [comment]
@Korijn in my paradigm for using `volumes`: their use should be exclusively anonymous and only the data generated and used by the application (not code) should be mounted (for example, a database, logs, etc.).

Why?: The `compose` configuration can spread to server environments, and there `volumes` of code are very dangerous, so I think the guys will allocate a separate `develop` block within which we will work locally.

**Comment by Korijn** [comment]
Ah okay. We only use compose in local development and testing scenarios.

**Comment by Korijn** [comment]
Wow, quick! Nice work! Thanks.

**Comment by binaryfire** [comment]
Hi guys. Was the standalone `restart` option dropped? I only see `restart+sync` in the docs: https://docs.docker.com/compose/file-watch/

We need to restart containers in local development without any file sync (since we're using bind mounts). From what I read in the docs, there's no way to just "watch and restart"? Unless I'm misunderstanding something.
