### ISSUE TITLE
Bump buildkit version to 0.12.4

### ISSUE THREAD

**Issue by eoshea-cmt** [docker/compose#11313]
### Description

0.12.4 has a bugfix for buildkit that would be great to get into compose:
https://github.com/moby/buildkit/pull/4346

**Comment by thaJeztah** [comment]
Compose is already using master / v0.13, so should already have that fix (from the master branch) but due to go's pseudo-version generating, it shows as `v0.12.xxx`; https://github.com/docker/compose/blob/06af729dc8988b7f926efa4ad796016c9b439595/go.mod#L14

See https://github.com/docker/compose/pull/11289#issuecomment-1864124306

**Comment by eoshea-cmt** [comment]
I see - is there anything to be done about releasing a new version of docker compose with the latest buildkit?

also - any idea what to do about this issue where the docker-ce is not getting updated when compose is released?:
https://github.com/docker/docker-ce-packaging/issues/967

**Comment by thaJeztah** [comment]
> I see - is there anything to be done about releasing a new version of docker compose with the latest build

I'm not a maintainer for docker compose, and don't know if a new release is scheduled (@milas or @glours may know)


> any idea what to do about this issue where the docker-ce is not getting updated when compose is released?:

docker compose is incompatible with go1.20 (see https://github.com/docker/docker-ce-packaging/pull/965), which is the version used to build packages of docker engine 24.x, unfortunately that means that no new packages can be published until either docker v25 is released, or docker v24 switches to go1.21 or above (there's a lot of risk involved in updating go version of the docker engine, which is why it tends to be a version behind).

docker 25 will be released soon though; beta packages are already available in the test channel, which also has package of docker compose v2.23.3 (see https://download.docker.com/linux/ubuntu/dists/jammy/pool/test/amd64/)

Alternatively, static binaries can be downloaded from the github repository https://github.com/docker/compose/releases

**Comment by milas** [comment]
We don't have a specific date for a Compose release, but it'll likely be Soon ™️ - there's a variety of fixes queued up on `main`, but we've had limited availability these past few weeks.

If you want a bleeding edge build, beyond building from source, you can also look at the [docker/compose-bin](https://hub.docker.com/r/docker/compose-bin) image. The `:edge` tag is published on each commit to `main`. A tool like https://github.com/crazy-max/undock can be used to get the binary out of the OCI image.
