### ISSUE TITLE
[idea] Allow docker compose to run 'all' services even if profiles are specified for the default condition

### ISSUE THREAD

**Issue by Interaze** [docker/compose#11383]
### Description

Docker profiles are awesome. However, once you specify profiles to services, the default condition of `docker compose up`  is no longer to run all services (only unspecified profiles). If we could still support the base case it'd be very appreciated, as it reduces the development friction of users going from not using profiles, to using it. While you could specify an all profile, this becomes an additional overhead to the structuring, so it'd be nice to maintain the same convention even with profiles. Additionally, I do acknowledge this is likely intentional to not support the default all, and enforce users to get accustomed to it, but I believe it may add more confusion to those not used to it. Thanks!

**Comment by ndeloof** [comment]
profiles are designed to let you declare additional "utility" services that are not required for your application. This is fully intentional **not** to run those by default. You can use `--profile='*'` to enable all profiles.

About profiles adoption, a pretty common pattern is to declare pseudo-services only used by `docker compose run..` command with profiles, or to group services involved in some subset of user's application (example: frontend, when a backend developer will only use backend services).

Closing this issue as "not planned"

**Comment by Interaze** [comment]
Thanks for the response. It seems I was using it then for a different purpose. Thanks!
