### ISSUE TITLE
[BUG] config command format JSON broken

### ISSUE THREAD

**Issue by ramundomario** [docker/compose#11627]
### Description

[Config command](https://docs.docker.com/reference/cli/docker/compose/config/) seems to ignore the format option, printing the content always in YAML

We're experiencing this behaviour since few hours ago with v2.25.0, rollbacking to previous version (v2.24.7) fixed the issue

### Steps To Reproduce

1. Execute the command `docker compose -f docker-compose.yml config --format=json`
2. Output is in YAML instead of JSON

### Compose Version

```Text
Docker Compose version v2.25.0
```

**Comment by Xeckt** [comment]
Quite new to learning compose and it's source so take my findings with a pinch of salt but, it looks like the `runConfig` function inside `cmd/compose/config.go` is receiving `false` for `opts.noInterpolate`, so it never reaches `formatModel()` due to the if condition - not sure as to why it's false, as it seems to show `true` in v2.24.7. So it's defaulting to a standard yaml config.

```go
func runConfig(ctx context.Context, dockerCli command.Cli, opts configOptions, services []string) error {
	var content []byte
	fmt.Println(opts.Format, opts.noInterpolate)
``` 
shows:
```
json false
```

**Comment by Xeckt** [comment]
Yeah, this looks intentional in the latest release - check the notes: https://github.com/docker/compose/pull/11604

**Comment by lemeurherve** [comment]
This is unfortunate 😓

Adding `--no-interpolation` breaks our usage, it doesn't seem to resolve this issue.

How can we get it working with interpolation?

**Comment by lemeurherve** [comment]
As a workaround, we can use pipe to `yq --output-format json` but it adds a dependency.

**Comment by ramundomario** [comment]
@lemeurherve It should be fixed in the next release of compose with https://github.com/docker/compose/issues/11646
As a workaround you could rollback at the previous version
