### ISSUE TITLE
[FEATURE REQUEST/BUG?] When passing through "--device /dev/snd" respect hosts audio routing

### ISSUE THREAD

**Issue by Rastafabisch** [docker/compose#11648]
### Description

Hello community,

configuring a docker container, which outputs sound [I realised that the container does not respects the hosts currently selected audio device](https://github.com/mikebrady/shairport-sync-docker/issues/22) (unless I'm missing some functionality?). 
Even though I changed the audio routing using `amixer` on the host the containers audio kept playing through the host's hardware's default audio device. This is true even when the host's default audio device is configured in `/etc/asound.conf` (though passing through `/etc/asound.conf` as a volume in a `docker-compose.yaml` file at least "fixes" this. 

However I feel, that a container should always respect the audio device currently selected audio device for sound routing. - At least unless specifically told otherwise, like with a dummy `asound.conf`. 

Implementing this like a flag when passing through /dev/snd could be a easily configureable option.
Like `"/dev/snd"` (or `"/dev/snd auto"`) defaulting to respecting the host selected audio, with `"/dev/snd [some_name/number]"` specifying the desired output device.

All that said, there might already be something similar, which I have not found and I'm not aware of. I saw that something like this can be achieved with the `docker run` command though this also does respect the host's selection. I've not found anything as to how to implement this in a `docker-compose.yaml` file. 

Best Rastafabisch

**Comment by ndeloof** [comment]
AFAICT this issue is not specific to docker compose so should be reported on https://github.com/moby/moby
I'm not used with Linux audio but AFAIK this is a nightmare :P 

IIUC the "default audio device" mechanism is based on `/etc/asound.conf` to declare the device to be used. Then you'll need to mount this file in container in addition to the configured device to use. Container will then replicate the device selection mechanism a standard linux process would execute.

**Comment by ndeloof** [comment]
Closing as issue is unrelated to Docker Compose and should be reported as a feature request on moby project
