### ISSUE TITLE
docker-compose重启服务时间太长，这是什么原因

### ISSUE THREAD

**Issue by Handikang** [docker/compose#11720]
如图片所示，下面的服务重启需要很久，据我所知docker应该在一分钟内就完成所有的重启动作。
![image](https://github.com/docker/compose/assets/42713276/19fae9ee-9a37-4566-bada-a4c5921fc8eb)
下面是我系统的基本信息
![image](https://github.com/docker/compose/assets/42713276/c2cad3dd-edb6-4d45-b15e-e4b3c5cfedcb)

**Comment by glours** [comment]
Hey @Handikang 
if the translation was correct, your issue is the time Compose is taking to start one of your service, right? (please, next time, try to post your issue in english, it's easier for everyone engage with this product both users and maintainers 🙏 )
If so there is no time guarantee about container startup time, depending on what is done during its boot process it can take a while to be considered as started, for example maybe your mysql database is taking more time to seed its data?

By the way you're using an old version of the docker engine `v20.10.10` maybe you could also try the latest `v26.0.0`? 

Can you give us more details? Such as the compose file composition?

**Comment by Handikang** [comment]
I used the same Docker engine on other computers and restarted the service quickly, so I don't think it's a problem with my service. This problem has been bothering me for a long time

**Comment by glours** [comment]
@Handikang I understand you frustration here but without more information I won't be able to help you

**Comment by ndeloof** [comment]
Please use `docker inspect` to capture container state when you see it stuck in this "restarting" state.
Do you have depends_on relations between services ?

**Comment by Handikang** [comment]
@ndeloof ,当我使用docker inspect的时候，没有任何反应

**Comment by Handikang** [comment]
服务之间是有依赖关系的

**Comment by Handikang** [comment]
![image](https://github.com/docker/compose/assets/42713276/61fc5431-2ed9-4c70-b6cb-f8c3903009fd)

**Comment by ndeloof** [comment]
if docker inspect hangs, as it seems according to your screenshot, then you have an issue with your docker engine. Issue is not related to compose. Please check engine logs for any reported error.
