### ISSUE TITLE
Feature Request: Web GUI

### ISSUE THREAD

**Issue by imton** [docker/compose#1215]
Docker Compose builds the ultimate layer on top of docker/swarm for controlling. It'd be awesome if we can give it a GUI.

I am thinking, could docker-compose become a (json) API too?

**Comment by itsravinder** [comment]
+kind/feature

**Comment by the-destro** [comment]
@imton This has already been discussed and kinda shot down in #1033 . I have a very rough POC that uses compose to manage groups of containers: https://github.com/the-destro/amhappy

**Comment by imton** [comment]
@the-destro cool! put a screenshot whenever possible and I will probably help

**Comment by francescou** [comment]
@imton I think you can find interesting my project: https://github.com/francescou/docker-compose-ui 

basically I've implemented a REST API on top of docker-compose and a GUI (i.e. an AngularJS application).

You can also use the API to develop your own client and to manage docker-compose application stacks with Continuous Integration tools (e.g. Jenkins).
Using the API I've successfully set up a Continuous Deployment pipeline of multiple docker compose stacks so that each git push triggers the deploy of the updated version of my application.

**Comment by dnephin** [comment]
A UI may be very appealing to some users, but it's not to everyone. Adding this to compose itself would be a mistake. It's easy to implement as an "add-on" and having them as a separate components makes it easier to iterate on each.

We may also look at #230 to make the write features more accessible from a gui
