### ISSUE TITLE
[BUG] Error response from daemon: invalid mode: rw,nocopy,www when using Volume subpath

### ISSUE THREAD

**Issue by stivyw** [docker/compose#12161]
### Description

I think the bug #12075 was not fixed by #12078. 
I'm getting this error message or I'm doing something wrong.
![Screenshot 2024-09-24 at 22 36 37](https://github.com/user-attachments/assets/162ce9f6-7a75-4175-993e-c9939a5cb570)

### More information

All the information are here #12075

### Compose Version

```Text
Docker Compose version 2.29.7
Docker Compose version 2.29.7
```

**Comment by jhrotko** [comment]
Hello @stivyw,

two PRs were merged this week to handle the original issue:
- https://github.com/compose-spec/compose-go/pull/688
- https://github.com/docker/compose/pull/12177

In order to make your spec work you will also need to define you bind path in Docker Desktop settings > Resources > File Sharing and add the bind mount path `/sw/etc/balance` in Virtual file shares.

Moreover, when using the `subpath` under `volume` make sure the `subpath` exists in `/sw/etc/balance`
