### ISSUE TITLE
docker-compose rm -v

### ISSUE THREAD

**Issue by sourav82** [docker/compose#1227]
What is the purpose of the switch -v with "docker-compose rm"? 

I thought it would delete the volume associated with the container but it is not doing so. In my configuration, I have one container with volume mapping (hostPath:containerPath).

If I use "docker-compose rm -v --force <<service_name>>", will it delete the volume along with the container?

**Comment by thaJeztah** [comment]
Bind-mounted volumes are not "managed" by Docker/Docker Compose, because they can be created from *existing* directories/files on the host. Because of that, Docker/Compose will not remove those.

**Comment by sourav82** [comment]
Thanks @thaJeztah. I was wondering the scenario where a container is started with --volumes-from another container and that container is removed with -v option. 

Then the volume of the container created with volumes from the deleted one will also be deleted?

**Comment by sourav82** [comment]
I just tried this but noticed that even if I delete the volume with -v of the dependent container, the depending container still have the volume attached. Below is my YML -

web:
  build: .
  volumes: ['/data']
  ports: ['22']
web2:
  build: .
  volumes_from: ['web']
  ports: ['22']

I deleted service "web" with "docker-compose rm -v web" but the volume "/data" is still attached with web2.

If this is not the intented behavior of "-v" switch, then what is the usecase of "-v" switch with "docker-compose rm"?

**Comment by thaJeztah** [comment]
@sourav82 correct; for regular volumes (non bind-mounted), Docker will not delete the volume if other containers are still referencing it.

This is by design; say, you want to migrate a container to a new version of an image, but you *don't* want to loose the data that's stored in the volume (data is important), then you can do;

```bash

# the "old" container
docker run -d -v /my-data --name mycontainer myimage:oldest

# start a "new" container, but use the "volumes" of the old container
docker run -d --volumes-from mycontainer --name mynewcontainer myimage:latest

# then remove the old container
docker rm -v mycontainer
```

Docker will see that the "mynewcontainer " container is still using the volumes, and even though you say `rm -v`, it will prevent you from deleting the volume (otherwise your data will be lost).

If the *last* container referencing the volumes is removed (with `-v`), the volume will also be deleted;

`docker rm -v mynewcontainer`

I'm explaining this with "docker" commands, but the same should apply when using compose (compose just "controls" docker via the docker remote API)

**Comment by sourav82** [comment]
@thaJeztah, Great! Thanks a lot for the explanation!!
