### ISSUE TITLE
Docker don't flush dns cache if host have been changed of the /etc/resolv.conf

### ISSUE THREAD

**Issue by prometheus-tao** [docker/compose#12304]
### Description

One of the host run many containers by compose up, Since host have been changed, And then dns request send to old it of the container too

Container resolv as following
`nameserver 127.0.0.11
options timeout:1 attempts:1 rotate single-request-reopen ndots:0`

Only one method by docker restart? Is anything have better?

**Comment by ndeloof** [comment]
AFAICT this isn't a Compose issue, but a general Docker question regarding engine support for changes on host's configuration.
Also not a feature request but a question/request for support
You should better join Docker community slack for such discussion

About your issue, AFAIK docker engine (and as such all containers) need to be restarted so that host's network config changes are applied to containers.

Closing as "not a compose issue"

**Comment by prometheus-tao** [comment]
okay,thank you so much!
