### ISSUE TITLE
docker-compose and passwords from environmental variables

### ISSUE THREAD

**Issue by ctmnz** [docker/compose#1235]
I was experimenting with docker-compose and I saw something a little bit disturbing in my output of phpinfo() function: LAMPDB_1_ENV_MYSQL_ROOT_PASSWORD lamppass

my docker-compose.yml:

lampapp:
build: .
ports:
- "8000:80"
links:
- lampdb
- lampmemcache
volumes:
- /var/
lampdb:
image: "mysql:5"
volumes:
- ./mysql:/etc/mysql/conf.d
environment:
- MYSQL_ROOT_PASSWORD=lamppass
lampmemcache:
image: "memcached"

I know that it is set by 'environment:' but my question: Is it O.K. (I think it is not) any application from my 'composed' docker infrastructure to see set passwords from the installation process ?

**Comment by thaJeztah** [comment]
@ctmnz I think you opened this issue just before I provided the additional information in https://github.com/docker/docker/issues/11983#issuecomment-88620911. Do you need more information, or is it safe to close this issue?

**Comment by ctmnz** [comment]
@thaJeztah If it is known as security issue by design, and it is okay for docker developers.. Yes we can close this issue.

**Comment by thaJeztah** [comment]
@ctmnz yes, it's "by design", which doesn't say it's a **good** design, but it's the current situation and cannot really be changed now without breaking backward compatibility.

IIRC, There are plans to offer alternatives in future and make more use of discovery mechanisms for linking, so that "old fashioned" links are no longer a requirement (and the env-vars no longer leaking between containers)

**Comment by ctmnz** [comment]
@thaJeztah I see. I just tried to help. Noting more.

**Comment by thaJeztah** [comment]
@ctmnz I understand, and it's really appreciated. I decided to add the extra information, also for people arriving here (e.g. via Google), so that they understand the current status.

Thanks for taking the time to open this issue, doing that is important and really appreciated!
