### ISSUE TITLE
docker-compose pulls images without being told to do so

### ISSUE THREAD

**Issue by pbecotte** [docker/compose#1242]
I use docker-compose up -d to bring up my dev environment in a vagrant vm.  At the end of the day I vagrant halt.  The next day, I repeat the process.  docker-compose begins pulling layers again.  My understanding is it is only supposed to do a pull when the image isn't found locally or when I run docker-compose pull.

**Comment by dnephin** [comment]
Sorry for the slow response.

That's correct, `pull` should only happen if the image label isn't found.  Is it possible that something deleted the images?  We haven't heard any other reports of this.

Going to close this issue since we've released a couple versions since this was first reported. If you're still able to reproduce this issue please re-open with the output of `docker-compose version` and the commands you ran.
