### ISSUE TITLE
Compose seems to not forward custom ports

### ISSUE THREAD

**Issue by andergmartins** [docker/compose#1256]
Running the container using docker command works:

    $ docker run ........ -p "8086:8080".....

Returns this: `0.0.0.0:8086->8080/tcp`

But using compose, It seems to not forward the port:
Here is part of my compose file:

    api:
        image: .....
        links:
            - .......
        ports:
            - "8086:8080"
    
Running it:

    $ docker-compose run api

Returns this: `8080/tcp`

**Comment by thaJeztah** [comment]
This is because `docker-compose run` is meant for running one-off tasks in a container, see the documentation; https://docs.docker.com/compose/cli/#run;

> by default no ports will be created in case they collide with already opened ports.

If you want to start a service, using the ports (and command) that's specified in your `docker-compose.yml`, use `docker-compose up [-d] [service]`. Where `-d` makes the service run "detached" (in the background) and `service` is/are the name of the service(s) you want to start. Leave out the service-name(s) to start all services.

**Comment by andergmartins** [comment]
Ops, sorry, missed that. Now that I'm using the correct command it works! :) 
Thank you for the quick response. My fault, closing this.

**Comment by thaJeztah** [comment]
No worries, it can be confusing that `docker-compose run` is *not* a complete equivalent of `docker run`. Nothing to be ashamed of :smile:

**Comment by tonypujals** [comment]
Would be nice if there was a flag to allow this.

**Comment by thaJeztah** [comment]
@tonypujals there's now an option to enable ports; `--service-ports`, see the docs: https://docs.docker.com/compose/reference/run/

**Comment by cjw296** [comment]
Shame it's not the default with an option to disable...

**Comment by augnustin** [comment]
I agree I'd be much more comfortable with ports opened by default with an option to disable.
At least if someone tries to open ports that are already binded, an explicit error is shown, while when using `run` without `--service-ports`, nothing is said and it might take a while to understand what is going on!

Besides, I'd be in favor of having an option `--try-ports` that would open ports if available, otherwise wouldn't without failing, along with a message: `try-ports options: Ports already in use, no port opened` or something.

**Comment by holms** [comment]
Been searching for this issue for hours. I'm running app container which depends on selenium, and selenium can't connect back to app, because app container doesn't expose any ports. How would I suppose to find out this?
