### ISSUE TITLE
How to specify CMD in the yml file?

### ISSUE THREAD

**Issue by volkanunsal** [docker/compose#1279]
I have a service where I need to specify a CMD. I figured I should be able to do this in docker-compose, but I got this error:

```
Unsupported config option for master service: 'cmd'
```

**Comment by thaJeztah** [comment]
You'll need to use `command:`. See the documentation; https://docs.docker.com/compose/yml/#command

**Comment by volkanunsal** [comment]
thanks!

**Comment by vstoykov** [comment]
Link to the documentation is broken

**Comment by thaJeztah** [comment]
looks like it's moved to https://docs.docker.com/compose/compose-file/, but a redirect is missing for the old location

**Comment by chrissound** [comment]
This is a bit difficult to Google for some reason. Here is docs to v2: https://docs.docker.com/compose/compose-file/compose-file-v2/#command

**Comment by yb66** [comment]
May I suggest that this is aliased this to `cmd`, or at the very least "cmd" is mentioned within the ["command" section of the compose file reference](https://docs.docker.com/compose/compose-file/#command). I've come to this page because I ran a search for "docker-compose yml cmd" and also searched the compose file reference page for "cmd" only to find out the name is different.

Please, be consistent in the interface or at least make it easy to find things by the tools we use. This is one of the first things we all learn as developers, *for good reason*.

Regards,
iain

**Comment by olsonpm** [comment]
Looks like things have changed - this new link helped me
https://docs.docker.com/reference/compose-file/services/#command

> command
> command overrides the default command declared by the container image, for example by Dockerfile's CMD.
> `command: bundle exec thin -p 3000`
>
> The value can also be a list, in a manner similar to Dockerfile:
> `command: [ "bundle", "exec", "thin", "-p", "3000" ]`
> If the value is null, the default command from the image is used.
>
> If the value is [] (empty list) or '' (empty string), the default command declared by the image is ignored, i.e. overridden to be empty.

and looks like they still don't want the names to be consistent
