### ISSUE TITLE
Container's name inside docker-compose.yml

### ISSUE THREAD

**Issue by Nelrohd** [docker/compose#1300]
Hi,

Currently `docker-compose` only supports the characters `[a-zA-Z0-9]` for the container's name inside `docker-compose.yml`, which is not consistent since you can name your docker `my-super-container` and use that name with the `FROM` command in the `Dockerfile`.

What about that? I didn't see any discussions about it.

**Comment by thaJeztah** [comment]
There are various existing issues for this, for example https://github.com/docker/compose/issues/652, https://github.com/docker/compose/issues/869 and https://github.com/docker/compose/issues/941

For an explanation as to why this wasn't implemented so far, see https://github.com/docker/compose/issues/941#issuecomment-73731608

I think it's best to close this issue and continue the discussion on the existing issues, so that the discussion takes place in a single location.

**Comment by Nelrohd** [comment]
Thanks, I close it.

**Comment by aanand** [comment]
See https://github.com/docker/compose/issues/1519
