### ISSUE TITLE
how to pass timezone when starting through docker-compose ?

### ISSUE THREAD

**Issue by PositiveAlex** [docker/compose#1324]
Subj.

I want to set up normal timzone and time in my image.

i can run it using `docker run --timezone` but the docker-compose says `Unsupported config option for db service: 'timezone'
`

**Comment by dnephin** [comment]
I can't find any reference to `docker run --timezone` in the help text or docs. Where are you seeing this?

I don't know how that could possibly work, because each distro has a slightly different way of configuring the timezone.

The way to configure a timezone would be one of these, depending on what container you're running: http://unix.stackexchange.com/questions/110522/timezone-setting-in-linux
