### ISSUE TITLE
scale renumbers the links

### ISSUE THREAD

**Issue by jdmarshall** [docker/compose#1340]
when using `docker-compose scale service=2` docker will claim it has spun up service_1 and service_2 but upon running `docker ps` or connecting to one of the linked machines to see the hosts entries, it has instead created service_2 and service_3

Obviously this causes problems when trying to configure things to talk to each other.

**Comment by mtlaird** [comment]
I'm also seeing this issue. The numbering also increases each time you bring the docker stack up and down. I'm now up to service_39 in my environment.

**Comment by dnephin** [comment]
The numbers should only increase if the old containers were not removed and not-recreated, which would be a bug.

The behaviour here has changed in the last couple of releases.

I'm going to close this issue (it should be fixed in 1.4.0). If you're still able to reproduce the issue with the latest release, please re-open.
