### ISSUE TITLE
Using extends to replace "build" with "image" results in an error when build directory path does not exist

### ISSUE THREAD

**Issue by turtlemonvh** [docker/compose#1350]
# Reproducing the Error

Create 2 files.

    # compose_base.yml
    sleeper:
      build: /tmp/doesnotexist

    # compose_local.yml
    sleeper:
      extends:
        file: compose_base.yml
        service: sleeper
      image: ubuntu:12.04
      command: sleep 1000

Run 

    docker-compose -f compose_local.yml up -d

You will get the error:

    build path /tmp/doesnotexist either does not exist or is not accessible.

According to [the docs](http://docs.docker.com/compose/extends/#adding-and-overriding-configuration)

> In the case of build and image, using one in the local service causes Compose to discard the other, if it was defined in the original service.

Since that section is replaced, a reference to an invalid path should not result in an error.

# Diagnosis

The root of the problem is that [`other_loader.make_service_dict` is called before the configurations are merged](https://github.com/docker/compose/blob/4926f8aef629631032327542a56ae35099807005/compose/config.py#L112).  Part of `make_service_dict` is a call to [process_container_options](https://github.com/docker/compose/blob/4926f8aef629631032327542a56ae35099807005/compose/config.py#L162) which does a check on existence of the build directory.

I realize this is done this way to make recursive loading of parent configs easy, but I think that those checks are not necessary if the configuration being built is a configuration that is being extended from *and* that part of the configuration is being overwritten.

# Why its a problem

If I want to build an image on one machine, then just run the image I build on another machine (in production), I'd like to be able to use the same base config file in both environments.

With the current bug / implementation we have 2 options:

1. Create another compose.yml file just for building that inherits from base and defines build directories for each section. The base compose file would then have to define an `image` section because [one or the other is required](https://github.com/docker/compose/blob/master/compose/service.py#L63).
1. Create empty directories on the machine where docker-compose expects to find build directories

Both of these are pretty silly options.

**Comment by turtlemonvh** [comment]
One possible solution would be to only resolve the host paths defined in the container options when on the final level of the inheritance stack.  That is, if you're looking at something you're extending, don't both resolving its paths.  This could be handled with a configuration flag.

If the community is open to this option, I'll submit a PR for this on Monday.

**Comment by turtlemonvh** [comment]
Pull request: https://github.com/docker/compose/pull/1357

**Comment by turtlemonvh** [comment]
This can be closed now that #1357 is merged.

**Comment by ebmeierj** [comment]
This issue appears to have re-surfaced:

> docker-compose --version
docker-compose version 1.6.0, build d99cad6


> docker info
Containers: 28
 Running: 0
 Paused: 0
 Stopped: 28
Images: 199
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 439
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-66-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.861 GiB
Name: jebmeier
ID: VHZF:73GG:GYMV:IOPQ:JOF5:3LRR:5N5T:7XDD:ZI24:M5GJ:3YMN:RWHZ


> cat test.yml
version: "2"
services:
  foo:
    image: "foo"
    build:
      context: ./foo


> docker-compose -f test.yml up --no-build foo
ERROR: build path /home/joe.ebmeier/sbf-root/foo either does not exist, is not accessible, or is not a valid URL.

**Comment by dnephin** [comment]
This is the expected behaviour with the v2 format. `build` no longer overrides `image` (or vice versa), they are complimentary: https://docs.docker.com/compose/compose-file/#image

**Comment by ebmeierj** [comment]
But if the image already exists and you aren't going to build it I don't see why you would require that the build path exists. This seems like a cumbersome requirement when using docker-compose to stand up a production environment where the build environment may not necessarily exist.

Further, it seems especially odd when you have explicitly specified that you don't want a build to ever take place (--no-build).

**Comment by aanand** [comment]
OK, I agree this is a bit confusing. Here's the current logic:

1. If the build path does not exist, the file is not valid.
2. If the image does not exist, Compose attempts to build it, unless `--no-build` was passed.

I guess the case where the build path doesn't even exist is one we didn't consider, because we assume that people are either running `docker-compose` from their local machine with their environment variables pointing at a production environment, or are running it somewhere else but with the whole source tree checked out.

Even if false, this used to be a harmless assumption to make when `image` overrode `build`, but now it's an issue.

We could relax (1) and make it a warning instead of an error. Then you'd get a different error, because the image doesn't exist. To avoid that, you'd need to run `docker-compose pull` before `docker-compose up`.

**Comment by ebmeierj** [comment]
That sounds good to me. Thanks for being flexible.

**Comment by dnephin** [comment]
#1973 is the issue for being able to run some commands without doing full config validation. I don't think we'd want to relax the build path requirement for every command.

Another way to solve this problem is to restructure your Compose file. You can have a canonical Compose file in `docker-compose.yml` that only uses images. Then in a `docker-compose.override.yml` (or a `docker-compose.dev.yml`) you can add `build:`, host `volumes:`, and other settings that only apply to dev.

Since your base Compose file is prod-ready, you can run with just `-f docker-compose.yml` and wont run into the validation problems.
