### ISSUE TITLE
ease distribution packaging: don't set upper bounds for versions of dependencies

### ISSUE THREAD

**Issue by TomasTomecek** [docker/compose#1401]
Since you are setting upper bounds for dependencies, it is hard to package your software in distributions. E.g. right now I can't update `requests`, because `compose` requires `requests < 2.6`.

Is there some hard requirement behind those upper bounds?

**Comment by aanand** [comment]
We've had problems in the past where dependent libraries introduce a breaking change in a minor point release (indeed, if I recall correctly, this has happened with `requests`). For that reason, we lock to a tighter version range so that people installing with Pip don't get a broken install.

Can you package the Compose binary?

**Comment by TomasTomecek** [comment]
Right, that's really sad actually. 

In Fedora and Red Hat family distros, it's not possible to package a binary. In case of dependency issues we still can patch compose and remove those upper bounds (and watch for any issues).
In gentoo I'll probably do my own ebuild.

**Comment by dnephin** [comment]
I've found that using a virtualenv is always a good idea if you want to avoid version conflicts. https://github.com/spotify/dh-virtualenv exists for making debian packages using a virtualenv, but I'm not aware of any equivalent for rpms.

I'm going to close this, since I don't think we can relax these at this time.

**Comment by turtlemonvh** [comment]
Thanks for the tip on using the binary distribution to avoid this. That was very helpful.  

Installation instructions are here:
https://docs.docker.com/compose/install/
