### ISSUE TITLE
docker-py version mismatch on 1.2.0 release

### ISSUE THREAD

**Issue by munhitsu** [docker/compose#1460]
requirements.txt on 1.2.0 git tag:
```
docker-py==1.0.0
```

setup.py on 1.2.0 git tag:
```
'docker-py >= 1.0.0, < 1.2',
```

when installing using pip (version source is setup.py):
```
$ pip install docker-compose==1.2.0
$ pip freeze
docker-compose==1.2.0
docker-py==1.1.0
...
```

while binary build comes with `docker-py==1.0.0` bundled (version source is requirements*.txt)
(conclusion based on missing private registry authentication)

Can you cut a new docker-compose patch release to synchronize the binary and pip install?

Might be also worth to update the binary build script not to rely on requirements.txt but on `pip install .`

**Comment by aanand** [comment]
If I recall, this was deliberate so that Pip users could use a newer docker-py if they wanted to. We couldn't use a newer docker-py with the binary because of an incompatibility problem with pyinstaller, which has since been fixed for Compose 1.3.

The private registry authentication bug will be fixed in the Compose 1.3 binary, for which an RC will be dropping soon.

**Comment by munhitsu** [comment]
@aanand, thanks for update
my dev team is then eagerly looking forward to Compose 1.3 RC

**Comment by dnephin** [comment]
These issues have been fixed
