### ISSUE TITLE
Add support for 'z' option for volumes

### ISSUE THREAD

**Issue by samalba** [docker/compose#1493]
'z' option is currently not supported for volumes and volumes_from.

Here are the modes available in docker: https://github.com/docker/docker/blob/53d9609de472f2fc9e6aaef2b713f526605f4ab8/daemon/volumes.go#L115

**Comment by aanand** [comment]
Maybe we can get it in as part of https://github.com/docker/compose/pull/1420.

**Comment by vdemeester** [comment]
It's just gonna work with Docker 1.7.0 as it's a pretty recent change (https://github.com/docker/docker/commit/af7d17a6c906d348eb0929766a81fd04fc173c44), but depending how we handle that #1420 could support this as well (or a new one later).

**Comment by aanand** [comment]
Since we're past code freeze for Compose 1.3 anyway, I think it'd be OK to make #1420 dependent on Docker 1.7 - it'll land in Compose 1.4, giving people plenty of time to upgrade.

You can start using RC1 right now by changing the lines in the Dockerfile that download the Docker binary and set the "default" (only) version.

**Comment by vdemeester** [comment]
Ok good then, I'll update #1420 this evening :)
