### ISSUE TITLE
Relax restrictions on service names

### ISSUE THREAD

**Issue by aanand** [docker/compose#1519]
Now that we're not relying on a strict container name format, we should be able to allow more characters in service names, as has often been requested (see #799, #869, #941, #1300, #1384).

- Docker allows `[a-zA-Z0-9_.-]` ([daemon.go](https://github.com/docker/docker/blob/04c6f09fbdf60c7765cc4cb78883faaa9d971fa5/daemon/daemon.go#L56))

- Compose allows just `[a-zA-Z0-9]` ([service.py](https://github.com/docker/compose/blob/7d2a89427c59774a8cbf503a57cb9f3b0d47d1fe/compose/service.py#L49))

Any good reason we can't allow `_.-` now?

**Comment by thaJeztah** [comment]
:+1: I'll finally be able to build my 

`a_.--.__.--.__.--.__.--.__.--.__.--.__.--.__.--._` and `127.0.0.1` images :D

**Comment by aanand** [comment]
Also relevant: allowed characters in image tags, since those are also based on service name. Seems to be the same chars though ([tags.go](https://github.com/docker/docker/blob/04c6f09fbdf60c7765cc4cb78883faaa9d971fa5/graph/tags/tags.go)).

**Comment by erichonkanen** [comment]
+1

**Comment by zstarer** [comment]
+1 just ran into this after a long day. that's fun. container name: -_-

**Comment by broegner** [comment]
Is there anything new here? Will this change be part of the next RC or is it already baken into the current one?

**Comment by aanand** [comment]
1.3 is in code freeze, so this will not be in the next release.

**Comment by phazei** [comment]
Is there anything happening with support on this? 
In this comment https://github.com/docker/compose/issues/472#issuecomment-91252147 it's mentioned that there should be some support for this in 1.3.

I'm using 1.3 and it doesn't seem to be any different.  Will there be a 1.3.1 or will we need to wait till 1.4 till anything other than [a-z0-9] is allowed for reasons of service/container/host compatibility/bug?

**Comment by aanand** [comment]
This won't be in 1.3, or any 1.3.x release. 1.4 is the likely target.

**Comment by aanand** [comment]
Closed by #1624.

**Comment by TristanCP** [comment]
"Any good reason we can't allow _.- now?"

There is a good reason for "_", since service names are used as host names in URLs :  

"Note that while upper and lower case letters are allowed in domain
names, no significance is attached to the case.  That is, two names with
the same spelling but different case are to be treated as if identical.

The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less."

https://www.ietf.org/rfc/rfc1034.txt
https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

If your try to reach a tomcat served URL inside from a container to an other container (using his service name), tomcat will pop a  "java.lang.IllegalArgumentException: The character [_] is never valid in a domain name."

**Comment by held-m** [comment]
I waste a day because I'm using underscore in my docker-compose. But somebody uses RFC (RFS 822) for his product.
Lesson learned. Never use underscore in docker. Just letters, numbers and -

**Comment by luator** [comment]
I'm very confused by this now.  So far I had dashes (`-`) in my service names and everything was fine until today, where I struggled to base the image of one service on another (using `additional_contexts:\ base: "service:other-image"`).  By trial and error, I figured out that the dash was the issue because changing to underscores fixed it.  Now I'm reading here that I should not use underscores but only dashes...

I'll just avoid both for now to be safe but is there some authoritative documentation on how services should be named?  I didn't find anything so far.
