### ISSUE TITLE
Use pyOpenSSL instead of stlib ssl module

### ISSUE THREAD

**Issue by aanand** [docker/compose#1530]
So we can be more permissive about the Python version while preserving security and avoiding the bug described in #1484.

Blocking on https://github.com/pyca/cryptography/issues/2039.

**Comment by tdsmith** [comment]
I commented on #1484 but if pyca/cryptography is built against openssl 1.0.2, using pyOpenSSL doesn't appear to provide any benefit wrt the certificate validation error. It appears to work on many systems because pyOpenSSL is actually being built against the system openssl, which is from the 0.9.8 series, which is too early to manifest the incompatibility with the docker stack. Building against the system openssl will stop working on OS X 10.11 because Apple will stop shipping the openssl headers.

**Comment by shin-** [comment]
We were able to update to 1.0.2 and I haven't seen any new issue reports regarding openssl issues, so I think we can close this.
