### ISSUE TITLE
Random crashes "Unit already exists"

### ISSUE THREAD

**Issue by Yajo** [docker/compose#1555]
It's common for me to get these messages when stopping (not killing) and restarting containers with `--no-recreate`, but I cannot know what triggers those:

    Cannot start container ef50748801ad83e9fb9f013c08cb81b03a600ff636118c8e7f8cb648952b5455: [8] System error: Unit docker-ef50748801ad83e9fb9f013c08cb81b03a600ff636118c8e7f8cb648952b5455.scope already exists.

Usually running `up` without `--no-recreate` fixes that until some later occasion.

**Comment by Yajo** [comment]
This is happening more often since 1.4.0rc2, since the no-recreate is the default.

A workaround is to `docker-compose rm` those containers, but it's unpleasing. Any idea about why this happens?

**Comment by buluba89** [comment]
This problem started to me today also when i upgrade to 1.4.0.
I am using arch with :
Docker version 1.7.1, build 786b29d 
and
docker-compose version: 1.4.0

As  @Yajo  said using docker-compose rm or the --force-recreate fix this.

**Comment by dnephin** [comment]
Thanks for the bug report!

This error is coming from the docker daemon. There isn't much we can do about it from compose. I'd suggest searching for an issue on the docker/docker github.

https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+unit+%22scope+already+exists%22+is%3Aopen+

It looks like a few of these have already been closed, so maybe this is fixed in docker 1.8?

If not, please do open a new issue on the docker/docker github.
