### ISSUE TITLE
Watch code and automatically rebuild when something changes

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#184]
Compose could watch your code and automatically kick off builds when something changes. This would mean:
- Code can be reloaded automatically regardless of language. This would also make code reloading work on compiled languages if that was part of the build process!
- Volumes are no longer needed in development
- Production server can be used in development (e.g. gunicorn can be used to serve Django apps in development)

It could either be an option to `up` (`docker-compose up --watch`), an option in the config file specifying directories to watch/ignore, or perhaps a separate command (`docker-compose watch`).

Thanks to @samalba for the suggestion!

**Comment by txdavidtx** [comment]
It's been a few months, and I couldn't tell from the merge referenced above, was a "watch" ability integrated?

**Comment by aanand** [comment]
No, `fig watch` has not been implemented.

**Comment by aanand** [comment]
It's still on the table though - see [ROADMAP.md](https://github.com/docker/fig/blob/master/ROADMAP.md)

**Comment by bfirsh** [comment]
An idea from @fxdgear: instead of rebuilding, it could also be useful to just restart the container when the code changes. E.g. when you've mounted your code with a volume.

**Comment by aanand** [comment]
Now that we have a `--no-build` flag, perhaps the logic should be:

```
$ fig up                      # current behaviour
$ fig up --watch              # watch and rebuild + restart
$ fig up --watch --no-build   # watch and restart
```

That said, if we go down the #693 path, we'll have to revisit this.

**Comment by amjibaly** [comment]
:+1: 

For this to be really awesome, there's got to be a way for docker build to accept or pass through some type of credentials without storing it in the image. I'm thinking private github modules but it really applies to any environment.

**Comment by docteurklein** [comment]
what about the right tool for the right job ?

wouldn't `guard` fit perfectly here ?

``` ruby
guard :shell do
  watch(/Dockerfile$/) { `fig build` }
  watch(/fig.yml$/) { `fig up -d` }
end
```

**Comment by ches** [comment]
@amjibaly:

> For this to be really awesome, there's got to be a way for docker build to accept or pass through some type of credentials without storing it in the image. I'm thinking private github modules but it really applies to any environment.
> ...
> I run fig up --watch and the first time npm install runs because the package.json hasn't been cached yet. This needs to fetch private modules from github so it passes those through (maybe this is setup in my ~/.figconfig or something similar?)

This sounds out of scope for fig or `docker build` to me. Like in this example, if you're referencing private Git repos as NPM dependencies, you could use the `git@github.com:me/myrepo.git` style of remote and then Git would just defer to SSH for key authorization without NPM, `docker build`, or fig needing to know anything about it. Most SCMs work similarly with SSH, or at worst other underlying tools should likely check an environment variable or config file of their own. But maybe there's something else you had in mind that I'm not considering?

**Comment by amjibaly** [comment]
@ches I didn't realize `docker build` already supports this. I just gave it a shot and it doesn't seem to work, can you point me to the documentation? Here's the error I see:

```
npm ERR! git clone git@github.com:myorg/myproj.git Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-myorg-myproj-git-9e8969c5'...
npm ERR! git clone git@github.com:myorg/myproj.git error: cannot run ssh: No such file or directory
npm ERR! git clone git@github.com:myorg/myproj.git fatal: unable to fork
```

In `package.json` I have:

```
"dependencies": { "myproj": "git+ssh://git@github.com:myorg/myproj.git#master" }
```

**Comment by dnephin** [comment]
@amjibaly looks like you need to install ssh in your container

@docteurklein I tend to agree, there are existing tools which would handle this pretty easily (the python watchdog package includes a cli called `watchmedo` which would also work).

**Comment by amjibaly** [comment]
@dnephin I installed ssh, now I'm getting this error:

    Host key verification failed.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights and the repository exists.

Running `npm install` locally works of course.

**Comment by docteurklein** [comment]
@amjibaly you're totally off-topic, no?

**Comment by amjibaly** [comment]
@docteurklein yeah my bad. FYI @ches it turns out that `docker build` does not support forwarding ssh creds so my original point still stands: https://github.com/docker/docker/issues/6396

**Comment by psychowico** [comment]
wouldn't it be too slow to work with everyday programming process?

**Comment by Starefossen** [comment]
Not entirely sure if this should be something Docker Compose do! I for one have several other build steps other than just restarting the container/app including compiling, transpiring, concatenation etc. Restarting the app when your code changes should be handled by the developer tooling inside the container. I'd rather see better support for multiple Docker Compose environment configurations in order to better support a developer configuration which are different from a prod configuration.

**Comment by nathanleclaire** [comment]
I've actually done an implementation of a feature like this at one point (in figgo) and I'm -1 on `fig watch`.  Even with a tiny little app it's just slow enough to be annoying, I don't think I would use it.  It'd be easy enough to write a little program to wrap fig and incorporate this that I don't think we'd stand much to gain by supporting it.

**Comment by sebglon** [comment]
+1

**Comment by trsouz** [comment]
+1

**Comment by crsmithdev** [comment]
+1

**Comment by aboutvale** [comment]
+1

**Comment by ronthepanda** [comment]
I am really with @Starefossen. Same opinion here. (:

**Comment by nathanleclaire** [comment]
> I'd rather see better support for multiple Docker Compose environment configurations in order to better support a developer configuration which are different from a prod configuration to accommodate for restart on file-change.

Hm, I'm not sure if this would solve what you're after, but take note that you can specify alternative configuration files using the `-f` option for `docker-compose`.  I have one project where I have a `docker-compose.yml` and a `docker-compose-prod.yml`, for instance, to change the DB password and a few other things.

**Comment by nmunson** [comment]
@nathanleclaire I think the extends option added in 1.2.0 now supports that model even better.  For example, both the dev and production compose files are based off the same common file, but the dev compose file also mounts volumes and watches for code changes on the components.  

FWIW I'd agree with @Starefossen, I'm not sure that's something Compose itself should do but rather the containers themselves can watch for changes.

**Comment by jp-gouigoux** [comment]
-1. IMHO this would go against a clear separation of responsibility. If Compose is supposed to watch code change, it would then need to check unit test before deploying, then maybe add triggering, etc. Soon, it'll end up doing everything a CI tool does, and when one tries to do too much, generally it does not do it in the best way. In short, too much coupling ; we need easily pluggable atomic services.

**Comment by LongLiveCHIEF** [comment]
-1 agree with @jp-gouigoux

**Comment by dnephin** [comment]
> - Volumes are no longer needed in development
> - Production server can be used in development (e.g. gunicorn can be used to serve Django apps in development)

I don't think this feature would actually accomplish these two (of three) goals.  A build + restart is often way too slow for interactive development. Using a volume is still going to offer much better results.

Part of development is debugging with an interactive debugger, which isn't going to be possible running inside a production server, so there is still a need to run a different entrypoint to the app.

I'm still very much in favor of #693, which would make this feature difficult (maybe impossible as they are conflicting ideas).

I could see a feature where `watch` tailed the event stream (#1510) and when a new image event is triggered, run `docker-compose up -d` to recreate any containers that have new images.

Then a separate build tool could watch files and rebuild the image when an image has changed. The rebuild of an image would trigger the recreate of a container, but they would be separate from each other, so that any build system would be supported.

**Comment by docteurklein** [comment]
I just thought of a crazy hack to bypass the volume VS rebuild && up problem:

 - create a container to be used as a volume source (--volumes-from)
 - watch changes locally and `docker cp` the changed files to this volume container

And now I realize this hack justs does badly what volume-drivers resolve, IMHO.

**Comment by sp90** [comment]
Im no docker expert, but couldn't you mount your own drive and then run a normal gulp task for dev environments and then do something different for production envs ??

**Comment by pakastin** [comment]
Here's how I've done it: https://github.com/pakastin/docker-boilerplate

**Comment by ethan-hunt-007** [comment]
how to I implement the same feature in Marathon... ie while deploying the docker image how do I force marathon to pull the latest code changes in its docker deployement???

**Comment by razic** [comment]
@bfirsh Are you a maintainer on this project? Is this at the suggestion point, or at the "this is something we actually want" phase? I could possibly implement something built in to compose if that's the direction we want to take.

**Comment by FGRibreau** [comment]
[docker-compose watch (a-k-a docker-compose reload) one-liner](http://blog.fgribreau.com/2017/04/docker-compose-watch-k-docker-compose.html)

**Comment by pakastin** [comment]
Btw. PM2 can nowadays handle Docker and watch files like magic. I definitely would recommend to check it out:
http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

😉

**Comment by edward-of-clt** [comment]
I would argue against this consider docker swarm utilizes docker compose files as well. If you need that functionality, use volumes.

**Comment by raphaklaus** [comment]
@edward-of-clt I agree. But what if you want to ignore some folders? `.dockerignore` doesn't work for that. Also, I think making docker-compose volumes workarounds kinda ugly.

**Comment by eduardomoroni** [comment]
What about instead of rebuild docker we keep files in sync? I mean, if I change a file which is supposed to be inside Docker container, docker will have an updated version of this file.
I agree with folks saying that rebuilding is not a responsibility of Docker itself, you app should've have this responsibility. Docker will only keep files up to date.

(I'm newbie at Docker environment, IDK if this feature exists or not)

**Comment by pie6k** [comment]
@eduardomoroni - keeping in sync is easy for static files - eg some .html file has changed and you can sync it. In many cases, however, simple file change can totally change way how some service is working. Thats why, usually full restart of  such service is required. 

Anyway - **it've been 4 years**, since issue was created. Would be so cool to have it

**Comment by edward-of-clt** [comment]
This will more than likely not be done solely because it seems to be outside the scope of Docker Compose.

Your best bet would be to implement a service such as watchman, and have it build within the container. (https://facebook.github.io/watchman/) 

If worse comes to worse, quite frankly, you could have Docker built into your container and map `/var/run/docker.sock` and, if need be, force a service update `docker service update --force <service_id>`.

**Comment by eduardomoroni** [comment]
@pie6k Thanks for you suggestions, I achieved desired behaviour using a lib to rebuild files if anything changes (nodemon) and then using volume to identify if files was changed. 
https://github.com/project-australia/Sydney/blob/master/docker-compose.yml

**Comment by pie6k** [comment]
Yup, I know nodemon is great for that. But it works if you use node only.

**Comment by scottstensland** [comment]
I am using a webhook written in golang which listens to any `git push` to trigger my app rebuild / redeploy process ... https://github.com/adnanh/webhook  ... I have this running inside a container which rebuilds then does a docker-compose up  ... love seeing my webapp get code updates with zero devops manual intervention

**Comment by pie6k** [comment]
I'd say it's not stale

**Comment by ndeloof** [comment]
compose now offers option to run builds using the docker CLI builder, which can be configured to use BuildKit. As the later doesn't require to send the whole docker context to daemon before a build start, and offers advanced caching capabilities, it seems a good candidate so service images can be rebuilt on a regular basis.

**Comment by SuperSandro2000** [comment]
spam for stale bot

**Comment by tonymj76** [comment]
i followed this thread from 2014 now to 2020 to find a clue on how to auto build microservices  (Go) binary  in dev when a file is change. am getting tired of running two many terminal so am looking into docker to see how it can help my life

**Comment by Lukortech** [comment]
6 years into the request and I still cannot easily rebuild my docker without creating freaking volumes. 
What is this.

**Comment by facundopadilla** [comment]
> 6 años después de la solicitud y todavía no puedo reconstruir fácilmente mi ventana acoplable sin crear malditos volúmenes.
> Qué es esto.

2021 lol

**Comment by DarthGoon** [comment]
I found a way to do this, that I like.

I'm using `inotifywait` to watch the file system, and `nohup` to start the processes;  In a dev tooling "layer" in my linux docker container.

I put this in my Dockerfile-
```
# DEV TOOLING
RUN apt-get update && apt-get install -y inotify-tools
COPY code_reloader.sh /
RUN chmod +x /code_reloader.sh
ENTRYPOINT ["/code_reloader.sh"]
#############
```
  

This is `code_reloader.sh`-
```
#!/bin/bash
set -x

reload() {
  nohup python /opt/manage.py runserver 0.0.0.0:5000 > /nohup.out &
  DEV_SERVER_PID=$!
  PROCESS_RELOADING=0
}

reload

inotifywait -m -r -e modify /opt | while read CHANGE_EVENT;
do
  if [ $PROCESS_RELOADING -ne 1 ];
    then
      PROCESS_RELOADING=1
      echo "#### $CHANGE_EVENT DETECTED, Reloading PID:$DEV_SERVER_PID... ####"
      kill $DEV_SERVER_PID
      reload
    fi
done
```

The `nohup` command in `reload()` is what would be the ENTRYPOINT in the production container's Dockerfile.  I happen to be running a python service in this example.
BE SURE TO redirect the `nohup` output file if it's in the same directory as the one you're monitoring; or `nohup` writing to it's out file will trigger a reloading loop.  I'm redirecting it to `/` in this example.

With this setup-- I mount the code directory into `/opt` in the `docker-compose.yml`;  run `docker-compose up`; and just write code.  The service reloads with changes.

I like this approach because I don't have to modify code, or install framework specific packages/CLI tools, to be able to live reload.

**Comment by fiq** [comment]
A watch and rebuild would be a really handy feature. As per the previous comment, a common work around is mounting one's app over the immutable version you have baked into your image. I see this often and it defeats the intent of containerisation + introduces false confidence as the running image is not representative of a particular build.

**Comment by ndeloof** [comment]
This would be an interesting feature, in the meantime could rely on dedicated solutions like https://containrrr.dev/watchtower/

**Comment by Mahoney** [comment]
Started playing with a wrapper script to add `--watch` here:
https://github.com/Mahoney/docker-compose-watch/blob/main/docker-compose

Immediate weaknesses:
* It just uses pwd rather than parsing the yaml to decide which contexts to use
* It’s pretty inefficient because it doesn’t know about .dockerignore - so a change to an ignored file results in the entire context being calculated and sent to the docker daemon, before docker then decides there’s nothing to do.

**Comment by patientplatypus6** [comment]
I'm surprised this is still not a feature. ndeloof is working on this for Docker v2, but this should be in v3 itself as well. 
Here's the problem that I'm currently facing.
I'm developing an application using docker-compose v3.9 on mac - which means that I can't use inotif-tools, but have to use fswatch. Which is a bit frustrating, because if I eventually want to port this over to a linux container that means that I'll have to then switch to inotify-tools. 
OK fine, minor issue.
*However*
Watching for file changes means that I spawn a new process - so if I `docker-compose up` and `<watch for file changes>` in the same bash file then a new process is spawned, meaning I can't restart the container in a process that doesn't have the container running! So, that leaves me with the option of writing entrypoint scripts for each of the containers - but look at this example 

This is the entrypoint.sh file for a backend Django/Python application - 

```
#!/bin/bash

echo "inside entrypoint"
echo "deleting prior static images directory"
rm -rf ./static_images
echo "makemigrations"
python3 manage.py makemigrations
python3 manage.py makemigrations lightone
echo "migrate"
python3 manage.py migrate
python3 manage.py migrate lightone

echo "manage.py createsuperuser"
python3 manage.py createsuperuser \
  --noinput \
  --username pixel \
  --email peterweyand0@gmail.com
# --database lightchan

echo "now running the server"
daphne -b 0.0.0.0 -p 8000 lightchan.asgi:application
echo "now running the server"
```

The container itself is alpine linux so I could use a file watch like inotify-tools. The issue now is that inotify-tools is blocking! So how do I simultaneously run Daphne while watching for file changes? Maybe I could run Daphne as a background process using a trailing &, but again, does that mean that Daphne will pick up file changes if inotify-tools kills the  container and then the script restarts?

This is a major major issue. Will somebody fix this?

**Comment by ndeloof** [comment]
> ndeloof is working on this for Docker v2, but this should be in v3 itself as well.
There's a (common) confusion here between the file format (which is now obsolete with Compose Specification) and the tool version. "Docker Compose v2" is `docker compose` command developed on this repository as `v2` branch. 

I expected inotify was working as expected under Docker Desktop, will need to change. A potential implementation of  `watch` command for application stacks which support reloading could be for `docker compose watch` command to send a `SIGHUP` signal.

**Comment by AradAlvand** [comment]
No updates on this after 8 years?!

**Comment by Lukortech** [comment]
Sadly, no. 
I've given up on docker desktop for now.

**Comment by ydennisy** [comment]
@ndeloof any news on your PR?

**Comment by nbx0** [comment]
+1!

**Comment by ndeloof** [comment]
The experimental `watch` command has been released, closing this issue now

**Comment by ramnes** [comment]
Here is more context for those wondering:
* https://github.com/docker/compose/pull/10163
* https://github.com/docker/compose/pull/10170
* https://github.com/docker/compose/pull/10218
* https://github.com/docker/compose/pull/10249
* https://github.com/docker/compose/issues/10270
* https://github.com/docker/compose/pull/10311
