### ISSUE TITLE
Can't run on MAC

### ISSUE THREAD

**Issue by oleynikd** [docker/compose#1848]
Hi, I read almost all  I could find, but I still can't get it to work.
I'm getting errors when trying to `docker-compose up`

If I'm:
```
pip install -U docker-compose==1.4.0rc3
docker-compose up
```
I get:
`SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

If I'm:
```
curl -L https://github.com/docker/compose/releases/download/1.4.0rc3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker-compose up
```
I get:
`Illegal instruction: 4`

Please HELP!

**Comment by aanand** [comment]
You're getting the first error because of a certificate generation issue with boot2docker. You have two options:

- Wait for boot2docker 1.8, which will fix the bug
- Use [Docker Machine](http://docs.docker.com/machine/) instead, which doesn't exhibit the bug

The second error is because your Mac has an older CPU architecture that's incompatible with the Compose binary.

**Comment by oleynikd** [comment]
Thank you!!!
