### ISSUE TITLE
Environment Variables in volumes trigger named volume warning

### ISSUE THREAD

**Issue by karlkfi** [docker/compose#1867]
Warning added in #1833 is triggered by volumes starting with environment variables (e.g. `${VOLUME_DIR}:/var/stuff`).

How would we know whether the env-var was a name or a path? 

Is there a way to wait to test for `.~/` until after env-vars are evaluated?

**Comment by aanand** [comment]
This is partly a bug, and partly a side-effect of how variable substitution has been implemented in the past for volume paths.

First of all, Compose *is* substituting variables before checking the host path. That's not the issue. However, two things are currently wrong:

1. The error message prints out the input string, rather than the evaluated string. That's an easy one to fix - I'll do that now.

2. The method we use to substitute variables - `os.path.expandvars` - performs no expansion if a variable is unset, meaning the final value will still be `${VOLUME_PATH}:/var/stuff`. This is obviously (to me) a bug. The good news is that it's already fixed in master, as a result of the new universal variable substitution code merged in #1765.

**Comment by karlkfi** [comment]
Thanks @aanand!
