### ISSUE TITLE
log_driver: none causes " Failed to get logging factory: logger: no log driver named 'none' is registered" message

### ISSUE THREAD

**Issue by lxe** [docker/compose#1947]
I'm using docker and docker-compose from homebrew (with boot2docker/docker-machine):

```
$ docker -v
Docker version 1.8.1, build d12ea79
```

```
$ docker-compose --version
docker-compose version: 1.4.0
```

The docker daemon version is:

```
$ boot2docker ssh docker -v 
Docker version 1.8.0, build 0d03096
```

I'm specifying my `log_driver` in the `docker-compose.yml` file as per https://docs.docker.com/compose/yml/#log-driver, and setting it to `none`:

`docker-compose.yml`:
```
helloworld:
  image: busybox
  command: echo "Hello World!"
  log_driver: none
```

I'm getting the following error when I 'docker-compose up`:

```
~/dockercompose-test ❯❯❯ docker-compose up
Starting dockercomposetest_helloworld_1...
Attaching to dockercomposetest_helloworld_1
helloworld_1 | taching: Failed to get logging factory: logger: no log driver named 'none' is registered
dockercomposetest_helloworld_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

The weird thing is this worked in lower versions of docker-compose and docker.

**Comment by mnowster** [comment]
Thanks for reporting this @lxe , I did some work on the log_driver options, so I'm going to try and take a look at it this week.

**Comment by terbooter** [comment]
``
log_driver: "syslog"
``
``
log_driver: "none"
``
Rises an error
`
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 59, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.utils", line 100, in split_buffer
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 221, in _multiplexed_response_stream_helper
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.packages.urllib3.response", line 218, in read
  File "/code/build/docker-compose/out00-PYZ.pyz/httplib", line 573, in read
  File "/code/build/docker-compose/out00-PYZ.pyz/socket", line 380, in read
MemoryError
`

**Comment by aanand** [comment]
@terbooter That looks unrelated - `MemoryError` is raised when the program has run out of memory. Do you have plenty of memory free?

**Comment by mnowster** [comment]
Ok, I've done some investigating and think this might be somewhere in docker daemon and not compose or docker-py. Compose and docker-py are sending "none" up to the daemon. There is code within docker daemon to handle when we do this, to signify we don't want any logging, here:

https://github.com/docker/docker/blob/v1.8.1/daemon/container.go#L747

But we're now not getting to there, because it goes through this factory registry and "none" is not registered as a log driver factory bean.

https://github.com/docker/docker/blob/v1.8.1/daemon/logger/factory.go#L83

This needs picking up by someone who knows Go better than me. Pinging @aanand @dnephin @shin- to the how do you even Go phone :phone: :floppy_disk:

**Comment by dnephin** [comment]
So the issue here is that if you try to attach to a container with `logs=1` and the container doesn't use the json log driver, then it gives you an error.

Basically any non-json log driver is incompatible with `docker-compose up` (with `-d` is ok) and `docker-compose logs`.

I think all we can do here is: document this limitation (it's actually on the docker api side), and improve the error message on the compose side.
