### ISSUE TITLE
doing a run with a 'restart: always' service causes the run to repeat infinitely

### ISSUE THREAD

**Issue by programmerq** [docker/compose#1985]
This was outlined in https://github.com/docker/compose/issues/1013, but that ended up only fixing the issue when doing a run with the `--rm` flag.

**Comment by aleedom** [comment]
A description of the bug can be found here: https://forums.docker.com/t/script-is-being-called-once-and-being-run-multiple-times/3250.  

how to reproduce this bug: 
1. clone this repo https://github.com/aleedom/Docker-Testing

2. Run the following commands from the root of that repo.


docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker-compose build
docker-compose up -d
docker-compose run web /usr/local/bin/python create_db.py
#View app (0.0.0.0) here to verify that no posts are in the database
docker-compose run web /usr/local/bin/python test.py
#view app (0.0.0.0) here to verify that multiple posts have been created instead of one

I'm still testing the interaction with repeated refreshing vs re-navigating to the page to see if there are additional symptoms.

**Comment by dnephin** [comment]
I think this is actually the correct behaviour for `always`. Docker has added `unless-stopped` , and there is always `on-failure[:max-retries]` for other retry strategies.
