### ISSUE TITLE
fd protocol Implementation

### ISSUE THREAD

**Issue by Glideh** [docker/compose#1998]
As I was saying in #88, for a fresh install with the curl script (at least in Debian 8), docker seems to be configured to listen on `fd://` by default

```
ExecStart=/usr/bin/docker daemon -H fd://
```

However, when `DOCKER_HOST` is set to use `fd://`, `docker-compose` (1.4.0) complains:

> fd protocol is not implemented

_Maybe this issue is more linked to the docker client_

**Comment by dnephin** [comment]
Yes, I think the support needs to be added to `docker-py`

**Comment by thaJeztah** [comment]
ping @shin- to check if this is already being worked on :-)

**Comment by shin-** [comment]
Not being worked on to my knowledge. [Explicitly unsupported](https://github.com/docker/docker-py/blob/7dce129180cb0ee88bc4bce7d36aa76332ebb36f/docker/utils/utils.py#L304-L305), but if someone wants to write a requests adapter for the fd protocol...

What system / version of docker are you using where `fd` is the default protocol?

**Comment by thaJeztah** [comment]
@shin- it's the default [SystemD service](https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service) now used in docker, so this will be used by any system that uses SystemD

**Comment by shin-** [comment]
Hm, but connecting to the socket at `/var/run/docker.sock` should still work, right?

**Comment by Glideh** [comment]
Sure, it's just a installation issue with the default behavior

Le mer. 9 sept. 2015 01:10, Joffrey F <notifications@github.com> a écrit :

> Hm, but connecting to the socket at /var/run/docker.sock should still
> work, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/compose/issues/1998#issuecomment-138727939>.
>
-- 
Pierre de LESPINAY

**Comment by dnephin** [comment]
Is `fd://` just an alias for `file://` or is there something else involved?  Could we handle it by just stripping the `fd:/` ?

**Comment by Glideh** [comment]
It seems more like a [dedicated socket for systemd](http://0pointer.de/blog/projects/socket-activation.html) with it's own protocol

**Comment by Burt-Silverman** [comment]
We found it was necessary to follow the instructions https://docs.docker.com/install/linux/linux-postinstall/ for Manage Docker as a non-root user near the top. Then everything takes care of itself and you don't have to worry about the details of fd://.

**Comment by ijc** [comment]
I think there's a small amount of confusion around what this issue means and what was going on in #88 (which is pretty ancient history).

If you launch `docker` (the daemon) with `fd://` then the systemd socket activation protocol is used and systemd will create `/var/run/docker.sock` and pass it (as an `fd`) to the daemon. However clients (like `docker-compose`) should/must still use `/var/run/docker.sock` (or whatever systemd was told to open) to talk to the daemon. It would a mistake/incorrect to try and use `fd://` as `$DOCKER_HOST` when invoking `docker-compose` (IOW the usual (?) convention that client and server may specify the same thing to talk to each other I think breaksdown for the socket activation case).

So passing `fd://` to the daemon is conceptually a separate thing to passing `fd://` to `docker-compose`, TBH I'm not 100% clear what it means to use systemd socket activation for a _client_ connection (my understanding of it is all around the listening/daemon side). I guess it would mean something like: you are launching a `docker-compose up` as a systemd service/unit and you want it to speak to the daemon on a client fd which systemd already opened on `/var/run/docker.sock` for you (I've no idea if the socket activation stuff can actually do client side things like that though). However, my ignorance about socket activation notwithstanding it still doesn't make sense to use `fd://` when you are invoking `docker-compose from the CLI yourself, unless you are somehow simulating systemd socket activation...

I think the perms on the socket (most recent comment) are orthogonal to that.

From my reading of the issue and of #88 I think this issue was down to a mistaken attempt to use `fd://` as `$DOCKER_HOST` when invoking `docker-compose` because the daemon was given `fd://`. As I explain above I don't think that makes conceptual sense so I am going to close this issue now.

If someone has a usecase for managing a systemd `my-compose-based-thing.service`  and can explain (or reference) how systemd socket activation works for _client_ uses like that then I think a fresh issue is the way to go.
