### ISSUE TITLE
docker-compose pull doesn't work with mixure of official and local images

### ISSUE THREAD

**Issue by villlem** [docker/compose#2028]
I use my own image build process in my development environment. This process create images localy so I can test them. I also use mose official images (databases) in my `docker-compose.yml`. With this combination `docker-compose pull` command fail when its tries to pull my local only images and if I'm not lucky no database images are pulled.

I would like to from time to time pull new images from repository and so far I have to list them all. Is it possible to pass some flag to `pull`  that it tries to pull all images and only report those that failed (instead of stop pulling others)?

**Comment by dnephin** [comment]
I've run into this issue myself, and I think it's pretty common. It would be good to fix it. The workaround I've used is to list the services you want to pull instead of pulling all of them.

A flag do `docker-compose pull --skip-missing` might be good, to allow any failed pulls to be skipped. I'm not sure if we want to change the default behaviour.

**Comment by villlem** [comment]
I've create implementation that skips all pull errors. Name of the flag is up to discussion but I've rolled with @dnephin 's `--skip-missing`
