### ISSUE TITLE
Add command to list project status

### ISSUE THREAD

**Issue by ghost** [docker/compose#2057]
With release 1.4.0 I have found no way to use `docker-compose` command to check if project is up and running (correct me if I'm wrong).

The closest is `docker-compose ps` whose output lacks information about stopped/not created containers. I guess it could be used for status querying with issue #1061 impemented, but we would still need to parse textual output to determine project status.

A `docker-compose status` that checks if project is up and running and returns proper zero/non-zero exit code would be very usefull for scripting `docker-compose` and integrating it with other tools.

**Comment by dnephin** [comment]
The problem with using container status as a healthcheck is that it's not a good measure of the health of a service.  The container may be running, but there are lots of possible (and likely) scenarios where your application in the container is not running correctly (ex: it could be listening on the wrong port (or otherwise misconfiguration). It could be spewing errors to a log and not actually doing any work.)

If you need the health of a service, it really needs to query the application itself.

There's been some discussion about how healthchecks should work in other issues, but I don't think that checking container status is sufficient.

I think #1061 is still important to implement, but I'm not sure if a `status` subcommand is the right approach.

**Comment by zdenekc** [comment]
Let me start from back. I too think that #1061 is important and should not be rolled up into this issue. I mentioned it only because I would be able to use it to work around my issue.

You say that I need query application to check for service health and I agree with you completely. The `status` subcommand as I proposed it is not sufficient for it. But my intention was not to check application health, only if it is running or not.

Think LSB init scripts and their `status` command. It does not know about service health either, but it is very uncomplicated mechanism that allows rudimentatry monitoring and automation (start if stopped). The `docker-compose` lacks even this rudimentary ability now.

What I've tried to do was implement simple LSB init script that would start and stop `docker-compose` project. But how do I check if all projects containers are running? The only way I found is `docker ps` and knowing which containers should run. And thats pretty hard to automate.

Status with proper health checks would be nice, but simple LSB init script like `status` seem like good, inexpensive start.

**Comment by nvllsvm** [comment]
I've been using some shell to check if any containers with health checks are not "healthy". If anyone one health check is not "healthy", the command exits with a code of 1.

```
FORMAT='{{ if .State.Health }}{{ if ne .State.Health.Status "healthy"}}1{{ end }}{{ end }}'
exit $(docker inspect -f "$FORMAT" $(docker-compose ps -q "$@") | sort -n | tail -n 1)
```

It's clearly not a pretty solution to my problem so having this in Docker Compose (or per-container in Docker CLI) would be useful. The biggest unknown is what the API would like.
