### ISSUE TITLE
Host unreachable after up --no-deps

### ISSUE THREAD

**Issue by flash1293** [docker/compose#2063]
I have some services running defined by a docker-compose.yml via `docker-compose up -d`. When I try to restart a service with a new image by calling `docker-compose up --no-deps -d SERVICENAME`, the service restarts as expected, but after that I can't reach it in linked containers, I get an EHOSTUNREACH error. I have to restart all services to re-establish the connection. How can I fix this?

**Comment by flash1293** [comment]
Additional information: Basically, I am trying to do this: https://docs.docker.com/compose/production/#deploying-changes

But as I said, after the redeployment the links to this container are broken. 

Debian 7.9
Docker version 1.8.2, build 0a8c2e3
docker-compose version: 1.4.1

**Comment by dnephin** [comment]
`--no-deps` has been known to cause a couple issues like this because it ignores all the dependencies, so compose doesn't know to recreate them when necessary.

This should be fixed in 1.6.0 (RC1 was just released) with docker 1.10. Links are being backed by a DNS instead of /etc/hosts, so they should be recreated automatically.

**Comment by flash1293** [comment]
Cool, thanks. I will try it out and report back.

Daniel Nephin <notifications@github.com> schrieb am Di., 19. Jan. 2016
01:11:
