### ISSUE TITLE
`command: true` gives `json: cannot unmarshal bool into Go value of type string`

### ISSUE THREAD

**Issue by amitsaha** [docker/compose#2121]
Consider the compose file:

```
web:
   image: fedora
   command: true
```

Now:

```
# docker-compose up
Creating root_web_1...
json: cannot unmarshal bool into Go value of type string
```

I am not sure if this is an issue with ``jsonschema`` or in the compose code itself? If I can get any helpful pointer, I can try to fix it. Thanks.

**Comment by dnephin** [comment]
The problem is that this yaml is not what you think it is.  `command: true` is parsed as `command: <bool>`, but a boolean is not a valid string, and command must be a string.  What you want is `command: "true"`.

We've fixed this validation in master, it will now give a much better error message about what is going on.

**Comment by amitsaha** [comment]
Thanks @dnephin I did try "true" before filing this issue and as you say, it worked. Good to know there is a better error message coming up.
