### ISSUE TITLE
Variable substitution default value support 

### ISSUE THREAD

**Issue by andrerom** [docker/compose#2178]
With several [extends](https://github.com/dnephin/compose/blob/release_notes_1.5.0/CHANGELOG.md#150-2015-10-13) and [substitution](https://github.com/docker/compose/blob/master/docs/yml.md#variable-substitution) needs coming into place now for 1.5.0, only thing missing from my POV is being able to set default values ala extended shell :tada:

**Comment by hadim** [comment]
Same here ! Any milestone ETA ?

**Comment by hadim** [comment]
Would you be interested by a PR ?

**Comment by dnephin** [comment]
One thing we've considered is to have the file for #745 support arbitrary environment variables, since all the thing we'd like to persist can be set from environment variables. That would allow for a place to set defaults for these config variables as well.

The other option is to expand the syntax to support some way to provide defaults inline. 

I think it needs more discussion before we start to implement anything.

**Comment by hadim** [comment]
Ok, thank you. Hope you'll take a decision soon. Variables substitutions are boring without default value :-)

**Comment by roll** [comment]
:+1:

**Comment by andrerom** [comment]
@hadim: missed the comments above, personally interested in PR of course, but you should hear with guys like @dnephin and other active commiters/maintainers on how to approach it.

@dnephin what I'm requesting here is inline defaults, basically ala ${var-default} where default should be limited to scalars for possible security implications, implementation complexity and portability.

Reason is that I see this mainly as a tool for people providing ready made compose files for others to use and get up and running easily, so it must be defined upfront and not something persisted and reused after first compose up run.

**Comment by dnephin** [comment]
We've got a few duplicate issues about default values. Going to close this issue for #2441
