### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by analytically** [docker/compose#219]
Ubuntu 14.04 defaults to Python 3.4 be default, so let's make fig compatible.

- Use https://github.com/bufordtaylor/python-texttable instead of texttable
- Upgrade websocket-client to v0.14 (will be released on May 15)
- Upgrade PyYAML to 3.11
- In fig's source, change

```
except StreamOutputError, e:
```
to
```
except StreamOutputError as e:
```

- Add '3.4' to .travis.yml

I'll submit a pull request when websocket-client 0.14 is released.

**Comment by dnephin** [comment]
#440 is in master!  the next release should support python 3

**Comment by franklinyu** [comment]
The [Fedora package](https://apps.fedoraproject.org/packages/docker-compose) still depends on Python 2, which should be unnecessary since the [Arch Linux package](https://www.archlinux.org/packages/?name=docker-compose) depends only on Python 3 packages. Is the maintainer of the Fedora package also in this repo? Or I need to submit bug report there?
