### ISSUE TITLE
Container autoreload in case of crash

### ISSUE THREAD

**Issue by marinho** [docker/compose#220]
It would be helpful to have an entry in fig.yml file to determine a container that should load again instead of just stop all services and finishing the whole set.

We could solve that by setting fig to start and be managed by Supervisor but that is not a good idea, in case we have many running containers to wait for all of them to stop and then to start the "fig up" again.

**Comment by dnephin** [comment]
With [restart](http://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mem-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only) and `docker-compose up -d` this has been working for a while.

In the next release it will work with `docker-compose up` as well (because up wont exit as soon as the first container stops).
