### ISSUE TITLE
Forrest etcd new features / integration in docker compose

### ISSUE THREAD

**Issue by Ozzyboshi** [docker/compose#2219]
In my opinion it would be great to enable docker-compose to send some container information to an etcd store like forrest does (https://github.com/avgp/forrest).

This is a docker-compose.yml example file:
web:
  build: ./webapp
  etcd-hosts:
    - 10.0.0.1
    - 10.0.0.2

In this case when docker-compose creates and run new containers, they must register the container name, ip and ports in the  etcd store at  10.0.0.1 and  10.0.0.2.
When the containers are destroyed or stopped, docker-compose must erase their entry in the etcd store.
I this way, with the help of confd I can instruct my haproxy (by a manual configuration file reload) where the web containers are located within my swarm cluster and achieve a quite automated balancing process.

Maybe there are other useful situations where the etcd registrations come in handy.

I don't know if this is the right place to ask, maybe this feature should be built within docker itself.

What do you think?

**Comment by dnephin** [comment]
I think the approach taken by forrest is wrong. There's no reason to couple the creation of containers to registration.  It's better to use `docker events` to do the registration.  The advantage to using `docker events` is that you don't have to implement the registration in every client. So instead of `docker-compose` and docker-cli having to communicate with etcd, you have a single service that tails the events and registers everything that is created.

http://jasonwilder.com/blog/2014/07/15/docker-service-discovery/ is a good example of what you want, and includes the registration step.

**Comment by Ozzyboshi** [comment]
thank you for the hint @dnephin I think you are right.
I don't even think that tying compose to a particular product like etcd is a good idea.
Closing issue for now.
