### ISSUE TITLE
Bundle update is not working

### ISSUE THREAD

**Issue by dronov** [docker/compose#222]
Hi. I'm trying to use fig with docker at Ruby on Rails development. I've made all instructions from [tutorial](http://orchardup.github.io/fig/rails.html) and everything goes well. But when I need to add new gems to Gemfile the command 'fig run web bundle update' after that is not working. Rebuilding the container is not working too. Bundle has ran well but it didn't make any changes and rails project is not working.

What have I done wrong?

**Comment by timdorr** [comment]
Sorry for dredging up an old issue, but I believe I have a solution for this. By all means, poke plenty of holes in this, as I'm new to the Dockerverse.

So, can this not simply be solved through the use of image versions? The act essentially as another caching layer. For my project called `gandalf`, here's what I have in my Dockerfile:
```dockerfile
FROM ruby:2.1.5-slim

RUN apt-get update && apt-get install -y \
        autoconf \
        build-essential \
        git \
        imagemagick \
        libpq-dev \
        libxml2-dev \
        libxslt-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install

ADD . /app
```

Nothing too crazy. The `Gemfile` and `Gemfile.lock` additions work as a cache for the `bundle install` step. So, if they haven't changed since the last time you ran `fig build`, they will pull from cache.

Now if I want to run `bundle update`, I can do that with `fig run web bundle update`. That does it's thing and leaves an image intact. I can see it with `docker ps -a`:
```sh
⚡  ~/Projects/gandalf (⭠ dockerize)$ docker ps -a
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS                       PORTS               NAMES
f1c84d921858        gandalf_web:latest            "bundle update"        3 hours ago         Exited (0) 24 seconds ago                        gandalf_web_run_1
90f530cd58a6        gandalf_web:latest            "foreman start"        4 hours ago         Exited (137) 7 minutes ago                       gandalf_web_1
``` 

Now this is where the magic happens: I can cache that `bundle update` with `docker commit` and the run container that was just created:
```sh
⚡  ~/Projects/gandalf (⭠ dockerize)$ docker commit -m "updated gems" f1c84d921858 gandalf_web
0bbf1ea8a2456722ec130e4c24458c9455fb1c1247e6073845c7ccb102a0dfd5
```

This will update the `gandalf_web:latest` image tag to what was in that container. Since fig uses the `latest` tag to recreate containers, it will use that version when `up`-ing. I confirmed this by printing out some version strings during the boot of my Rails app and it showed the correct version.

And if I want to bust the cache and rebuild from scratch, `fig build` will cause docker to note the changed `Gemfile.lock` and bust the cache of that `ADD` and the `bundle install` step. And in the case of bundler (I don't know about npm, pip, or other equivalent systems), it keeps the previous gem versions around, so switching between branches or reverting your `Gemfile.lock` shouldn't require a `fig build`. 

Does that jive with how I should be using images in docker and how fig operates? It seems to, but perhaps I missed something obvious.

**Comment by RotemEmergi** [comment]
Hello,

How can I install the bundle on the docker compose  ?

I want to run : docker-compose bundle .

And I will get the  example. dsb 

I am working on docker 1.12

**Comment by aanand** [comment]
@RotemEmergi This issue is about the Ruby `bundle` tool, not distributed application bundles. Please open a separate issue for your problem. Thanks!
