### ISSUE TITLE
Incorrect network name showed with --x-networking

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2345]
Started an application using https://github.com/arun-gupta/docker-images/blob/master/wildfly-mysql-javaee7/docker-compose.yml as:

```console
docker-compose --x-networking up -d
Creating network "wildflymysqljavaee7" with driver "None"
Creating wildflymysqljavaee7_mywildfly_1
Creating db
```

The message shows network is created with driver "None" but listing the network as `docker network ls` shows otherwise:

```console
> docker network ls
NETWORK ID          NAME                  DRIVER
a3c9994d6134        none                  null                
91537bec6510        host                  host                
b1770955e5aa        wildflymysqljavaee7   bridge              
6fda61934fbe        bridge                bridge  
```

**Comment by dnephin** [comment]
The log message needs to check if there is no driver specified, and say "default" instead of "None"

**Comment by nicolaka** [comment]
@aanand @dnephin why is it that compose still creates an overlay network and names it $PROJECT_NAME even if all the services in docker-compose.yml file explicitly use a `net:` parameter that uses an existing overlay network ? 

Is this behavior handing with this issue?

**Comment by aanand** [comment]
We probably shouldn't create the default network if nothing is going to use it, yeah.

**Comment by dnephin** [comment]
Ya, that should have already been fixed in #2341 (#2275) which was part of 1.5.1.

**Comment by dbonev** [comment]
Sorry, if it's a stupid question, but is the expected behaviour here to just output "default" (literally) instead of "None"?
I.e. in this particular case, what is the expected output:
1) Creating network "wildflymysqljavaee7" with driver "default"
2) Creating network "wildflymysqljavaee7" with driver "bridge"
or maybe:
3) Creating network "wildflymysqljavaee7" with the default driver

Again, sorry if that's obvious -- I'm a newbie in compose.

Thanks

**Comment by aanand** [comment]
Correct. (3) would be my preference.

**Comment by dbonev** [comment]
#dibs
