### ISSUE TITLE
[Enhancement] Docker-Compose directive for added delay or wait time between container launches.

### ISSUE THREAD

**Issue by chamunks** [docker/compose#2440]
Some applications require that other applications are already booted and readily available in order to launch correctly.  [For example](https://github.com/benhutchins/docker-taiga/issues/6#issuecomment-158562872) was only able to launch if the postgres container was already fully available.   

My suggestion is to have some method to add a delay between containers launching if need be.  I have no clear suggestion as to how you would accomplish this but it would be really helpful.

**Comment by dnephin** [comment]
There's a lengthy discussion about this in #374.  I believe this issue is a duplicate.

For now, the problem can be solved by the application, either by implementing an entrypoint script which waits for the dependency to be ready, or by having the application retry the operation until the dependency is ready.
