### ISSUE TITLE
Infinite recursion bug?

### ISSUE THREAD

**Issue by spinus** [docker/compose#2541]
https://github.com/docker/compose/blob/master/compose/project.py#L111
Looks like infinite recursion.

**Comment by dbonev** [comment]
No because the recursive call is made using the ```self.service_names``` property (https://github.com/docker/compose/blob/master/compose/project.py#L72) instead of the originally passed ```service_names``` parameter.
The initial validation (https://github.com/docker/compose/blob/master/compose/config/validation.py#L77) ensures that there will be at least one service, so ```project.service_names``` is guaranteed to be non-empty.

**Comment by spinus** [comment]
Is the python API way to go with docker-compose as well? Or only CLI?

I started using docker-compose from python, created manually "Project" and that happened. Do I make it in a wrong way?

**Comment by dbonev** [comment]
Ah, now I understand.

My guess then would be that, since you're instantiating and using Project       directly, it is not properly initialized, ```self.services``` is not set (and   thus -- ```self.service_names``` would be empty and you end up with infinite    recursion).

I'm very new to compose myself, so take my opinion for what it's worth, but I   don't think it was ever intended to be used in the way you're trying to. Using  the CLI from your python script would be the way to go IMHO, especially for a   real-life project. 

If, on the other hand you simply want to play around, test (and break) things   and see how stuff works, in this case you should do something similar to what   https://github.com/docker/compose/blob/master/compose/cli/command.py#L82 does   to properly instantiate a Project.

Again, I might be missing something quite significant myself, so don't take it  for granted.

**Comment by spinus** [comment]
I instantiate project with exactly the same method as in the link (``from_dicts`` method), I just passed empty service list. Of course I will use some services and the problem will go away, it just hit me when I started playing around. If there are any "length" checks for services I think they are in wrong place.

Anyway, just wanted to report. If you think this ticket is invalid, please close.

**Comment by dnephin** [comment]
Since this doesn't manifest as a bug from the cli I think we can close the issue. But if you want to submit a PR to fix it, we might be able to accept it.
