### ISSUE TITLE
up command should allow the allocation of a pseudo-TTY during container creation

### ISSUE THREAD

**Issue by kuhnroyal** [docker/compose#2610]
`docker-compose up` should have a flag and preferably also a config file option to allocate a pseudo tty during the container creation. The run command already allows for this.

**Comment by dnephin** [comment]
The config option already exists (`tty`) https://docs.docker.com/compose/compose-file/#cpu-shares-cpuset-domainname-entrypoint-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-stdin-open-tty-user-working-dir

It doesn't make sense to make it a flag on `up`, because it would apply to every service. We don't want to duplicate every run option on up, that's what the config is for.

**Comment by kuhnroyal** [comment]
I looked all through the reference but missed that somehow...

**Comment by dnephin** [comment]
It might be good to split all those options out into their own section, it can be easy to miss.
