### ISSUE TITLE
docker-compose running in a container

### ISSUE THREAD

**Issue by hourliert** [docker/compose#2630]
Hi,

I have an issue when:
* running docker-compose in the official container (Installed with this command ```curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose```)
* using a private a registry with authentication (so when this file is created in ~/.docker/config.json)

It seems my home directory is not mounted at the right place in the docker-compose container.

If I change [this line](https://github.com/docker/compose/blob/2f8cb554126f05bc5a4965a10c69dc500d2d1131/script/run.sh#L43) by this line : `VOLUMES="$VOLUMES -v $HOME:/root"` it works.

I could do a pull request if requested.

**Comment by dnephin** [comment]
Ah, so that volume is being mounted for other volumes, not for the docker config. I think we should mount an additional volume for the config (not change that one).

I think that line should be `VOLUMES="$VOLUMES -v $HOME:$HOME -v $HOME:/root", with a comment about why there are two.

A PR would be great, thanks!
