### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by asmoker** [docker/compose#2738]
After I installed docker  completely, then I tried to install `docker-compose` followed by the docs [Install Docker Compose](https://docs.docker.com/compose/install/), after that when I run the command `docker-compose` ,  error:

```
docker@ubuntu:~$ docker-compose
Segmentation fault (core dumped)
```

My ubuntu's version info:

```
docker@ubuntu:~$ uname -a
Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I also tried on th CentOS 7 with the same error.
Any suggestions are appreciated.

---

I tried to use `sudo pip install docker-compose` and fixed.

**Comment by sillyousu** [comment]
Can you provide the core file?

**Comment by zmpandzmp** [comment]
Hi, 
thanks for your reply.

Because of the problem of network, 

1. I download the docker-compose file from [github](https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Linux-x86_64) to localhost; 
2. I upload the docker-compose file(docker-compose-Linux-x86_64) to my server(ubuntu 14.04) via scp; 
3. I move the file to /usr/local/bin/ and rename to docker-compose; 
4. `chmod +x /user/local/bin/docker-compose`;

Then I run the command `docker-compose`, the result was : Segmentation fault (core dumped);

Thanks .

**Comment by gmarquet** [comment]
Same problem from differents install strategies (curl, ftp, pip)

```
root@docker:/home/ubuntu# uname -a
Linux docker 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
root@docker:/# docker --version
Docker version 1.13.0, build 49bf474
```
```
root@docker:/# docker-compose --version
Segmentation fault
```

**Comment by ramesh-code** [comment]
If you are doing docker-compose up and have the above error first restart your docker
sudo service docker restart

i have waste lot of time

**Comment by Polar-Tang** [comment]
Maybe any docker-compose old version is causing conflict, so
cd /
find -name docker-compose 2>/dev/null
so remove the old ones with `rm -r <filePath>` and only leaving "./usr/local/bin/docker-compose" installed
