### ISSUE TITLE
Update getting started guides to use Compose file version 2

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2825]
The list of guides is:
* https://github.com/docker/compose/blob/master/docs/gettingstarted.md
* https://github.com/docker/compose/blob/master/docs/django.md
* https://github.com/docker/compose/blob/master/docs/rails.md
* https://github.com/docker/compose/blob/master/docs/wordpress.md

**Comment by 13josh** [comment]
Please include more details around networking as well.  The default examples are sparse, particularly in the area of multiple networks.  

In general, the compose networking solution doesn't work for me since it prefixes the network with the compose directory.  The connectivity works fine, but if i try to access something at "container.network.name" where container is the name or hostname of the container and "network.name" is the network name, then it fails because the container exists at "container.appname_network.name".

I want to use the fullname for SSL, but hardcoding the directory name into the script seems wrong.  This gets more complicated where I want to join containers to multiple networks and specify different hostnames (or at least aliases per network (DNS entries?)).

I tried just configuring the networks external (which seems reasonable given my requests) but I couldn't get the container to join multiple networks.  

I assume all of this is possible, but I spent literally hours scanning the docs yesterday and experimenting and couldn't get it to work for my single host with multiple bridge networks.  I've since reverted back to v1 compose file format and am just joining a single network via the "net:" entry which seems to work just fine (especially now that docker 1.10 supports DNS).

Would love to see better documentation (complete with real-world example compose files) around networking as this is a new great thing in the Docker ecosystem and deserves to have more than a few short paragraphs.

**Comment by dnephin** [comment]
I just want to make sure you're aware of https://docs.docker.com/compose/networking/, which is our networking guide.

> I tried just configuring the networks external (which seems reasonable given my requests) but I couldn't get the container to join multiple networks.

If you have a reproducible case, please open a new issue and we can definitely look into that.
