### ISSUE TITLE
QoL Request: Highlight breaking changes in release notes

### ISSUE THREAD

**Issue by thieman** [docker/compose#2852]
There are multiple breaking changes in the [1.6.0 release](https://github.com/docker/compose/releases/tag/1.6.0), specifically the three bullets under `New Features` which begin with the word `Removed`. Discovering these breaking changes currently requires a careful read over the entire changelog, since Compose neither uses semantic versioning nor groups breaking changes under a `Breaking Changes` headline to make them obvious. Additionally, the placement of a breaking change under `New Features` is unintuitive.

It would be much more friendly to users if breaking changes were grouped together in a `Breaking Changes` headline in the future so that anyone parsing the changelog can easily identify them.

**Comment by dnephin** [comment]
Normally we do put the breaking changes section first (see https://github.com/docker/compose/releases/tag/1.5.0, https://github.com/docker/compose/releases/tag/1.3.0).

In this case we were only removing features that had been deprecated for many releases already, and produced a warning when you tried to use them. Since they had already been warning for a while I didn't seem as critical to call it out at the top. Apologies if this caused you any problems.

Was there one in particular that you were still using?

**Comment by thieman** [comment]
We were using `--allow-insecure-ssl`, which was obviously a bit of an anti-pattern to begin with. The fix is trivial and this hasn't placed that much of a burden on us, I just thought it suboptimal that I needed to read through the whole changelog to figure out why my project was broken with 1.6. Good to know that what I'm asking for is usually standard practice, thanks for responding.
