### ISSUE TITLE
Service instance unaware of its externally resolvable hostname

### ISSUE THREAD

**Issue by davidcurrie** [docker/compose#2862]
This is a variant of https://github.com/docker/compose/issues/2551 which has now been closed because it is possible for a container to ping itself using its container name based hostname. The issue I have is that the container itself still doesn't know what that name is!

I have a product where, on startup, process B is required to register itself with process A and then, at some point later, process A is going to call back to process B. By default, process B registers with its local hostname but its smart enough to know that this is not always going to be resolvable by A so the hostname that it should register with can be overriden on startup.

Given the decision that containers should be allocated hostnames on the overlay network based on container name rather than hostname (the rationale for which I've not found in writing anywhere) in the non-Compose scenario I have the following options:
* Set the hostname and container name to be the same
* Set the container name and pass that as a variable on container startup so that process B knows to register with this instead

Neither of these options is available with Compose if I want to be able to scale the number of instances of process B. Just making the container name available inside the container would be one option (https://github.com/docker/compose/issues/1503) but there are also other possibilities. Providing an option to have compose set the hostname to be the container name being another one. 

My preference would be to have a variable available for use in the yml that represents the generated container name for a service instance. You then have choice whether to set the hostname e.g.

```yml
processB:
 hostname: ${CONTAINER_NAME}
```

or pass it through to the container:

```yml
processB:
 environment:
  - MY_VAR=${CONTAINER_NAME}
```

**Comment by dnephin** [comment]
The way I've done this (and seen other do it), is to use the short container id. It's available from inside the container by using `$(hostname)` (don't set a custom hostname), and it's discoverable from other containers on the network at that name.

Note: #2845 is an issue with 1.6.0 that will be fixed in 1.6.1. For now you can get it to work by removing the last two characters that you get from `$(hostname)` so that it uses a 10 character short id.

**Comment by brunoborges** [comment]
This issue may be better explained by the folllowing tests.

```
bruno@lenovo: compose-net$ cat docker-compose.yml 
version: '2'
services:
  slave:
    image: busybox
    command: top
    networks:
      - mynet
    depends_on:
      - master 
  master:
    image: busybox 
    command: top
    container_name: master 
    hostname: master
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
```

Then I execute the Compose above as daemon:

```
bruno@lenovo: compose-net$ docker-compose up -d
```

This is the state of these containers:

```
bruno@lenovo: compose-net$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
0f734f3eca10        busybox             "top"               2 seconds ago       Up 2 seconds                            composenet_slave_1
9c8c035f9290        busybox             "top"               3 seconds ago       Up 2 seconds                            master
```

And these are the tests:

```
bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 master
PING master (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.052 ms

--- master ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.052/0.052/0.052 ms

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 composenet_slave_1
PING composenet_slave_1 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.066 ms

--- composenet_slave_1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.066/0.066/0.066 ms

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 0f734f3eca10
ping: bad address '0f734f3eca10'

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 9c8c035f9290
ping: bad address '9c8c035f9290'
bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 master
PING master (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.049 ms

--- master ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.049/0.049/0.049 ms

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 composenet_slave_1
PING composenet_slave_1 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.021 ms

--- composenet_slave_1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.021/0.021/0.021 ms

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 9c8c035f9290
ping: bad address '9c8c035f9290'

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 0f734f3eca10
PING 0f734f3eca10 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.047 ms

--- 0f734f3eca10 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.047/0.047/0.047 ms
```

As you can see above, these are the scenarios that fail:

 1. pinging 0f734f3eca10 from 9c8c035f9290 fails
 2. pinging 9c8c035f9290 from 0f734f3eca10 fails
 3. pinging 9c8c035f9290 from 9c8c035f9290 fails

I understand that [2] and [3] above perhaps should indeed fail since that container has a specific hostname `master`. But [1] should not happen, and that is what should be fixed.

**Comment by davidcurrie** [comment]
Thanks @dnephin - I'm good with that. Indeed, that's what I hoped for originally. I just fell foul of #2845.

**Comment by alexch** [comment]
This ticket [and others](https://github.com/docker/compose/issues/2845) are talking about connecting using the container id, not the name. 

But in https://docs.docker.com/compose/networking/ it says, "by default, any service can reach any other service at that service’s name". Is this no longer true? Where are the most up-to-date docs?

(name would be most convenient since then I wouldn't have to keep rewriting the various services' config files to point to the new hash id whenever i tweak `docker-compose.yml`)

**Comment by alexch** [comment]
Replying to my own comment... It seems that "any service can reach any other service at that service’s name" is true, whether or not the other service's name is listed in the `links` section for the service in question. 

My problem was that they have to be on the same network; I was confused since specifying `network-mode: bridge` adds you to a bridge network named `bridge` but *omitting* `network-mode` adds you to a bridge network that is *not* named `bridge` (it's `appname_default` for me).
