### ISSUE TITLE
'fig logs' exits when a service is stopped

### ISSUE THREAD

**Issue by stefanfoulis** [docker/compose#289]
I usually have a console open that just shows the output of ``fig logs``. In a other console I use ``fig start ...`` and ``fig stop ...`` and other commands to alter the environment.

Every time a service is stopped, the ``logs`` command also exists.

**Comment by imton** [comment]
any update? it's kind of annoying :(

**Comment by thaJeztah** [comment]
For reference, the link in Aanands comment no longer works because the repository was moved to "docker" and the rebranding to "compose"; this one should work; https://github.com/docker/fig/blob/master/compose/cli/log_printer.py#L56-L58 (not sure if the line numbers are correct). This will change again soon once the repository is renamed to "compose" :)

**Comment by aanand** [comment]
This was fixed in #1754, and will land in 1.5.
