### ISSUE TITLE
underscores being removed in a project name

### ISSUE THREAD

**Issue by lruslan** [docker/compose#2923]
It would be good to allow usage of the underscores in a project names. Compose allows usage of underscores in a container names, but in case of a project name underscores being silently removed. 
`docker-compose -p api_backend up -d` with service name  "service_a" will result in a container with name "apibackend_service_a_1" and labels:
```
"com.docker.compose.project": "apibackend",
"com.docker.compose.service": "service_a",
```
Looks like undocumented feature.
https://github.com/docker/compose/blob/89c5b800e64dba79f287b20932df9e3b70e561b0/compose/cli/command.py#L92 

Is there particular need to remove underscores in a project name?  Having direct mapping of project name to internal docker compose naming would help us to do less non transparent name transformations when automating compose based deployments.

In any case it would be useful to have documentation describing naming conventions and transformations.

**Comment by aanand** [comment]
It used to be necessary to remove underscores so that container names had a predictable structure (`project_service_number`), because before Engine implemented container labels, we were using names to keep track of everything.

However, we can't easily change that logic without breaking backwards compatibility: imagine having an environment running, upgrading Compose, running `docker-compose up` and getting a bunch of new containers called `api_backend_*` alongside your existing `apibackend_*` ones.

If we're going to change the logic of what characters are dropped from the directory name, we'll need to carefully figure out a migration and deprecation strategy.

**Comment by dnephin** [comment]
#2119 covers this issue, let's bring the discussion there.
