### ISSUE TITLE
Compose doesn't respect ports with run

### ISSUE THREAD

**Issue by FrenchBen** [docker/compose#2946]
## Issue
`docker-compose run` doesn't respect the port mapping 

## Expected
`docker-compose up` and `docker-compose run` should behave similarly, except you only run 1 service instead of the entire stack.

## Steps to reproduce
Create a `docker-compose.yaml` file a `test` folder:
```
redis:
  image: redis
  ports:
    - "6379:6379"
```

Getting the container up and running with `docker-compose up` will create the proper container and will have the ports mapped (as expected)
```
$ docker port test_redis_1
6379/tcp -> 0.0.0.0:6739
```

Running the same file via `docker-compose run redis` will create a container without the ports mapped.
```
$ docker port test_redis_run_1
(empty)
```

**Comment by nathanleclaire** [comment]
@FrenchBen Not doing port mapping during `run` is intentional.  You can turn it on with `docker-compose run --service-ports`.  The reasoning for this historically is that if you want to do something like `docker-compose run app rake db:migrate` multiple times, the created containers will conflict with one another if ports are forwarded to the host.

**Comment by FrenchBen** [comment]
Makes sense  and I should've read the docs: 
https://docs.docker.com/compose/reference/run/
