### ISSUE TITLE
HostConfig on /start ?

### ISSUE THREAD

**Issue by vieux** [docker/compose#2952]
We currently have a bug in swarm + compose.
It's going to be fixed in swarm but in the meantime I'm wondering why compose is sending the host config on container start.

It has been deprecated a year ago, it should only be send on create now.

**Comment by dnephin** [comment]
We don't send HostConfig on `start`, you can see that here: https://github.com/docker/compose/blob/master/compose/service.py#L427-L430

You can see it being passed to `create`: https://github.com/docker/compose/blob/master/compose/service.py#L255-L265, and https://github.com/docker/compose/blob/master/compose/service.py#L622-L626

We've been sending it on create since it was deprecated (1.4.x I think).

**Comment by vieux** [comment]
@dnephin can you try with 1.1.1 ?
1.1.1 includes https://github.com/docker/swarm/pull/1829 and it look like the definition we use for hostconfig it's outdated.

This test https://github.com/vieux/swarm/commit/d49db6afaf126b96d7590ced45c16c14a32e57fd is currently not working with 1.1.1 

and it working again if we revert https://github.com/docker/swarm/pull/1829 that's why I think compose is doing something weird with hostconfig.
