### ISSUE TITLE
How will name conflict in network be resolved?

### ISSUE THREAD

**Issue by cgcgbcbc** [docker/compose#2984]
For example, if a projcet_A_network has a service name app, and project_B_network also as ha service name app, and B's app join A's network in additional to B's network, then app in A's network will be resolved to which container??

**Comment by dnephin** [comment]
Undefined. You will get one of the containers. You can use links or alises (coming in 1.6.1) to address this issue and name them differently.

**Comment by dextervip** [comment]
@dnephin, any good approach today?

**Comment by RozbehSharahi** [comment]
I am not an expert on this, but still hope this helps.

I see 3 possibilities, which I already tried all:

1) Rename your services to be more unique (ok obvious)
2) Use aliases in order to make this work

the 3) one is the solution I currently took on my project. I am still not sure, if this will turn out well, as it is a very fresh implementation, which works though.

Imagine Project A and Project B are running both on your computer/host. Let's say you they are webservers and serve on port 80 inside but you exposed them on individual ports 8001 and 8002, as they would otherwise conflict on your host.

This means you would have access from host via localhost:8001 and localhost:8002.

On you docker-compose.yml you can then define something like this on your services

```
extra_hosts:
  - some.domain.for.service:host-gatway
```

From inside you should then be able to do `curl some.domain.for.service:8001`

Maybe this helps <3
