### ISSUE TITLE
Using extends and multiple compose files (-f) result in stacking of paths which do not exist.

### ISSUE THREAD

**Issue by fxdgear** [docker/compose#3219]
When using multiple compose files, and in those files there's a "common" service which gets extended. It causes issues where paths get stacked and can not be found: 

for example see this:
https://github.com/fxdgear/composebug

**Comment by dnephin** [comment]
I believe the issue here is that any file that is listed in `extends` is expected to be a fully valid Compose file. So the the `servicea` in `services/servicea/docker-compose.yml` is being used in two different ways. Once as a base for `extends` and again as an override to `servicea`. 

The rules for how these two things work are different, and incompatible. For extends it's expected to be a fully valid service relative to the file path, for an override it's expected to be a fragment, relative to be the base files path.

I don't know if we can actually change this, because both of these are by design. Is it possible to use only override or extends, and not both together?
