### ISSUE TITLE
Scale counts wrong

### ISSUE THREAD

**Issue by jayfk** [docker/compose#3273]
The `scale` command begins to count at whatever value the last running container has at `com.docker.compose.container-number` when starting new containers.

Imagine the following: `foo` is scaled to 2, but `foo_1` is stopped and removed. When scaling up, compose starts to create and run `foo_3` instead of `foo_1`.

---
To reproduce:
```
version: "2"

services:
  foo:
    image: busybox
    command: sleep 300
```
```
docker-compose scale foo=2              
Creating and starting 1 ... done
Creating and starting 2 ... done
```
```
docker-compose ps  
     Name          Command    State   Ports
-------------------------------------------
increment_foo_1   sleep 300   Up
increment_foo_2   sleep 300   Up
```
```
docker stop increment_foo_1  
increment_foo_1
```
```
docker-compose ps               
     Name          Command    State    Ports
--------------------------------------------
increment_foo_1   sleep 300   Exit 0
increment_foo_2   sleep 300   Up
```

```
docker-compose rm -f    
Going to remove increment_foo_1
Removing increment_foo_1 ... done
```

```
docker-compose scale foo=2  
Creating and starting 3 ... done
```

```
docker-compose ps 
     Name          Command    State   Ports
-------------------------------------------
increment_foo_2   sleep 300   Up
increment_foo_3   sleep 300   Up
```

**Comment by dnephin** [comment]
This is by design. There shouldn't be any documentation that says numbers should always start at 1. These numbers are really just to give the container a unique name.

We'd actually like to remove the sequential numbers (#1516), so I don't think we're going to be doing any work to have the numbers "fill in the gaps". This would make Compose even more prone to race conditions and would be additional API calls with no real benefit.

**Comment by jayfk** [comment]
All right, that's great news!
