### ISSUE TITLE
1.7.0-rc1 has an inconsistent version number

### ISSUE THREAD

**Issue by dominics** [docker/compose#3300]
`1.7.0-rc1` is called different things in different places
- Download URL: `1.7.0-rc1`
- `docker-compose -v`: `1.7.0rc1` (NB: no dash, doesn't match download URL)
- `docker-compose version`: `1.7.0rc1` (same as `-v`)

I'm happy enough for the version specifier to not have a dash, but if we're going to do that can we at least make the download URL also not have one?

As it is, having these inconsistent version numbers makes it awkward to ensure the correct version of docker-compose is installed in configuration management; you have to somehow map the version number you'll get from `docker-compose version` to the download URL, or vice versa.

**Comment by aanand** [comment]
I agree, this distinction is annoying. It stems from two external influences:

- Docker Engine RCs, which contain dashes (e.g. `1.11.0-rc3`)
- [PEP 0440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers), which specifies a strict syntax for Python software version numbers (which matters because, as well as publishing compiled binaries, we publish to PyPi).

It's impossible to be consistent with both. If we were to go with one, my vote would be for consistency with the rest of the Docker projects.
