### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon

### ISSUE THREAD

**Issue by psychok7** [docker/compose#3341]
Hi, I am using Ubuntu 14.04 and i have been getting this error sometimes `ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.` since i upgraded compose to version `1.7.0` . 

I have no idea why but since i am not using docker-machine (only compose).

when i run `docker-machine ls` i get but i am using directly my ubuntu host for compose:

```
NAME   ACTIVE   DRIVER       STATE   URL   SWARM   DOCKER    ERRORS
yyy   -        virtualbox   Error                 Unknown   machine does not exist

```

Should i just remove docker-machine vm since i don't use it? Can't they coexist?

I reported in docker machine github but they told me to come here https://github.com/docker/machine/issues/3324

**Comment by dnephin** [comment]
The error may be misleading you. If `docker-compose` finds the `docker-machine` binary then it will use this error message as the "Connection Error" message, because it assumes that you are running Engine using `docker-machine`.

You do not need to uninstall `docker-machine`, just treat that error message as a generic "Couldn't connect to Docker socket" error message.

If you have any env vars set (`env | grep DOCKER_`) I would try unsettling them. That might cause a connection error if they're inconsistent.

Does `docker version` work ?

**Comment by psychok7** [comment]
@dnephin I don't have any env vars set with `env | grep DOCKER_` and i did add my user to the docker group..

docker version shows:
```
docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

```

Truth is since i removed my unused vm in docker-machine i haven't seen this error.

**Comment by psychok7** [comment]
@dnephin i am still getting this issue so i am going to try to downgrade compose to 1.6.2 and if it still happens will do the same with docker since i didn't have this issue before i upraded

**Comment by lang100** [comment]
@psychok7 i am facing the same issue,
did you solve it?

**Comment by psychok7** [comment]
@lang100 i don't remember but i think i reinstalled compose from `pip3` instead of `pip` and never had this problem again.
