### ISSUE TITLE
Include service name when printing an error message

### ISSUE THREAD

**Issue by TomasTomecek** [docker/compose#3355]
We've been happily using docker compose for a couple of months in our project (~9 service, moderately complex setup). From time to time, usually when a new team member tries to set up the development environment, there's an issue with bringing up the environment. When this happens, all we get is some cryptic error message:
 * `No such file or directory`
 * `Container command not found or does not exist.`

At this point, we usually have to dig into the person's machine and check what's wrong. We usually have to: check container logs, check images, inspect containers, try to start them manually using `docker` directly. From time to time, we even have to check docker logs, start stuff with `strace`...

It would be so much better if compose printed way more information when an error occurs: service name, engine API call, all arguments... Ideally, engine would do the same by sending more detailed error messages.

**Comment by dnephin** [comment]
I think we're pretty good about printing the service name when the error comes locally from Compose (like config validation).

These errors look like they are coming from the engine. I think it used to be that it was more obvious which service caused the error because we started them all sequentially, so the problematic service would be the same listed immediately before the error message ("creating and starting ...").

However now that we start things in parallel that probably doesn't work anymore. We could wrap these errors to provide more detail about the source.

**Comment by TomasTomecek** [comment]
That's exactly what I had in mind. I've opened https://github.com/docker/compose/pull/3364 to address this.
