### ISSUE TITLE
Quick start with Marathon on Windows - Docker Quickstart Terminal

### ISSUE THREAD

**Issue by fabrii** [docker/compose#3386]
I dont know if this is the proper place for posting this. I apologize if it isn't.

When running:

![win](https://cloud.githubusercontent.com/assets/18692157/14840759/8d8d9a3a-0c0d-11e6-852c-a5561b5bc401.jpg)

i get the following error:
C:\Program Files\Docker Toolbox\docker.exe Error parsing reference "Files/Docker" is not a valid repository/tag.

What am i doing wrong?

Btw, Kitematic isnt supported right?.
Thanks.

**Comment by dmc2015** [comment]
@fabrii is this still an issue for you?
It is probably a better idea to copy and past the string you are actually typing instead of an image so people don't have to re-type it.

I would try running it one line at a time and seeing when that error pops up. Also looking at the script it looks line it was built for an OS other than windows, but the error looks like you are running it on a windows system which is probably some how related.

Support/Issues for Kitematic is here
https://github.com/docker/kitematic
