### ISSUE TITLE
Question: running Gradle-based functional tests against linked containers

### ISSUE THREAD

**Issue by formerlyKurt** [docker/compose#3389]
I started up a few services using Compose on my Mac and they *appear* to be running just fine.  The services are, a Spring Boot application that is linked to a mock application, ActiveMQ, Mongo.  I have been able to verify that the Spring Boot app connects to both the database and the activemq containers.  For some reason though, when I run functional tests against the app container, it cannot connect to the mock application.

Here's a summary of how the apps connect and the error messages I am seeing:

        poc_service:
              build:
                context: .
                dockerfile: Dockerfile
              links:
                        - activemq:amq
                        - mock:mock
                        - mongodb:mongodb
              environment:
                        - ws.url=http://mock:38080/services/MyService

So I am telling gradle to hit the poc_service and in fact do see that connection established.  However, the poc_service is unable to reach the mock.

      poc_service_1   | ID: 1
      poc_service_1   | Address: http://mock:38080/services/MyService
      poc_service_1   | Encoding: UTF-8
      poc_service_1   | Http-Method: POST
      poc_service_1   | Content-Type: text/xml
      poc_service_1   | Headers: {Accept=[*/*], SOAPAction=[""]}
      poc_service_1   | Payload: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body>...</soap:Body></soap:Envelope>

And the error is:

      poc_service_1   | org.apache.cxf.interceptor.Fault: Could not send Message.
      poc_service_1   | 	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64) ~[cxf-core-3.1.5.jar!/:3.1.5]
      ...
      poc_service_1   | Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '404: Not Found' when communicating with http://mock:38080/services/MyService
      poc_service_1   | 	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1600) ~[cxf-rt-transports-http-3.1.5.jar!/:3.1.5]
      
Any thoughts on why this is not connecting or how to debug this further?

**Comment by dataethos** [comment]
I'm driving container integration tests with Gradle + Spock.  A few possibilities come to mind that I had issues with when doing this:

1. Your `mock` service isn't exposing `38080`, which you would need to do in order to have visibility from your `gradle test` running on your host machine (I presume) to your `mock` container.  Something like the following would correct this:
```yaml
services:
  mock:
    ...
    ports:
      - 38080:38080
    ...
```
2. You have a race condition between the application inside your `mock` container and when your test code runs. `(Container is running) != (Application inside the container is running)`  You may possibly need to write some retry logic around your SOAP call. In my case, `gradle integrationTest` does a `docker-compose up -d`, followed by running my Spock test cases, then `docker-compose down`. I wrote a simple exponential back-off method, and called the REST API as a Groovy closure.

**Comment by formerlyKurt** [comment]
Thanks for the info @dataethos! The issue was a misconfigured connection string -- Mock wasn't really connecting to ActiveMQ. Not immediately visible. Once, the connection string was fixed, I was able to run Gradle against the app. Nice!! Thanks. :-)
