### ISSUE TITLE
compose up --no-build Build Path Does Not Exist

### ISSUE THREAD

**Issue by dsanders11** [docker/compose#3391]
Currently if you do a `docker-compose up --no-build` for a `docker-compose.yml` file that looks like:

```
version: '2'

services:
  foo:
    build: "foo"
    image: foo:latest
```

And you're in an environment where the build folder doesn't exist, you'll get:

````
ERROR: build path /foo either does not exist, is not accessible, or is not a valid URL.
````

Creating an empty directory with that name allows things to continue as expected.

I'd like to have a single `docker-compose.yml` file that can be used for building on the developer side and deploying on the production side. As such I never want to build in production and only use the prebuilt images, hence the '--no-build' flag. The behavior of reading the build option in this case is unexpected and counter intuitive.

It looks like this is part of the validating the config logic, which is understandable, but it would be nice if no build was plumbed down so that a missing build path was not an error.

**Comment by metal3d** [comment]
Having image and build directive is an error I guess. Isn't it ?

**Comment by metal3d** [comment]
I precise:

This meand "please, build Dockerfile found in "./foo" directory"
```
build: foo
```
And this means "please use "foo" image, pull it if you don't find it":

```
image: foo:latest
```

So docker-compose doesn't know if it should pull "foo" image (or use the local one), or to build Dockerfile found in "./foo" directory. And more: because the "./foo" directory does'nt exists, docker-compose complain to not find the directory that you give to find your Dockerfile.

**Comment by metal3d** [comment]
You received 2 messages from me for some comments: sorry ! I didn't read your message as I should and I didn't understand what you meant. Now I understand :) and you're absolutly right !

**Comment by dnephin** [comment]
This is covered by #1973, closing as duplicate.
