### ISSUE TITLE
depends_on restarts dependent services when up is called

### ISSUE THREAD

**Issue by robert-bo-davis** [docker/compose#3397]
I bring up two containers called master and slave where slave depends_on master.  I destroy master.  I then run `docker-compose up` and both slave and master are recreated even though nothing has changed about slave. 

```
/ $ docker-compose -v
docker-compose version 1.7.0, build 0d7bf73
/ $ docker -v
Docker version 1.11.1, build 5604cbe
```

**Comment by shin-** [comment]
I believe that's intentional. Is this an issue for your application? What's your use case?

cc @aanand

**Comment by mujiburger** [comment]
I asked about it on IRC and was told it might be a bug, so I put in an issue.  My breaking case is a depends_on tree of a redis master -> redis slave -> redis sentinel.   Sentinel and redis slave really don't like to come up after the master.  The restart is a problem because it means potential unnecessary data loss and cache rebuilds.  A consul cluster is another example.  If you bring up a master to start up the cluster, start order is important, but you don't want to restart the entire cluster if the node with the master goes down and you bring the master up somewhere else.
<img width="1360" alt="screen shot 2016-05-02 at 7 29 43 pm" src="https://cloud.githubusercontent.com/assets/7569921/14971030/4a6e02c4-109c-11e6-9663-b5e911fc6ee0.png">

**Comment by aanand** [comment]
I think @dnephin is right: that behaviour was originally implemented for `links`, back when links were the only way to enable reachability between containers, and a link was bound to a specific container. If you recreated an upstream dependency (thus destroying the old container), it was necessary to recreate all downstream containers as well to preserve reachability.

So I think we can definitely change this behaviour for `depends_on`, and arguably for `links` in V2 files as well (since `links` now merely defines hostname aliases, which aren't bound to a specific container).

As for whether or not to treat it as a bug, I'm not sure. For `depends_on`, I feel the case for treating it as a bug is stronger. For `links`, it's possible there are people expecting/depending on the old behaviour, even under V2, and there should perhaps be a "deprecation warning" phase first.

**Comment by sanmai-NL** [comment]
From a user standpoint, I say just drop that legacy behavior.

**Comment by KevinTHU** [comment]
Is there a conclusion for this issue? We have the same problem as @robert-bo-davis .
