### ISSUE TITLE
docker-compose run doesn't use container_name

### ISSUE THREAD

**Issue by nicolaka** [docker/compose#3455]
When I use docker-compose run, it seems that container_name paramter doesn't get used. Is this by design or a bug?

```
# cat docker-compose.yml
version: "2"

services:
  ubuntu:
    image: ubuntu
    command: /bin/bash
    container_name: c1
```

```
# docker-compose up -d
Creating network "docker_default" with the default driver
Creating c1
# docker-compose down
Removing c1 ... done
Removing network docker_default
# docker-compose run ubuntu
Creating network "docker_default" with the default driver
root@8cefeea1924b:/# exit
exit
```

**Comment by vdemeester** [comment]
Hey @nicolaka, 

I'll let @dnephin or @aanand answer but I'm probably sure it's by design. `run` creates a new container for a "one-time" thingy and thus, it should probably not be created with the `container_name` with the risk of naming conflicts.

**Comment by mattbriancon** [comment]
Would it be possible to have it use the name of the container when using the `--service-ports` option? The ports are already going to conflict if two containers are running.

We're using 
```yaml
external_links:
  - my_api
``` 
but when I try to
```
docker-compose run --service-ports --rm my_api bash
```
in order to run `my_api` in a more debuggable way, I'm unable to receive any requests because the "run" container doesn't have the correct name.

**Comment by athenayao** [comment]
@mattbriancon 

Just ran into this myself. If you run with the `--name` parameter, that just works. e.g.,

 docker-compose run --service-ports --rm --name my_api my_api bash
