### ISSUE TITLE
Compose + Swarm + Port Mapping error

### ISSUE THREAD

**Issue by yank1** [docker/compose#3469]
Compose + Swarm + Port Mapping error

Environment: One node swarm.
## Step 1

```
redis: 
  image: daocloud.io/redis:3
  ports: 
    - "6378:6379"
  restart: unless-stopped 
```

`docker-compose up`

everythink ok.
## Step 2

```
redis: 
  image: daocloud.io/redis:2
  ports: 
    - "6378:6379"
  restart: unless-stopped 
```

`docker-compose up`

Error Message.

```
2016-05-17 17:00:04   Recreating 01a75d7735a8_redis_redis_1
2016-05-17 17:00:04  
2016-05-17 17:00:04   ERROR: for redis  Unable to find a node that satisfies the following conditions 
2016-05-17 17:00:04   [port 6378 (Bridge mode)]
2016-05-17 17:00:04
```

I know it's due to [swarm issue](https://github.com/docker/swarm/issues/1205) but the compose+swarm cannot work in the upgrade image case.

**Comment by jicki** [comment]
me too  !!

**Comment by yank1** [comment]
Hi @aanand, Is it a swarm issue or a compose issue, how would we fix it?

**Comment by aanand** [comment]
It's both, and it's an unfortunate result of how Swarm and Compose work today. There's some background in the ["Host ports and recreating containers"](https://docs.docker.com/compose/swarm/#host-ports-and-recreating-containers) section of the Compose/Swarm guide.

As the guide lays out, it's happening because you have an anonymous volume in your redis container (probably the redis data directory). You currently have two options:

- Let the containers be recreated elsewhere, by mounting a named volume and using a volume driver which supports relocation of containers.
- Destroy the old containers with `docker-compose rm` before creating the new ones.

**Comment by yank1** [comment]
Thank you

**Comment by niieani** [comment]
Here's a copy of my description of the associated duplicate issue (https://github.com/docker/compose/issues/3420); it has to do with affinity and here it is for completeness:

I have a service that has affinity set so that it can only be created on a specific node in the swarm.
That same service binds to a port on that node, meaning the service shouldn't scale to more than 1 container (by design).

An error appears however when `docker-compose up -d` tries to recreate the container, when the underlying image has changed. It checks for whether the conditions are met BEFORE stopping the previous container. Because the port is still in use by the old version of the same container, it spits out an error:

```shell
Recreating driver-singleton

ERROR: for driver-singleton  Unable to find a node that satisfies the following conditions
[port 443 (Bridge mode) port 80 (Bridge mode)]
[container!=*driver* (soft=false)]
```

docker-compose should ignore the container(s) it's about to recreate when deciding on which nodes to put the containers. Or even simpler, when it's recreating the container(s) it shouldn't even "think" about the nodes, just do it in place.

The workaround is to first manually stop and remove the service and then run `up -d` again.

**Comment by emmetog** [comment]
If you are using node constraints (eg `constraint:node==node-1`) and you run into this and everything else seems correct: double check that your node constraint hostname matches the hostname in your swarm key/value store (for example the `hostname` parameter you pass to consul). The error message is very similar in these two cases:
* no node was found by name to satisfy the node constraint
* a node was found but a port conflicts

**Comment by jmkgreen** [comment]
We' just hit this (or similar) on a four-node cluster with Docker 1.11.2, Swarm 1.2.3 and Compose 1.7.1.

In our case `up -d` failed to start an `haproxy` instance:

```
Recreating merge_haproxy_1
ERROR: for haproxy  Unable to find a node that satisfies the following conditions
[port 5982 (Bridge mode) port 5983 (Bridge mode) port 5980 (Bridge mode) port 5981 (Bridge mode)]
[available container slots]
[serverclass==gateway]
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

`docker info` showed one `serverclass=gateway` and it all was well, nothing listening on the above ports according to `netstat -nat` either.

The problem was a previous instance had `Exited (0) 4 days ago`. I removed it with `docker rm <id>` and Compose ran successfully this time. This is actually closer to #3420 but may well boil down to the same logical error behind the scenes.

**Comment by tronicum** [comment]
@jmkgreen thanks for the hint. 
I just run into the problem and it was a stopped container which had the port exposed from an manual test before. 
docker-compose would complain about not being able to bridge that port until I removed that container.

**Comment by viveky4d4v** [comment]
@emmetog - How can we check the hostname of nodes registered with consul ? Is it that what we pass at the docker machine creation time ? If there is any other way to check please let me know , GUI didn't helped .

I think i am stuck at a similar situation , could you please help me in below -  https://github.com/docker/docker/issues/27887   

I believe i might have done a silly mistake .

**Comment by emmetog** [comment]
@viveky4d4v yes, the `--hostname` is set when you run the consul container. It's a docker argument, not a consul argument.
