### ISSUE TITLE
Named volume + swarm + constraint:node. How?

### ISSUE THREAD

**Issue by vingrad** [docker/compose#3613]
I want to define a named volume in my compose-config, but I need to specify the constraint:node for this named volume.

volumes:
 data-app:
   image: busybox:latest
   volumes:
     - /data:/var/www
   environment:
     - "constraint:node==node1"

But this does not work. Why? How can I specify the destination node for a named volume?

**Comment by gittycat** [comment]
Use this instead:
```
environment:
    - "constraint:node": "=node1"
```

**Comment by vingrad** [comment]
constraint:node does not work for volumes...

**Comment by ijc** [comment]
It's been a while but I think the idea here is that you have to pin the container to a specific node and the named volume must the necessarily follow since volumes are mounted from the host.

Since the question is several years old I'm going to close. If the above isn't sufficient then I would encourage you to post on our forums: https://forums.docker.com for questions about using `docker-compose`.
