### ISSUE TITLE
Volumes in hyper-v docker 

### ISSUE THREAD

**Issue by marfillaster** [docker/compose#3642]
The recently released beta can mount windows host directory using this test command

```
docker run --rm -v c:/Users:/data alpine ls /data
```

However, it is not working when used in compose under the volumes key:

```
 alpine:
   image: alpine
 volumes:
       - c:/Users:/data
```

We get this error instead

```
C:\> docker-compose run alpine ls /data
ERROR: Named volume " c:/Users" is used in service "alpine" but no declaration was found in the volumes section.  
```

Workaround

```
volumes:
     - $PROJECT_PATH:/data

PROJECT_PATH=/c/Users docker-compose run alpine ls /data
```

**Comment by janhartigan** [comment]
Not totally sure, but I think this issue is also preventing me from using `docker-compose` to mount files in volumes from my host to my containers. I thought it was completely broken until I tried:

```
docker run --rm -v c:/Users:/data alpine ls /data
```

...and finally I saw the data mounted.

@marfillaster I'm curious about how you get your workaround to work. How do you set that environment variable in Windows and did you set that volumes in inside the service or outside of it? Relative noob to docker and trying to get it working on Windows (hyper-v the latest beta Docker for Windows), so any guidance you can give would be much appreciated!

**Comment by marfillaster** [comment]
@janhartigan You should be running docker-compose inside bash on windows (available for insider folks). The environment can then be exported inside .bashrc.

**Comment by ijc** [comment]
I believe this was fixed several releases ago and `docker compose` is now compatible with Docker Desktop on Windows (which I think is "the beta") referred to.
