### ISSUE TITLE
Docker compose pull doesn't respect local images

### ISSUE THREAD

**Issue by antony** [docker/compose#3660]
During my searches I've seen this issue raised and closed a few times, but even using the latest build of docker-compose, this still doesn't behave the way I understand that it is expected to.

Scenario:
We're building a composed environment for our CI tests to run. We grab a database image, an api image, and a _local_ copy of the image containing application we are trying to test (it has been built in a previous CI step, and tagged with the build hash provided by our CI environment (CIRCLE_SHA1)

docker-compose.yml

``` yaml
api:
  image: mycompany/api

undertest:
  image: mycompany/undertest:${CIRCLE_SHA1}

db:
  image: mycompany/db
```

The commands we run then are as follows:

``` bash
docker-compose pull # Because we definitely want the latest db, and api for a true test.
docker-compose up # compose the environment
```

Actual Result:
No matter what I do, docker compose always tries to pull my CIRCLE_SHA1 tagged version from  docker hub. it doesn't exist there, I never want to push it (until it passes tests and is re-tagged as :latest and/or :release 

I have a unique tag CIRCLE_SHA1 which only exists inside the build environment, meaning no confusion for docker-compose when it tries to pull, and yet, it seems to try to fetch it anyway, and fail even though that exact tag exists locally.

Expected Result:
I'd expect the fact that there is no remote build tagged with CIRCLE_SHA1 to cause docker-compose to use the local copy it finds. I need to do pull, because I want everything else to be the latest.

I'd suggest that if there is confusion where `image:` refers to a remote repository, then perhaps we could use `local:` instead, to reference a local image?

**Comment by decoomanj** [comment]
I'm facing similar issues. I use the --ignore-pull-failures option when I do a docker-compose pull. This basically ignores ALL errors. It is ok as a workaround. We do the same thing in our pipeline. I pull other production-images and start my freshly build release-candidate container locally. When the tests are ok, it's uploaded.

**Comment by johnharris85** [comment]
I don't see this is a issue / bug with current functionality. `pull` is doing exactly that, how would it know in your original compose file that 2 images should be pulled remotely but one should be grabbed locally (seeing as they all probably exist locally right, you just want to 'refresh' the other two?).

Perhaps a --filter option, so something like:

    docker-compose.yml
    version: '2'
    services:
      api:
        image: mycompany/api
        labels:
          - "refresh"
      undertest:
        image: mycompany/undertest:${CIRCLE_SHA1}
      db:
      image: mycompany/db
      labels:
        - "refresh"

Then:

 `docker-compose pull --filter "label=refresh"`

@aanand @dnephin thoughts?

**Comment by dnephin** [comment]
`--ignore-pull-failures` for this very reason. 

You could also do `docker-compose pull db api` to only pull the ones you wanted.

**Comment by johnharris85** [comment]
Both of those options seem kind of sub-optimal. 

It's not really a 'failure' to ignore, more of a separate use case. 

The second option means you're having to declare some behavior / state outside of the compose file. I.e. I have all of this automated but then want to change which images are pulled and which aren't, I probably want that to be reflected in my compose file as a single-point-of-truth, but I have to edit the pull command instead.

**Comment by antony** [comment]
I'd agree with @johnharris85 on `--ignore-pull-failures` not feeling like the option to use. Something like `--prefer-local` would work - but I'd still probably prefer a concrete `local: my-org/my-image:tag` to make for a clearer intent.

**Comment by JashaadGaines** [comment]
Problem: 
I agree @johnharris85 - These options are suboptimal. Docker is sort of acting like a dependency manager or at least one dependency resolver. It pulls images from a specified/default repo then/and only then, commences it's docker process. In the same way gradle, ant, maven, gulp, npm, etc. pull dependencies and define processes the user can run. The standard has been set for Dependency Mgr/Resolvers, look locally first (sometimes cache or something), then pull from repo. I'm trying to think of a really pressing reason why docker would want to force you to look at the repo first. Just like @antony & @decoomanj I don't want to push any images that don't even satisfy our lowest level of threshold: unit tests. Not to mention any other test suite. 

Suggestion: 
rancher-compose offers a --pull option to insure you're getting the latest image from the repo. It would be great if docker-compose looked for images locally first then to the repo. And if necessary there can be a --pull option to force docker to only search for images in the repo.

**Comment by rabelenda** [comment]
I am facing a similar problem, when I try to do `docker-compose up` with a local image, it is trying to pull the image from remote repo and since is not there it fails. I have to push the image and then do `docker-compose up`, which doesn't make sense at all. This is something that start failing recently for me, I am using docker for mac 17.03.0-ce and docker-compose 1.11.2, this used to work when I used docker 1.6 and docker-compose 1.3. Any clues how to avoid this issue?

**Comment by martindariocernadas** [comment]
Any clues how to avoid this issue?

**Comment by smebberson** [comment]
I'd like to know how to avoid this issue too.

**Comment by izrobin** [comment]
I'd also like to use a locally built image, before building and publishing a real image to our registry. How would I go about doing that? Looking at this conversation, it seems impossible to use locally installed images?

**Comment by KamilKopaczyk** [comment]
> The Compose file should really only include configuration for those containers. How to pull an image is not container configuration
It's not only for containers if docker-compose allows to pull and push.

Maybe it shouldn't be concern for docker-compose? Maybe docker should mark locally built, not-yet-pushed images and ignore it when trying to pull this particular image.

It's PITA since latest docker-compose releases,  we're able to build docker images with concrete name specified in docker-compose.yml.
This way if you do `docker-compose build --pull` you end up with errors and images not being pulled and built. It's even worse - you can't use `--ignore-pull-failures` flag with `docker-compose build`.

**Comment by skehlet** [comment]
A hacky workaround to use your local images is to run your own registry:
```
docker run -d -p 5000:5000 --name registry registry:2
docker tag 4e6a104bad19 localhost:5000/stevek/my-container
docker push localhost:5000/stevek/my-container
# edit docker-compose file to use localhost:5000/stevek/my-container
docker-compose ...
```

**Comment by Constantin07** [comment]
+1 same issue

**Comment by karunapuri** [comment]
Try this './docker-env -c ./build --no-update'. This command works for running locally built images.

**Comment by joeyhub** [comment]
This kind of solution isn't really viable:

     --ignore-pull-failures was added for this very reason.

People want to ignore that an image is local. Not necessarily every other type of error.

Seasoned developers will tend to program strictly and abort on the first error. This breaks with that.

**Comment by NoahO** [comment]
With the status quo, using —ignore-pull-failures and —include-deps together doesn’t actually work.. my dockerfile has “FROM: ubuntu:16.04”, but this dependency is never pulled because of the pull failure...

Of course it is pulled when I later build, but there is no way to force pull the latest version of every dependency, so it is left with the first version of the image forever...

I imagine there is a lot of out of date code in production for this reason..

**Comment by zuernBernhard** [comment]
--prefer-local (prefer newer image with same tag on local machine) would be great - than we can use the same compose file and workflow in local development and in production - and it is always possible to locally override images with ease for testing purpose

**Comment by SuperSandro2000** [comment]
Bump

**Comment by arkadyt** [comment]
Bump

**Comment by amackiewicz** [comment]
bump

**Comment by ndeloof** [comment]
On 1.25.1 service with a `Build` section won't break `docker-compose build` but report need to build image.

see https://github.com/docker/compose/pull/7052

**Comment by ndeloof** [comment]
@noaho as you use “FROM: ubuntu:16.04” in a Dockerfile this is *not* what compose consider a "dependency". dependencies is about services in your compose file, i.e if you run `docker-compose <command> service1 --include-deps` and service1 depends on service2 in your compose file, then command will also be ran on service2. 

You're in charge for base image used by your Dockerfile. If you wish to get notified on updates/vulnerabilities reports, then check DockerHub features.

**Comment by thisismydesign** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by jpbochi** [comment]
bot wars!

**Comment by fgauer** [comment]
Hi chiming in here...this has had me stumped for days trying to stand up a new Docker based development environment using docker-compose and has led to much frustration and needless pain.

Coming from an environment where we have not used the **image:** feature in docker-compose.yml and now attempting to utilize it for CI/CD purposes for a new project we realized, after a significant amount of time, trial and error, that the docker-compose up always pulls from the repo defined in **image:** and does not give us a way to intuitively pull from a local image where/when we need to (i.e. local development).

We have the following goals with our setup:

1) We want to use the same set of docker-compose.yml files for CI/CD purposes in various environments, which includes local development, that should allow for a developer to make changes to the code base and immediately re-build the containers on their local machines in order to work with their changes.
2) In order to facilitate #1, in other words use the same set of scripts for various deployment environments, we use ENV variable substitutions in our docker-compose.yml files. This works fine until you throw in the local development scenario where we need to grab locally built images for development iteration.

Since the **image:** feature currently does not allow us to intuitively override ride it in such a way as to have it look for a local image, I believe we faced with going with one of the following options below. Please bear in mind that whereas the options below work, it was getting to this conclusion that was really quite painful due to the counterintuitive nature (at least this was my experience personally) of how the **image:** feature works without some kind of local override option.

1) Setup a completely separate docker-compose.yml file for local development purposes, or overlay multiple docker-compose.yml files to specify the environment’s **image:** tag in all environments except for local development. But with the ENV variable substitution features current working in docker-compose.yml for all of our other environments, why would we have to go here? It would be nice to substitute something in like ‘local:’ for the image name and have Docker Compose respond accordingly using ENV variables.

2) Setup a local ‘development’ repository on each developer’s local machine. We could do this, but it seems to rub against one of the fundamental advantages of using Docker for local development which is to minimize the amount of individual local environment setup for individual developers, and tracking/managing that whole circus.

**Comment by lucasbasquerotto** [comment]
@fgauer In my case I don't want to pull images if there is already a local image because that can be time consuming if there are lots of images (even if all of them are already pulled), furthermore it could give errors if there's no internet or if the connection fails. 

What I did to solve it was  to not use `image:` but `build:` in the `docker-compose.yml` file, because `build` pulls only when needed, and I use a Dockerfile that only defines the image I want to pull. I use build `args` to not have to create lots of Dockerfiles, like the following:

_Dockerfile:_

```
ARG IMAGE
ARG VERSION

FROM $IMAGE:$VERSION
```

`docker-compose.yml:`

```
services:
  my_service:
    build:
      context: .
      dockerfile: "path/to/Dockerfile"
      args:
        IMAGE: "alpine"
        VERSION: "latest"
```

Then I just run `docker-compose build` (and not `docker-compose pull`) and the problem is solved for me.

I don't know if it will work in your case, but you could give it a try.

**Comment by erdnaxeli** [comment]
The problem is actually this:
* we want to run `docker-compose pull` to pull external images
* we don't want the same command to fail on local only images, because that's not an actual error, that's the expected behavior (you can't pull an image not pushed on a registry)
* we don't want to have to specify the list of images to pull in the command line, because we want all the config to stay in the docker-compose file
* we don't want to ignore all errors, because errors can happen and we want to see them

Currently it fails because it does not know that the image is local only. Can't we add something in the docker-compose file to let it know it is local only and it should not try to pull it? Something like this would do the job:
```
services:
  my_service:
    image: some_external image
  my_private_service:
    image: some_local_only_image
    pull: false
```

This way I am explicitly telling docker compose that I don't want it to try to pull this image, and everyone is happy.

**Comment by SuperSandro2000** [comment]
I think this syntax is more logical.

```
services:
  my_service:
    image: some_external image
  my_private_service:
    image:
      name: some_local_only_image
      pull: false
```

**Comment by mslipets** [comment]
Bump!

**Comment by akashjain971** [comment]
A workaround for this while developing locally and save pull time:

1. Create a local docker registry like [this](https://docs.docker.com/registry/deploying/)
2. Pull the image from the remote docker registry (**abc/xyz:latest**)
3. Tag this image to point to the local docker registry (**docker tag abc/xyz:latest localhost:5000/abc-xyz-latest**)
4. Push this image to the local docker registry (**docker push localhost:5000/abc-xyz-latest**)
5. Use this image in your local docker-compose file

**Comment by EricBorland** [comment]
@akashjain971 Oh man, you saved me. It's a very ugly workaround but works like a charm. Shame than docker-compose doesn't have anything like the `pull: false` commented above.
Thank you very much :)

**Comment by TheSpad** [comment]
Is it not simpler for there to be a reserved "repo" name for locally-built images such that something like:
```yaml
service:
  my_service:
    image: localhost/myimage:devtag
  my_other_service:
    image: redis:alpine
```
Means that Compose knows that my_service is using an image that only exists as a local build and would never attempt to pull it?

**Comment by phramz** [comment]
Would be nice to have a K8S-like `imagePullPolicy` (`IfNotPresent`|`always`|`never`) to the yaml service section? That would be familiar to many folks as well as solving most of the common use cases right away.

**Comment by tdepalle** [comment]
Still no solution better than creating a local registry ?

**Comment by ard-i** [comment]
You can force compose to use a local image by doing the following:

```

docker pull remoteimage:latest
docker tag remoteimage:latest localimage

```

then call localimage:latest in the compose.

This seems to work for me.

**Comment by erdnaxeli** [comment]
@ard-i that's not what the issue is about. The issue is about using `docker-compose pull` when at leat one image in the docker-compose file *does not* existe on the remote registry but exists locally.

**Comment by haneef95** [comment]
Thanks @lucasbasquerotto 

Using `build:` worked like a charm!

**Comment by ndeloof** [comment]
AFAICT [`pull_policy: missing`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) introduced by the compose specification should be enough to address this issue.

**Comment by lucasbasquerotto** [comment]
@ndeloof With `Compose implementations SHOULD pull the image only if it's not available in the platform cache` it means that if a image with the tag is already local it won't even try to pull (nor try to connect to the remote repository), or it will try to verify if the remote image with the tag exists and has the same image id/hash? The former is probably what people in this issue want (no remote connection at all if `image:tag` exists locally). The later is what already happens currently.

**Comment by ndeloof** [comment]
The spec don't define how implementation has to behave regarding registry connexion, but a reasonable implementation would be:
```
exists := localengine.lookup(image)
if ! exists {
    docker.pull(image)
}
```
About checking the image is up-to-date with registry one, there's unfortunately no such thing as a portable hash to be compared with the remote. The local image ID only exists in the local engine. Using `always` would then force (at least, try to) pull from registry:
```
err := docker.pull(image)
if err != nil {
	exists := localengine.lookup(image)
	if ! exists {
		return error.New("Sorry")
    }	
    // never mind, we have a local image for it. Maybe just warn user?
}
```

**Comment by haneef95** [comment]
> AFAICT [`pull_policy: missing`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) introduced by the compose specification should be enough to address this issue.

Thanks @ndeloof 

I've tried both `pull_policy:` and [`pull:`](https://docs.docker.com/engine/reference/commandline/run/#:~:text=to%20random%20ports-,--pull,-missing) defined in docker run.

Both are giving me errors:
![image](https://user-images.githubusercontent.com/298208/142424790-b7da8f57-6f63-42db-a047-d66097ba35a0.png)
![image](https://user-images.githubusercontent.com/298208/142424828-fe29d929-a4c2-434a-8a9b-457695f257b5.png)

`docker-compose version 1.25.0`

**Comment by ndeloof** [comment]
I said this was introduced by the compose-spec, and could be used to support this feature request, not that it's already supported in docker compose!

**Comment by haneef95** [comment]
hopefully, it's implemented soon! This is already available with `docker run`, so should be a fairly quick implementation?

**Comment by eladitzhakian** [comment]
Is this being addressed? It's a real pain for some use cases and the solution seems pretty straightforward

**Comment by filinvadim** [comment]
My workaround:
`DOCKER_BUILDKIT=0 docker compose -f docker-compose.yml up your-app`

**Comment by filinvadim** [comment]
Found the issue. For latest Docker versions that happens because you haven't pointed base image platform type like `linux/amd64` for example.

**Comment by erlangparasu** [comment]
@filinvadim thanks. add `DOCKER_BUILDKIT=0` to environment works for me

**Comment by typoworx-de** [comment]
Still having the issue and found this thread! I don't think disabling Buildkit is a smart hack if one wants to use buildkit-features like ```COPY --chmod=a+x```

The matter that buildkit obviously breaks this is a bug. Has this been reported to buildkit or is the bug located in docker itself?

**Comment by al-dot-exe** [comment]
Know this issue is closed but you can use watchtower on a custom custom interval to keep remote images up to date and never push your local image to docker hub [watchtower](https://containrrr.dev/watchtower/)
