### ISSUE TITLE
scale does not distribute to other nodes (in swarm cluster)

### ISSUE THREAD

**Issue by 2trc** [docker/compose#3881]
**_Setup_**
I have deployed a swarm standalone cluster on 3 nodes (each behaving as manager and regular node) with Zookeeper as the discovery service (mainly following [Build a Swarm cluster for production](https://docs.docker.com/swarm/install-manual/)).  Everything seems to be working (docker info shows 3 healthy nodes). I can run containers as well.
So I tried using docker-compose to test the 'scale' functionality. I followed this tutorial: [How to scale Docker Containers with Docker-Compose](https://www.brianchristner.io/how-to-scale-a-docker-container-with-docker-compose/).

**_Problem_**
I was surprised to see that all containers were deployed on the same host. Then I tried scaling the containers (by 10) but they remained on the same node.

Is this the expected behavior?
How do I get the load to be shared across nodes?

PS: I just noticed that docker-compose now has some [affinity/filter/scheduling](https://docs.docker.com/swarm/scheduler/filter/) but I didn't use any of those.

**_Environment details_**

```
docker --version
Docker version 1.12.1, build 23cf638
```

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.5
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   27968ed
 Built:        Thu Aug 18 23:10:29 UTC 2016
 OS/Arch:      linux/amd64
```

```
docker-compose version
docker-compose version 1.8.0, build 94f7016
docker-py version: 1.9.0
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
```

**_docker-compose.yml_**

```
version: '2'
services:
  web:
    image: dockercloud/hello-world
    ports:
      - 8080
  redis:
    image: redis
```

**Comment by mujiburger** [comment]
Did you `export DOCKER_HOST=tcp://127.0.0.1:4000` before running `docker-compose up` and `docker-compose scale`?

**Comment by optimum-web** [comment]
Same issue here,   what export DOCKER_HOST=tcp://127.0.0.1:4000  supposed to do ?  
Any info on how to distribute containers to other nodes ?

**Comment by mujiburger** [comment]
To be clear, my answer in the form of a question is based around the old style swarm described in the how to that the OP referenced, not the new engine swarmmode.  If you used the walk through referenced in the OP, then you have to tell docker-compose to communicate with the swarm master instead of communicating with the local docker engine directly.  It is the same as adding `-H :4000` to your docker commands which is described in the walk through.  Compose configuration is done using environmental variables as described [here](https://docs.docker.com/compose/reference/envvars/).  None of this really applies if you are using the new docker engine swarmmode instead of an old style swarm.

**Comment by optimum-web** [comment]
@2trc  hi.  I removed all images from swarm master and pulled them again from docker hub and it started to distribute containers to other nodes.
