### ISSUE TITLE
Add ability to reload env_file for a specific container

### ISSUE THREAD

**Issue by joaquincasares** [docker/compose#4140]
Hello,

I'm not sure if this task is something that compose can handle alone, or if I also need to create a ticket against the docker project, but I figured to start here.

My use case is: 
* I have ngnix, cassandra, and a web container running, via `docker-compose up`.
* I've updated an env_file used by the web container.
* Now, I'd wish to have my web container use the updated env_file.

If I try:
* `docker-compose [stop|kill] web`
* `docker-compose start web`

I still get my original envars that were in place at the time of `docker-compose up`.

How can I reload my web container to consume the updated env_file without having to do a full shutdown via `docker-compose down`?

Thanks for any help and guidance!

**Comment by shin-** [comment]
You would need to do `docker-compose up --force-recreate web`, I think. Let me know if that works!

**Comment by joaquincasares** [comment]
I gave that a shot, but it seems like a bit of a destructive path for just reloading an env_file:

```
$ docker-compose up --force-recreate web
Recreating project_cassandra_1
Recreating project_zookeeper_1
Recreating project_kafka_1
...
```

I understand that's caused by the docker-compose `links` definition. Thanks for the help though! Do you by chance have any other suggestions?

**Comment by Dineshs91** [comment]
`docker exec -it <container_name> bash -c "source env_file"`
`docker restart <container_name>` or `docker-compose up -d <service_name>`

@joaquincasares Can you try these and see if it helps ?

**Comment by MetricMike** [comment]
(as of 1.12.5) I think the `.env_file` directive in your `docker-compose.yml` is doing a couple things:

0) After a container is built, but before CMD/ENTRYPOINT is called,
1) Copy `<env_file>` into the container.
2) Call `source <env_file>`

Based on `docker-compose --verbose` and https://github.com/docker/compose/blob/master/compose/config/config.py it looks like docker-compose can check the env file (and volume/network settings) for changes to the configuration. 

So when you run, `docker-compose up`, one of two things might happen assuming your Dockerfile hasn't changed and an up-to-date image has been built:
* No config changes? Don't do anything unless another option like `--force-recreate` is passed.
* Yes changes? Reapply any config changes needed (copy and source env_file, open ports, mnt volumes). Then call the equivalent of `docker-compose restart <service>` and restart the container, because docker-compose can't tell what you're running inside and what services might need a restart to pick up those config changes, refresh file handles, etc.

`restart` skips an important step (because docker-compose has chosen to make container configuration part of the build step, which probably isn't a terrible idea), but you shouldn't need to tear everything down to do what you want.

Hope that helps! I've been wrestling with a similar problem most of today :)

**Comment by shin-** [comment]
When a container is recreated the containers that depend on it are recreated as well, which is the behavior you want in most cases. 
You could make a case for adding an option that simply reconnect the existing dependents to the new container instead, but it's honestly not very high on the list of priorities.
