### ISSUE TITLE
With --userland-proxy=false, dockerd listens on exposed ports (instead of docker-proxy)

### ISSUE THREAD

**Issue by peterthomassen** [docker/compose#4168]
I assign IPv6 addresses directly to my docker containers and don't want anything docker-related to be available on the host IPv6 address.

By default, `docker-proxy` listens on the host IPv6 address to deal with traffic coming in on exposed ports (each with a different process). I therefore added `--userland-proxy=false` to the `dockerd` systemd configuration.

It turns out that the main `dockerd` process now listens on the exposed ports instead. While I was not able to establish a connection on these ports (I tried an SSL connection on port 443, with no success), I am wondering what the purpose of this is.

- Why does `dockerd` listen on exposed ports when `--userland-proxy=false` is set?
- What sort of communication can be done with `dockerd` through these ports? Is any form of remote control possible?

**Comment by peterthomassen** [comment]
was not meant for compose -- sorry

**Comment by konstantinj** [comment]
Hi,
same issue for me after I've update docker from 1.12.x to 17.06.x.
`2017-09-18T21:12:23.335362+00:00 mail postfix/smtpd[623]: connect from unknown[172.17.0.1]`
Also with the new docker version I cannot get the client ip from my nginx container anymore.
Unfortunately setting userland-proxy=false makes it worse since the mailserver is then not able to get traffic anymore. But sending still works. But: Nginx then gets the client ip. What did docker do?
