### ISSUE TITLE
Is it possible to add attach function to fig?

### ISSUE THREAD

**Issue by 0xcb49** [docker/compose#423]
For example, Using command "fig attach appname" to enter the container which was created by fig.
 I think this may be helpful in some cases. Now I know that nsenter can attach a new bash shell on 
a running container, but I don't know if it's possible to intergrate it with fig. Thanks.

**Comment by koddo** [comment]
@aanand, @michaelsbradleyjr, I second that. When I do `fig up`, I can't get an erlang shell on a remote node. I have to do 'fig run' and then something like this works:
```
$ docker exec -it foo_web_run_1 erl -remsh 'foo@172.17.0.12'
```
I'd like to be able to get the repl even in production environment.

**Comment by michaelsbradleyjr** [comment]
@koddo I've been doing something similar. By the way, there's a tty-related bug in `docker exec`:

https://github.com/docker/docker/issues/8755 

The documentation and help output don't mention it, and it can be tricky to figure out what's going on if you don't' think to check the output of the `tty` command. Anyway, I just wanted to give you a heads up in case you weren't aware of the bug.

**Comment by thomasf** [comment]
I don't know if this can be closed now but `docker-compose.yml` now supports this:

```yaml
app:
  tty: true
  stdin_open: true
```

Which also seems to make `docker attach project_app_1` do the right thing in combination..

**Comment by cameron** [comment]
@thomasf to the rescue!

**Comment by jaccarmac** [comment]
```
tty: true
stdin_open: true
```

does not work for me. It may be because I'm on Windows, or it may be a bug in a newer version of Compose. I'm on 1.6.0.

**Comment by kaiomagalhaes** [comment]
Thanks @thomasf

**Comment by gkop** [comment]
Curious, what is different between `docker-compose up <service>` and `docker-compose up -d <service>` followed by `docker attach <service-instance>` that @thomasf' solution for interactive debugging works with the latter but not with the former? (using pry, with the former, execution stops, but standard input doesn't seem to make it to the container).

**Comment by aanand** [comment]
'up' does not hook up the terminal stdin. It's not designed for interactive
use, because it usually operates on multiple containers.

**Comment by k2nr** [comment]
Because I also wanted to `attach` to a running `rails server` process to communicate with `binding.pry`, I am using the following simple script, which works well for me.

```bash
#!/usr/bin/env bash
docker attach $(docker-compose ps -q $1)
```

Name it `docker-compose-attach` and then run `docker-compose-attach <service>`

But I believe it's better for docker-compose to have `attach` subcommand

**Comment by gkop** [comment]
Our team has observed that while the config suggested by @thomasf does work nicely to permit interactive debugging of running containers, `stdin_open: true` causes strange and unfortunate side effects when running `docker-compose logs`: the timestamps are missing from the logs and we get disconnected after 1 minute.

@k2nr first of all, thank you for the alias - it is certainly handy for myself and my team, as attach is a viable workaround in the face of the issue with the logs ^^ . I don't think however it belongs as a proper subcommand to docker-compose because it assumes that you only have one docker instance of the service running, which is not realistic in many cases.

**Comment by gkop** [comment]
@dnephin I think what we're observing in first paragraph above ^^ might be an incident of https://github.com/docker/compose/issues/3106#issuecomment-196508170 - in our case however it's apparently `stdin_open` rather than `tty` that's triggering the timeout and missing timestamps in docker-compose logs.

Should I create a separate issue for this?

/cc @thaJeztah

**Comment by shin-** [comment]
With #3106 fixed and `exec` and `run` implemented, I believe this can be closed. I don't think there's a scenario where `attach` makes a lot of sense (especially over the two other subcommands).

**Comment by JamesLivengood** [comment]
@thomasf That worked for me to get into a debugger, but it doesn't let me type anything - like typing in c, or n to continue through doesn't work (I have to ctrl + C and close the server to get out of it)
