### ISSUE TITLE
fig.yml should support unsetting entrypoint/command

### ISSUE THREAD

**Issue by bendk** [docker/compose#436]
As far as I can tell, if these are set in the Dockerfile, there is no way to unset them with fig.yml.  I would like to be able to unset them with something like this:

```
    entrypoint:
    command:
```

The use case is simple, suppose a Dockerfile specifies both and I want to run /bin/bash in the container.  It's not obvious how to do this.  For example, if I use `enrtypoint: /bin/bash`, it  will pass the command to bash.

There are various ways to make it work, for example `command: -i`.  But it should be more obvious.

**Comment by artburkart** [comment]
Can I expect the `[]` unsetting strategy to be around for the long-term?

**Comment by shin-** [comment]
More intuitively, the `command` and `entrypoint` keys can be omitted altogether and will default to the image's value.

**Comment by artburkart** [comment]
@shin- If I understand correctly, I think your proposal achieves the opposite of the goal in this issue.

**Comment by bendk** [comment]
Yes, this is not why the issue was opened.  Please re-read the description.

**Comment by shin-** [comment]
You're right, my apologies. I'll make a PR to https://github.com/docker/docker.github.io to add it to the docs when I have some time, unless one of you beats me to it.

**Comment by artburkart** [comment]
Looks like–since this PR was merged–it is also possible to unset the entrypoint with `""`.

**Comment by artburkart** [comment]
@shin- After further reviewing it, I would maybe argue no further documentation is required. There's a [table in the docker docs](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact), which indicates it's possible to _not_ set the `entrypoint`.

|                                | No ENTRYPOINT              | ENTRYPOINT exec_entry p1_entry | ENTRYPOINT ["exec_entry", "p1_entry"]          |
|--------------------------------|----------------------------|--------------------------------|------------------------------------------------|
| **No CMD**                     | *error, not allowed*       | /bin/sh -c exec_entry p1_entry | exec_entry p1_entry                            |
| **CMD ["exec_cmd", "p1_cmd"]** | exec_cmd p1_cmd            | /bin/sh -c exec_entry p1_entry | exec_entry p1_entry exec_cmd p1_cmd            |
| **CMD ["p1_cmd", "p2_cmd"]**   | p1_cmd p2_cmd              | /bin/sh -c exec_entry p1_entry | exec_entry p1_entry p1_cmd p2_cmd              |
| **CMD exec_cmd p1_cmd**        | /bin/sh -c exec_cmd p1_cmd | /bin/sh -c exec_entry p1_entry | exec_entry p1_entry /bin/sh -c exec_cmd p1_cmd |

Given this table and the [docs about the entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint):

> ## ENTRYPOINT
> 
> ENTRYPOINT has two forms:
> 
> - `ENTRYPOINT ["executable", "param1", "param2"]`
>   (*exec* form, preferred)
> - `ENTRYPOINT command param1 param2`
>   (*shell* form)

I'd say it's not a huge stretch to deduce that `[]` and `""` are valid values for `entrypoint` (although this wasn't the case when this issue was opened).
