### ISSUE TITLE
docker-compose 1.9.0 compromised with Linux.Xor.DDoS

### ISSUE THREAD

**Issue by domdorn** [docker/compose#4388]
Hi!

I installed docker-compose (1.9.0) on three servers around december 25th 2016. Now all three servers report Linux.Xor.DDoS by chkrootkit. 

The list of files. md5sums, the output of chkrootkit is in this pastebin: http://pastebin.com/uS2b8uyG

I couldn't attach a copy of the files, so I uploaded a tar.gz to a cloud-hoster: 
http://filebin.ca/3A9L1AIVGblT/docker_possible_backdoor.tar.gz

I really hope this is a false positive.. 

Thanks,
Dominik

**Comment by shin-** [comment]
Thank you for reaching out.

> I'd like to know
> a) is this is a false positive of chkrootkit ?

The `docker-compose` binaries are built by our CI system in isolated, clean environments that are created and destroyed on the fly. Specifically for the Linux x86_64 binaries, those are generated by [Travis](https://travis-ci.org/docker/compose/branches).
My understanding is that this is indeed a false positive.

> b) why is docker-compose putting files in my /tmp directory, when I already downloaded the binary files into my /usr/local/bin directory?

The compose binary is created using [PyInstaller](http://www.pyinstaller.org/), which works by self-extracting into a self-contained Python environment in your OS's `/tmp` directory. This is expected behavior and should not cause any worry in and of itself.

> c) is this version of docker-compose (1.9.0 on Linux_x86_64) compromised ?

Again, not to my understanding (see my answer to a)

**Comment by n4ss** [comment]
Thanks again for opening an issue, this is indeed a false positive.

As you can see in `chkrootkit` code:

```
## Linux/Xor.DDoS
   if [ "${QUIET}" != "t" ]; then
      printn "Searching for Linux.Xor.DDoS ... "; fi
   files="`${find} ${ROOTDIR}tmp/ ${findargs} -executable -type f 2> /dev/null`"
   if [ "${files}" = "" ]; then
      files="`${ls} ${ROOTDIR}etc/cron.hourly/udev.sh 2> /dev/null`"
      if [ "${files}" = "" ]; then
         if [ "${QUIET}" != "t" ]; then echo "nothing found"; fi
      else
         echo "INFECTED: Possible Malicious Linux.Xor.DDoS installed"
      fi
   else
     echo "INFECTED: Possible Malicious Linux.Xor.DDoS installed"
     echo "${files}"
   fi
```


`chkrootkit` does 2 things to check for a Linux.Xor.DDoS infection:

1.  Check for regular executable files in `/tmp` and its subdirectories
2.  Look for a shell launching a hourly cron job started at boot at `/etc/cron.hourly/udev.sh`

@shin- mentioned that [PyInstaller](http://www.pyinstaller.org/) creates an environment in your `/tmp` directory with every file (and directory) in it readable, writable and executable by default.

That's why even the `GITSHA` file by itself will trigger an infection message in this case.

Please verify that there is no unwanted executable files in your `/etc/cron.*/` directories to be sure, if not, this is a false positive.

**Comment by domdorn** [comment]
I don't have any unusual cron files, so looks like a false positive - thank god. 
Maybe we could add a README to the directory that gets created ? or even a README.chkrootkit ?
