### ISSUE TITLE
GPU resource support

### ISSUE THREAD

**Issue by vditya** [docker/compose#4657]
Is there an effort to support GPU as another resource type within docker compose specification?

**Comment by shin-** [comment]
If it's supported in Engine we'll gladly add it in Compose.

**Comment by ksnzh** [comment]
Try nvidia-docker and nvidia-docker-compose.

**Comment by andyneff** [comment]
I was just looking in to making `compose` able to support this without `nvidia-docker-compose` 

@shin, it comes down to [this](https://github.com/docker/compose/blob/ce44c865e5939645cb919c0278776a0f5de876bc/compose/cli/main.py#L1233) line. To make a GPU docker work, all we need to do is call `nvidia-docker` instead of `docker`. The executable `docker` is hard coded in here. I would propose a feature where we can override the value `docker` with something else (say `nvidia-docker`). I have a few ideas in mind, do you like any of them?

1. Replace the string `docker` with `os.getenv('DOCKER_EXECUTABLE', 'docker')`. (Simplest)
2. And an option to the CLI to specify a different docker executable name. (Slightly more work)
3. And an option to the CLI to specify a different docker executable path. (More work)
4. Detect if the image is a GPU image and automatically choose to `find_executable('nvidia-docker')` when it is a GPU image. This can be done by checking the label `com.nvidia.volumes.needed="nvidia_driver"` (Most work)
5. ~~Always search for `find_executable('nvidia-docker')` and if that fails, then search for find_executable('docker') (hacky-est)~~

Option 4 would result in the smoothest user experience because the user would never have to do anything, and it would *just work*. Which option would you prefer in `compose`?

## Background

`nvidia-docker` is a [shim](https://en.wikipedia.org/wiki/Shim_(computing)) that is called exactly like `docker` to handles the complication of passing a GPU from a linux host to a linux docker. It is an extremely useful "plugin" and I consider it to be the mainstream way of running GPU dockers now. (While it is possible to run a GPU docker with `nvidia-docker` it just handles the drivers so eloquently its so much better than manually handling it).

**Comment by shin-** [comment]
@andyneff That line you highlighted is only used in the context of a Windows client - I don't think it's relevant to the experience of `nvidia-docker` users?

**Comment by andyneff** [comment]
@shin Darn... Sorry about that, I was just quickly scanning the code, haven't had time to attempt a POC yet. Looking at it closer, looks like you are using py-docker, which if I understand correctly, doesn't use the `docker` (client) executable at all? So there's no room to call the `nvidia-docker` executable I take it? :-\

Guess the answer is no, it's is not supported by the docker engine. It's at the `docker client` level. 

---

When running [locally](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#running-it-locally) `nvidia-docker` does two main things:

1. `nvidia-docker` creates a volume using the `nvidia-docker` driver to store the drivers. This is the complicated step that even eywalker/nvidia-docker-compose#7 doesn't appear to have working.
2. It mounts the devices and volumes into a container when using `docker create`/`docker run`. This part is relatively easier. It involve:
    - Mount device `/dev/nvidia[0-9]+`
    - Mount device `/dev/nvidia-uvm`
    - Mount device `/dev/nvidiactl`
    - Determine the nvidia driver version. Here's how they did it in [go](https://github.com/NVIDIA/nvidia-docker/blob/3422bca272d64600ca15874d96e4e511b669c7c4/src/nvml/bindings.go#L59-L64) or simply parsing `/proc/driver/nvidia/version` (Since this feature can only work on Linux). 
    - Mount volume `nvidia_driver_${NVIDIA_VERSION}` to `/usr/local/nvidia` as readonly

(I have no working knowledge of how nvidia-docker works in the remote case. However I think most of your users will be happy with the local case to start with)

So maybe we could give up on part 1, and try and implement part 2?

Maybe someone at nvidia would have a better idea for part 2. Maybe they could add an additional sub-command to `nvidia-docker` just to do volume creation from part 1? Any ideas @3xx0, @flx42 ?

**Comment by arthur-tacca** [comment]
@andyneff You might want to look at the nvidia-docker-compose source code (or the nvidia-docker documentation). Rather than hardcoding all those devices and volumes it [calls the nvidia-docker REST API](https://github.com/eywalker/nvidia-docker-compose/blob/master/bin/nvidia-docker-compose#L43), which returns a list of volumes to mount. I suspect this is less likely in future versions of nvidia-docker (although you do end up with the additional problem of how to find the REST API endpoint).

**Comment by andyneff** [comment]
@arthur-tacca Excellent idea using the endpoint. I had skimmed through the nvidia-docker-compose source code previously, but did not notice that detail. I was more distracted by the jinja templating and thinking "Woah, that's way out of scope for getting nvidia working".

As for finding the REST API, I would like to use the same behavior as [nvidia-docker](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker#running-it-remotely) using the [NV_HOST](https://github.com/NVIDIA/nvidia-docker/blob/3422bca272d64600ca15874d96e4e511b669c7c4/src/nvidia-docker/env.go#L61) enironment variable

This also pointed out I'm mounting the volume wrong, and need to specify the volume driver, which solves the last unsolved part of the problem creating the mount point when it does not exists. Thanks!

I will get coding on this!

**Comment by Motophan** [comment]
https://github.com/docker/compose/issues/8107

I hope this can get reopened, there is no modern/sane documentation on how to get a container able to use a GPU.
