### ISSUE TITLE
docker-compose rm fails when containers are paused

### ISSUE THREAD

**Issue by mcandre** [docker/compose#4679]
We expect `docker-compose rm [-f]` to completely remove the containers managed by docker-compose. For example, `docker-compose rm -f && docker-compose up` *should* be enough to completely wipe the containers and launch a new set. For example, when troubleshooting a Kafka cluster from zoidbergwill/docker-compose-kafka, users want a convenient way to wipe and recreate the entire stack in docker-compose, to eliminate any mistakes in the current configuration.

What actually happens, is that `docker-compose rm` only sees the containers that are currently running. As a workaround, users have to do a really awkward series of

```console
$ docker-compose up
(Wait for containers to come up)
(Send docker-compose up a kill signal with Control+C)
(Wait for docker-compose up to die a certain way)

$ docker-compose rm -f
$ docker-compose up
```

This sucks, please fix.

**Comment by shin-** [comment]
#4040 

1. `docker-compose rm` will not remove running containers - this is by design. There is nothing to fix.
2. With the next release, you will be able to run `docker-compose rm -f -s` to stop running containers before removing them. 
3. In the meantime, `docker-compose kill && docker-compose rm -f` should do the trick.
