### ISSUE TITLE
CommandError: /code/manage.py already exists,

### ISSUE THREAD

**Issue by plaindocs** [docker/compose#470]
Hi Guys,

Trying to run through the Getting Started with Django on Linux Mint:

```
$ fig --version
fig 0.5.2

$ docker -v
Docker version 1.2.0, build fa7b24f
```

But running `$ fig run web django-admin.py startproject figexample .`

```
.... snip ...

Step 6 : ADD . /code/
 ---> 24d453a8017f
Removing intermediate container 8581492d0a70
Successfully built 24d453a8017f
CommandError: /code/manage.py already exists, overlaying a project or app into an existing      directory won't replace conflicting files
```

**Comment by plaindocs** [comment]
I think I tried to create a directory with and old version of fig, which did not work, then after updating fig I ran the same command but the directory was already there.

So delete/move the existing dir and re run the command.

**Comment by erichonkanen** [comment]
totally new to docker, what do you mean the dir was already there? I dont see it on the host, is it created inside the boot2docker VM?

**Comment by plaindocs** [comment]
If I remember correctly, when you run 

    $ fig run web django-admin.py startproject figexample . 

the first time it create a `figexample` directory on the host. If you run the same command again it fails because the directory already exists.

**Comment by vinit1102** [comment]
It can happen due to two reasons :
1. You are trying to create a new folder with the exiting folder name.
2. You have previously deleted a folder with this name. Deleted it for some reason. But again trying to create package with this name.

To resolve this follow 

Go to <%System Path%>/PycharmProjects/<%Your Project Name%>/.idea/workspace.xml

edit this file "workspace.xml" and then search with the package name you are trying to create. 
delete that line and save the file.
Now try to run the command again. 

I hope this helps. 

Regards,

**Comment by Dhiraj-48** [comment]
This error occurs if you try to create another project in a single virtual environment. To remove error and create next project delete  "manage.py file" which is the file automatically created while starting project.
