### ISSUE TITLE
Docker Compose not using trusted content during pull

### ISSUE THREAD

**Issue by brian-bason** [docker/compose#4787]
We have been using content trust (notary) to sign our images when building and sending them to a third party repository.

We make use of docker compose to pull in all the required images that need to go on a particular device but we noticed that compose is not making use of notary to confirm that the images being pulled down have a tag record in the notary server thus marking it a trusted content.

We need to make sure that the images stored at the third party site have not be compromised from the day we uploaded them to the time they are deployed in production. Why doesn't docker compose respect the environment variables DOCKER_CONTENT_TRUST and DOCKER_CONTENT_TRUST_SERVER when running the pull command like the docker client does?

This seems to be a bug and therefore request to get it fixed please, thanks.

**Comment by shin-** [comment]
Content trust is implemented client-side in the Docker CLI. Since `docker-compose` is an entirely different code-base, we do not have a matching implementation of that feature at this time.

For the time being, you might want to pull images using the `docker` CLI before running `docker-compose up`.

**Comment by brian-bason** [comment]
This is a bit of a limitation. We have a number of images that need to go into production machines and we find it useful to make use of compose to manage the set of images that are to be deployed on a particular box.

Is this in the pipeline of getting done or still not on the radar? We have assumed that since docker compose is part of the ecosystem of Docker that the same feature for trusted content would have been implemented.

**Comment by MatthewVance** [comment]
It's also worth noting pulling the Docker compose image (docker/compose:1.15.0) with content trust enabled fails because the compose image itself has not been signed. 

```
docker pull --disable-content-trust=false docker/compose:1.15.0
Error: remote trust data does not exist for docker.io/docker/compose: notary.docker.io does not have trust data for docker.io/docker/compose 
```

**Comment by peterthomassen** [comment]
You might want to take a look at [trusted-compose](https://github.com/sse-secure-systems/trusted-compose).

It is a wrapper that uses `docker pull` with DCT to pull verified images, then propagates them to a local registry (which can be a ephemeral container without persistent storage), and then makes sure that docker-compose only uses these verified and locally stored images. The tool requires prefixing each image name with an environment variable so that the magic can be injected.

**Comment by ddelange** [comment]
> Content trust is implemented client-side in the Docker CLI. Since `docker-compose` is an entirely different code-base, we do not have a matching implementation of that feature at this time.
> 
> For the time being, you might want to pull images using the `docker` CLI before running `docker-compose up`.

@shin- is there a specific reasoning behind skipping this essential feature in compose? Who can we tag here for a second opinion? :)

As for your suggestion, grepping the docker image tags from the `docker-compose.yml` before each `up` seems a bit cumbersome, but I guess the best alternative without resorting to 3rd party software.

> The tool requires prefixing each image name with an environment variable so that the magic can be injected.

@peterthomassen could you elaborate on this reasoning?

**Comment by peterthomassen** [comment]
@ddelange As explained in the [previous post](https://github.com/docker/compose/issues/4787#issuecomment-573129692), trusted-compose is a wrapper around docker-compose; it pulls images, verifies signatures, and pushes them to a local registry. It then has to make sure that docker-compose will only used the verified images from the local registry. That's what the env variable prefix is needed for.

The reason for this approach is so that certain race conditions can be avoided. For details, see [this article on trusted-compose](https://medium.com/sse-blog/bringing-content-trust-into-the-world-of-docker-compose-12836b3537d).

**Comment by ndeloof** [comment]
> Content trust is implemented client-side in the Docker CLI

With [Compose v2](http://github.com/docker/compose-cli) implemented in Go as a CLI plugin, it seems to me we could introduce support for content-trust in `docker compose`

**Comment by skrutzler** [comment]
> > Content trust is implemented client-side in the Docker CLI
> 
> With [Compose v2](https://github.com/docker/compose-cli) implemented in Go as a CLI plugin, it seems to me we could introduce support for content-trust in `docker compose`

what is the current status? Are there any plans in the near future to work on that?
