### ISSUE TITLE
Sometimes appear strange container names as /shacode_shacode_shacode_containername

### ISSUE THREAD

**Issue by cesarjorgemartinez** [docker/compose#4834]
Hi,

I'm using docker-compose v11.1, and sometimes when try to start the containers, some container fail to start:
Recreating shacode_shacode_containername (two shacode)
And no such image
My container always named containername
I do not know how to reproduce it

Doing a docker inspect shacode_shacode_shacode_containername get:
"Name": "/shacode_shacode_shacode_containername",

The shacode is the same always
"Name": "/2c457ba8998f_2c457ba8998f_2c457ba8998f_containername",

My docker compose has the definition
containername:
  container_name: containername
  hostname: containername

I'm using algo docker 17.03

What could be happening?

**Comment by shin-** [comment]
When recreating a container (either because its configuration changed, or because `--force-recreate` was used), the previous container is renamed to a temporary name `<container_id>_<container_name>`. If the new container can not be created (usually due to an error in config that can only be detected at runtime), the old container will be preserved with that temporary name so data can be retrieved / the app can be restarted. If recreation fails multiple times, the temporary prefix may be appended multiple times, like in your case.

**Comment by cesarjorgemartinez** [comment]
Exist any form to define something like "drop all containers in this state", in the up container process?

**Comment by shin-** [comment]
You can use `docker-compose rm` to remove all containers that are not currently running.
