### ISSUE TITLE
Publish Python 3 versions of binaries

### ISSUE THREAD

**Issue by veqryn** [docker/compose#5063]
Can you please publish the binaries with Python 3 embedded somewhere?
I realize they are still in a bit of beta, so they could be marked as beta or put behind a link, or under some nightly/unstable builds area, or something.
I'm running into an issue with encodings that python 3 solves: https://github.com/docker/compose/issues/2775
Side benefit would be more people looking at and reporting any issues with the python 3 versions.

**Comment by shin-** [comment]
As far as I remember, the reason we haven't switched to shipping Python 3 binaries is that it doesn't work (or at least, it didn't last time we tried). I'll have to dig a bit and see what were the reasons for that.

It's still something I want to do (especially because it would fix a lot of encoding issues as you note),
