### ISSUE TITLE
container naming conflict on identical project folder names (in multi user enviroments)

### ISSUE THREAD

**Issue by smoebody** [docker/compose#5104]
I have an issue with the container-naming in docker-compose. We have a multi-user scenario where multiple developers are working on one docker-enabled host, each of them in their own home-dir, on their own clone (branch) of the project. The developers are using a docker-container to test their implementation.
The problem is that - as long as they do not clone the project to different folder-names - the container names are identical and therefore conflicting each other. It would be nice if the container-name would be hashed from the absolute filesystem path or a prefix could be defined.

Any suggestion how to circumvent this issue?

**Comment by shin-** [comment]
- [`COMPOSE_PROJECT_NAME`](https://docs.docker.com/compose/reference/envvars/#compose_project_name)
- [`-p` flag](https://docs.docker.com/compose/reference/overview/#use--p-to-specify-a-project-name)

**Comment by Ryanf55** [comment]
What should we use when using worktrees, or multiple users on the same server?

**Comment by your-diary** [comment]
I'm having this issue:

1. I run `docker compose up` in `/path/to/1/foo`

2. Then I run `docker compose up --remove-orphans` in `/path/to/2/foo`, where the two directories (projects) are completely independent and share the same directory name `foo` by coincidence.

3. Then the first `docker compose up` is detected as an orphan and terminated.

`-p` works, but I believe treating two projects as equal just because the last components of their directory names match is not reasonable.
