### ISSUE TITLE
build from git doesn't use /etc/hosts for name resolving

### ISSUE THREAD

**Issue by PascalTurbo** [docker/compose#5174]
I've got an internal server which I can't access by dns, so I've created an entry in /etc/hosts.

```
# /etc/hosts
192.168.4.2 internal.server.name
```

When executing `docker build http://internal.server.name/git/my_repo.git#FEATURE/name` everything works fine.

But when adding `build: http://internal.server.name/git/my_repo.git#FEATURE/name` to my docker-compose.yml it ends up with

```
ERROR: error fetching: fatal: unable to access ' http://internal.server.name/git/my_repo.git/': Could not resolve host: internal.server.name
: exit status 128
```

**Comment by shin-** [comment]
Compose behaves differently from the CLI. It sends git URLs directly to the Docker engine and lets it clone the repo itself. That means configuration on the client (like git credentials or etc/hosts entries) will not be taken into account.

Because this is a fringe use case that requires a lot of work to get right, we don't currently have any plans to emulate the CLI's behavior.

HTH.
