### ISSUE TITLE
Parallel execution of docker-compose run fails to start some containers

### ISSUE THREAD

**Issue by carbolymer** [docker/compose#5179]
When running multiple instances of service using `docker-compose run` in parallel, some containers fail to start started with an error:
> ERROR: No such container: ebe351e9f48acc1cb4c58f16df3487294c0f7ee5e7632f846974e9197f864bdd

The repository with sample `docker-compose.yml` and reproduction steps is here: https://github.com/carbolymer/docker-compose-run-parallel-failure

## Steps to reproduce
1. Clone the repository mentioned above
1. Start rsyslog service

    ```
    docker-compose up -d rsyslog
    ```

2. Start stress test
    ```
    ./run.sh
    ```

3. Observe multiple error messages in the terminal. If the error messages are not present, try to increase I/O parameter of the `stress` application in `docker-compose.yml`.
File `example_run.log` contains example log from execution of `run.sh` where only 14 containers of 20 were started.

## Software & hardware parameters
* Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (4 cores / 8 threads)
* 24 GB RAM
* Kernel: 4.12.8-2-ARCH
* OS: Archlinux
* Docker version 1:17.07.0-1
* Docker compose version: 1.15.0-1

**Comment by carbolymer** [comment]
I've found that this could be related with the container creation time:
https://github.com/moby/moby/issues/26452#issuecomment-246750980

Other similar issue:
https://github.com/moby/moby/issues/1319

Any ideas for workaround  / fix?

**Comment by arturgspb** [comment]
@carbolymer, I have the same. Did you find something to solve the problem?

**Comment by carbolymer** [comment]
@arturgspb Unfortunately not. AFAIR I was trying to use `sleep` or `docker-compose pause` but that was not 100% reliable workaround - still some containers were not started.

**Comment by brainlock** [comment]
I'm hitting the same problem, and did some digging.

My use case is running (concurrently, in Jenkins parallel() blocks) multiple
one-off instances of the same docker-compose service to perform different
checks against the rest of the system.

The problem can be reduced to the following simple repro:

```
albe@myo /tmp/repro % cat docker-compose.yml
version: "3"
services:
  main:
    image: busybox
albe@myo /tmp/repro % cat repro.sh
#!/bin/bash

docker-compose up main

declare -a pids

for n in `seq 20`; do
  docker-compose run --name "main-$n" main true &
  pids+=( $! )
done

for pid in $pids; do wait $pid; done

docker-compose down -t 1
albe@myo /tmp/repro % ./repro.sh
Creating network "repro_default" with the default driver
Creating repro_main_1 ... done
Attaching to repro_main_1
repro_main_1 exited with code 0
ERROR: No such container: 9f986c2b11308d3e0223be7b92578620e7e95e2b486753591f9b0ed60b3c64fa
ERROR: No such container: 11d2dc4107962b7cc787e133179783b5e0bfd74e3be723ed537875a78a9966d0
ERROR: No such container: 11d2dc4107962b7cc787e133179783b5e0bfd74e3be723ed537875a78a9966d0
ERROR: No such container: b0bde0fa0ec084d5684d0e5236a0ca2fb8f101239d65f04060a6621044d4c524
ERROR: No such container: 13e647f7153a22d7702680acc61ad5f23ba4585ae2bb58eb79dfec0a5d25c32d
ERROR: No such container: 13e647f7153a22d7702680acc61ad5f23ba4585ae2bb58eb79dfec0a5d25c32d
ERROR: No such container: 13e647f7153a22d7702680acc61ad5f23ba4585ae2bb58eb79dfec0a5d25c32d
ERROR: No such container: fd8a9ce92a2d08bde09e7a28612c3a06a16a263ba0999a4e78a6af84a2b61b2d
ERROR: No such container: 66cb9684faf94fba3faac9dc2e20a1b1047e738de83ce6315b5f41adb912de78
ERROR: No such container: 66cb9684faf94fba3faac9dc2e20a1b1047e738de83ce6315b5f41adb912de78
Stopping main-9  ... done
Stopping main-10 ... done
Stopping main-7  ... done
Removing main-9       ... done
Removing main-10      ... done
Removing main-3       ... done
Removing main-7       ... done
Removing main-2       ... done
Removing main-4       ... done
Removing main-5       ... done
Removing main-6       ... done
Removing main-1       ... done
Removing repro_main_1 ... done
Removing network repro_default
ERROR: network repro_default id d1170738cc542ed1d86f6891c4c7a090d2893ff66fc0c99ce323e4d4bb6741df has active endpoints
albe@myo /tmp/repro %
```

The containers have a unique name (`--name "main-$n"`).

Adding more logging into the mix, I can see that one of the concurrent invocations creates
a container (different IDs from another run, bear with me :-) ):

```
logs-6
54:compose.cli.verbose_proxy.proxy_callable: docker create_container -> {'Id': '10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c',
56:compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c')
57:urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c/json HTTP/1.1" 200 None
69:compose.cli.verbose_proxy.proxy_callable: docker disconnect_container_from_network <- ('10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c', 'repro1234_default')
72:compose.cli.verbose_proxy.proxy_callable: docker connect_container_to_network <- ('10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c', 'repro1234_default', aliases=[], ipv4_address=None, ipv6_address=None, links=[], link_local_ips=None)
75:compose.cli.main.call_docker: /usr/local/bin/docker start --attach --interactive 10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c
```

however, this container is also seen by other concurrent invocations:

```
% cat logs-12
[…]
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=repro1234', 'com.docker.compose.service=main', 'com.docker.compose.oneoff=True']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Drepro1234%22%2C+%22com.docker.compose.service%3Dmain%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D HTTP/1.1" 200 1168
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 2 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c/json HTTP/1.1" 404 98
compose.cli.errors.log_api_error: No such container: 10b22cd6391d865c4dacb2960568b01df25d0603c9b8367b5e23bb4fe0a0450c
```

The problem seems to be that docker-compose fetches a list of containers by
`filters={'label': ['com.docker.compose.project=repro1234', 'com.docker.compose.service=main', 'com.docker.compose.oneoff=True']}`, and this also returns one-off containers
that are actually managed by other invocations of `docker-compose run`.

Trying to inspect one of those containers when it's already terminated results
in a 404 and the "no such container" error.


I'm running this on the latest Docker for Mac + latest docker-compose `master`
(currently at `867ad1550beb48a1bff052086958f0ba644f8e4b`), the above repro.sh
behaves the same on my CI machine (`debian stretch`,
`Docker version 17.12.0-ce, build c97c6d6`,
`docker-compose version 1.18.0, build 8dd22a9`).


What do you think? Is my use case (multiple concurrent instances of the same compose service)
completely off and unsupported? Is my analysis wrong?

I'm quite new to docker and docker-compose, but I could try and get this to
work, if you think it's a use case worth supporting and can point me in the right direction.


And thanks for the fantastic tool, docker-compose is a huge help for me
in testing a complex legacy system! :-)
