### ISSUE TITLE
Confusing and undocumented cpu* parameters

### ISSUE THREAD

**Issue by asarkar** [docker/compose#5509]
According to the [doc](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources), the following parameters were added in v2.2. The corresponding PR appears to be https://github.com/docker/compose/pull/4835

However, I couldn't find any explanation whatsoever of what these parameters do. Doc says:
> analogous to its docker run counterpart

But, [docker run](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources) doesn't have these parameters. Neither does [this](https://docs.docker.com/engine/admin/resource_constraints/#cpu).

So I'm looking at `cpu_count: 2` and wondering how in the world is it different from `cpus: 2`. What does the word `cpu_count` mean to anyone who speaks English? Two counts of cpu. Well, that's exactly what `cpus` is supposed to be.

Can we stop this guessing game and clearly document the parameters?

**Comment by shin-** [comment]
Sorry for the confusion! Here is the relevant documentation page: https://docs.docker.com/edge/engine/reference/commandline/run/#options

As you can see, `--cpu-count` and `--cpu-percent` are Windows-only options that let the user control the CPU allocation of Windows containers. Combined together they're analogous (though not equivalent, due to underlying system differences) to the UNIX flag `--cpus`.

Feel free to open an issue on the [docs repo](https://github.com/docker/docker.github.io/issues) if you have suggestions on how to improve these pages!

**Comment by asarkar** [comment]
Thanks, moved to https://github.com/docker/docker.github.io/issues/5622
