### ISSUE TITLE
Validation / lint by version

### ISSUE THREAD

**Issue by ronaldpetty** [docker/compose#5511]
Docker 17.09
Compose 1.8
Host Ubuntu 16.04

Hi,

Is there a tool that anyone is aware of that takes a compose file and does the following?

* Is it validate?
* What is the minimum supported Composer and Docker for this version of the file?
* What is the maximum supported Composer and Docker for this version of the file?
* Show what is right for a given error message.

Ex.  Using dc 1.8 this seems invalid:

version: "2.1"
and
version: "3"

but

version: "2" worked.  However the particular error didn't give a pointer to the version matrix or the regex that would work (in fact, I didn't find a reason why 3 wouldn't work).

It is getting a little challenging to remember what is valid and what is not between versions.

Ideally Compose would be able to do this, but an external tool is great as well.  If no one knows of one (I could not find one) maybe I can do it.

Happy new year!

Ron

**Comment by shin-** [comment]
Hi Ron,

Is there a specific reason you're still using Compose 1.8? It's 18 months old, which is an eternity in "Docker years". You're missing out on a lot of features, improvements and bug fixes.

To partially answer your question - `docker-compose config` will validate a Compose file assuming it's a version that instance of Compose supports. 
The reason there's not a chart of "Which version of Compose supports what" is because we're concerned it would imply we somewhat support older versions in some configurations, whereas we make no such guarantee. The information is technically available if you dig through the releases page though: https://github.com/docker/compose/releases

**Comment by ronaldpetty** [comment]
@shin thanks, yes its old, but did make me think about upgrading.  I can understand not implying support, but I would imagine a more direct way of that is a table/tool stating as much (remove magic).  To that point. I specifically asked due to the fact the release info doesn't say it explicitly (at least I couldn't find it).

I suppose it is just my thoughts so maybe close, just throwing it out there.  Thanks again for the feedback.
