### ISSUE TITLE
Execute a command on host everytime a container restarts

### ISSUE THREAD

**Issue by pikaille** [docker/compose#5731]
I have a container acting as a reverse proxy which forwards to other containers that are hosting websites.

**One of the hosting container needs to know the ip of proxy.** 

When ever docker starts the proxy container, I would like to run a script on the docker host machine, that would in turn setup the website hosting container with the proper ip. Can this be done, and is it a usual way of doing things? 

For more details :

- I use an nginx reverse proxy in combination with nextcloud. 
- I need to set the `trusted_proxies` parameter on nextcloud which requires an IP. 
- I start nginx last so that I can setup my upstream values using the container names:

```
upstream nextcloudserver {
    server nextcloud_server;
}
```

Cheers!

**Comment by shin-** [comment]
In the future, please direct this kind of question to the [forums](https://forums.docker.com).

If you absolutely need to use an IP address rather than a hostname, the best way to do so is to set a fixed IP on the network shared by these two containers. See [the docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address) for more details.

**Comment by pikaille** [comment]
Thanks for directing, somehow, ended up in freenode channel instead of the forums.
