### ISSUE TITLE
Add an option to the YAML file to specify an alternative signal to stop containers

### ISSUE THREAD

**Issue by GaretJax** [docker/compose#576]
It would be great if we could specify a signal number in the `fig.yml` file. Fig would then use it with `docker kill -s SIGNAL` instead of `docker stop` when stopping a container.

**Comment by brianclements** [comment]
Definitely +1. The trend is more and more toward complicatedly intertwined and heterogeneous clusters of containers consisting of many different apps, but that all must operate harmoniously as a single service. I think this feature is extremely important to ensuring this.

The implications too are not just for docker-compose, but also because the docker-compose yaml syntax is becoming the standard for other orchestration platforms such as Rancher and this would be a good habit to enforce in the yaml files all around.

**Comment by deminoth** [comment]
+1

**Comment by thaJeztah** [comment]
I think this is currently worked on in Docker, see this pull request; https://github.com/docker/docker/pull/15307

**Comment by dnephin** [comment]
The cli now supports `-s` http://docs.docker.com/compose/reference/kill/

I don't think it makes sense to add an option to the yaml config. Containers should respond to signals in an expected way. There's no good reason to send anything besides `SIGTERM` to stop a container.

**Comment by thaJeztah** [comment]
> There's no good reason to send anything besides SIGTERM to stop a container.

Docker *will* be adding this though, see https://github.com/docker/docker/pull/15307. IIRC, this came up a few times, because some packages/services didn't work well with `SIGTERM`

**Comment by aanand** [comment]
Interesting, I can see the argument for it. I guess we should implement `stop_signal` then.

**Comment by thaJeztah** [comment]
FYI, docker https://github.com/docker/docker/pull/15307 was just merged, so this will be in the Docker 1.9 release.
