### ISSUE TITLE
Losing stdout and stderr after a minute

### ISSUE THREAD

**Issue by dickmao** [docker/compose#5972]
## Description of the issue
`docker-compose up` in container ([jpetazzo/pseudo-dind](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)) loses stdout if nothing is printed for a minute.  Proposed labels: `compose-in-a-container` `kind/bug`

## Context information (for bug reports)

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

## Steps to reproduce the issue

1. 
```
cat > Dockerfile -<<EOF
FROM bash
ENTRYPOINT [ "sh", "-c", "echo 1; sleep 63; echo 2" ]
EOF
```

2. 
```
docker build -t foo .
```

3. 
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -ti alpine:latest
```

4. The following commands occur within the alpine image
```
apk --update add py-pip && pip install docker-compose
cat > docker-compose.yml -<<EOF
version: "2"
services:
   foo:
     image: "foo"
EOF
docker-compose up 
```

### Observed result
```
foo_1  | 1
default_foo_1 exited with code 0
```

### Expected result
```
foo_1  | 1
foo_1  | 2
default_foo_1 exited with code 0
```

The expected result can be achieved by sleeping for less than 60 seconds in step 1, or by `pip3 install  docker-compose` (instead of plain `pip`) in step 4 thereby getting a CPython version that is 3.x.

**Comment by shin-** [comment]
Thanks for the report!

As far as I can tell from my tests, this issue only occurs with Python 2. Using Python 3.6 will yield the expected result.

Given that
- The cause of this issue is probably in one of our dependencies, or possibly in Python itself
- The binary we distribute is now compiled using Python 3
- [Python 2 is getting deprecated in the near future](https://pythonclock.org/)

We will not spend any additional effort tracking down this bug. Please install Compose in a Python 3 environment instead.
