### ISSUE TITLE
New "fig.yml" key: 'run' ?

### ISSUE THREAD

**Issue by mcbhenwood** [docker/compose#600]
It would be great to have an ability to specify Dockerfile-like "RUN" steps, just for the Fig container. My specific situation is this:
My Dockerfile for my Django-based service installs basic service dependencies. However in my Fig container where I run tests and also run the dev server, I would want also to install test dependencies, which should never be built into the Docker container itself, rather as a layer on top for the Fig user.

I have tried a few shell-based ways of doing this but they are all dirty. The beauty of Fig is the way it applies a "thin override" to Dockerfile settings, in a slightly altered container. It seems to me that being able to RUN commands as well, as part of the Fig build, would be a good addition.

**Comment by dnephin** [comment]
This is not possible with the current docker remote API. There are plans to extract the build process from the API and do it client side, which would make this support even less likely.

In the end, compose is not really a build tool (#1455).

Since this feature is not possible, and it looks like the docker engine is moving in a different direction, I'm going to close this issue, but as always thank you for the proposal!
