### ISSUE TITLE
dns configuration option does not work on docker-compose

### ISSUE THREAD

**Issue by dwebber** [docker/compose#6031]
Same issue that is referenced in https://github.com/docker/compose/issues/2847 which has been in existence for over 2 years.

docker-compose version 1.16.1, build 6d1ac21
Server Version: 17.09.0-ce

**Comment by shin-** [comment]
Not a Compose issue. Please don't open duplicates intentionally.

Also, your software is outdated.

**Comment by jrichard8** [comment]
If its not a Docker compose why DNS work with a docker run command and not with docker-compose ?

**Comment by shin-** [comment]
> If its not a Docker compose why DNS work with a docker run command and not with docker-compose ?

If you see a bug please make a proper report. FYI, @thaJeztah did a fairly deep dive on how DNS info works with custom networks [here](https://github.com/docker/compose/issues/5991). Two issues have been identified, one of them has been fixed in the engine in 18.03.1, while the other one is still pending (see https://github.com/moby/moby/issues/20494#issuecomment-392759632). Still, neither of these are Compose issues.
