### ISSUE TITLE
Proposal: `fig run` should default to running the one and only service in the `fig.yml`

### ISSUE THREAD

**Issue by SvenDowideit** [docker/compose#605]
or perhaps the first service even?

I'm playing with fig to replace my use of Makefiles for experiments - expecially using the official `onbuild` images, where even a Dockerfile could be almost optional (just needs `FROM golang::onbuild`

initially, there will only be one service, so thats 'easy', but if I can specify the default service to run that would rock.

Thinking about it - It would be even better to specify in the fig.yml that this is an interactive service, requiring a tty, and for `fig up` to be just as magical then :)

> *Note:* `fig run` is not really 'just to run a one-off command in a service (for that, we should presumably now use `docker exec` - its necessary to run an interactive service too - and its possible that this interactive UI interacts with other services.

**Comment by dnephin** [comment]
Thanks for the feature idea!

We've seen a lot of requests for features that try to use Compose as a build tool like make. On the surface it seems like it would work, but it's really not designed for that workflow.  I think trying to change it to fit that workflow is going to make it a lot more confusing for the existing use cases, so it's probably better suited in a different tool.

I've prototyped one idea of what that might look like in https://github.com/dnephin/dobi

Going to close this issue since it doesn't fit with the current Compose use cases.
