### ISSUE TITLE
Avoiding build or image constraint

### ISSUE THREAD

**Issue by koen-serry** [docker/compose#627]
I was looking into the issue I just got regarding having both an image and a build inside my fig config, but I couldn't understand why this constraint exists.

__Service .... has both an image and build path specified. A service can either be built to image or use an existing image, not both.__

Because I may have both. If my image is not stale (ie. exactly the same as my Dockerfile) running from my image will be faster than rebuilding it. If however my image is stale (or I want to rebuild it just in case) I'd use __fig build__ . I agree that now we save a step when you do a fig up, because it actually builds the image, but it's also a bit confusing. Would it be possible to have some kind of fallback so in case the image is not there it builds it?

**Comment by chernjie** [comment]
[compose/service.py#L184:L187](https://github.com/docker/compose/blob/master/compose/service.py#L184:L187):

```python
        if (do_build and
                self.can_be_built() and
                not self.client.images(name=self.full_name)):
            self.build()
```

I too was hoping that this constraint is lifted. I have a private registry which causes the `image` name to be different from a build scenario, e.g. `localhost:5000/my/image` instead of `my/image`

It would be nice if docker compose first try the `image` and if not found then run `build`.

**Comment by dnephin** [comment]
Thanks for this proposal! let's continue the discussion in #2092
