### ISSUE TITLE
docker-compose init does not conform to documentation

### ISSUE THREAD

**Issue by phawxby** [docker/compose#6287]
## Description of the issue
https://docs.docker.com/compose/compose-file/#init
"Either set a boolean value to use the default init, **or specify a path to a custom one**."

Either the docs are wrong and custom paths aren't supported on init is not fully implemented. I'm guessing the latter?

```
# docker-compose.yml
version: '3.7'

services:
  web:
    image: alpine:latest
    init: /usr/libexec/docker-init
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Output of `docker version`**
```
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
```
docker-compose config
ERROR: The Compose file '.\docker-compose.yaml' is invalid because:
services.web.init contains an invalid type, it should be a boolean
```

**Comment by shin-** [comment]
Hi @phawxby !

That's actually a docs issue ; `init` only accepts boolean values in v3 files. This is due to the fact that `--init-path` was introduced in Docker 1.13.0 and later removed in 17.05.0 (see https://github.com/moby/moby/pull/32470). Since v3.7  (which introduced `init` to the v3 format) needs to be used with Docker 18.06.0 at minimum, there was no reason to implement support for this removed feature. The v2 format, on the other hand, still supports that syntax, though it is obviously considered obsolete.

What probably happened is the docs for the v3 format were copied over from the v2 docs and wasn't amended accordingly. Feel free to create an issue/PR on the [docs repo](https://github.com/docker/docker.github.io/) so we can fix it!
