### ISSUE TITLE
project.up method made the containner hang up

### ISSUE THREAD

**Issue by Nukker** [docker/compose#6395]
relation-link:  https://github.com/moby/moby/issues/38073

we found this bug(containner hang up) only happen in this method
**project.up(service_names=services, ignore_orphans=True)** 

we use `project.client.up(...)` is ok
we test hundreds `docker-compose -f compose_file_xxx.yml up -d`  in cmd is ok

**Comment by shin-** [comment]
Hi @Nukker 

We do not recommend using Compose's programmatic interface, as it is primarily designed as a CLI tool and should be used that way. That said, runtime issues like container hangups aren't generally a matter handled at the Compose level, so it's unlikely you'll find the cause here anyway.

I'll see if I can get someone to take another look at your issue on the moby/moby tracker.

**Comment by Nukker** [comment]
thank you @shin-
