### ISSUE TITLE
apt-get install docker-compose is way out of date

### ISSUE THREAD

**Issue by lukepighetti** [docker/compose#6471]
`apt-get install docker-compose` is installing v1.8 on Ubuntu 16.04. My experience with dev tools is that they are always up to date on the ubuntu repos. If this issue belongs somewhere else please help me understand where it belongs. Thanks!

**Comment by ulyssessouza** [comment]
Thank you for the report @lukepighetti !

AFAIC, we don't release any distribution specific package, and having a look at [Ubuntu packages](https://packages.ubuntu.com/xenial-updates/docker-compose) you can address it to the good channel.
But I think that your request will not be taken in consideration, since that means updating all it's dependencies too.

You can overcome this issue by using other ways of installation listed in https://docs.docker.com/compose/install/
