### ISSUE TITLE
Add support for docker --squash

### ISSUE THREAD

**Issue by kiorky** [docker/compose#6510]
Reopening of #4235, feel free to close and reopen the other.

**Is your feature request related to a problem? Please describe.**
squash is often needed to handle base image builds, see https://github.com/moby/moby/issues/38657 and the long list of --squash related bugs on moby tracker. A lot of us rely on it.

It would be nice to have a supported toggle in compose to enable the flag.

**Comment by mskoenz** [comment]
I mention my comment in #4235 here too, since this is an open issue. At least to my search, many propose to just use multistage builds to compensate for the lack of squash, but the issue is that it does not seem possible to inherit CMD/ENTRYPOINT/USER/WORKDIR from the parent image we are multistage-"squashing". A docker-compose --squash option would be extremely helpful to make e.g. gitlab CI pipelines more efficient since loading only a few layers seems to be faster due to less validation (and also the output is less cluttered with many hundered lines of docker pull output).
