### ISSUE TITLE
Performance improvements for run.sh

### ISSUE THREAD

**Issue by joakimr-axis** [docker/compose#6571]
run.sh contains some unnecessary statements that can be removed. For instance, a statement like

if [ -n "$foo" ]; then
   echo bar
fi

adds an extra check for the [ result that was already evaluated, and shell script best practice is then to write

[ -z "$foo" ] || echo bar

instead and save us from wasting some extra CPU cycles while decreasing the shell script footprint too.

Furthermore, there is no need to add quotes where not needed, and also not make external calls to external binaries like dirname (where the shell build-in string manipulation can do the job for us at a much lower cost).

I will add a pull request for this.

**Comment by ulyssessouza** [comment]
Hello @joakimr-axis, thank you for the interest in docker-compose!
My opinion is that the first block primes for readability which improves maintainability.
This conditional statements that you've mentioned are executed just once and are not CPU heavy, so the "optimization" is insignificant.

The focus of docker-compose is not on performance, but on readability, since it not a CPU intensive software.
