### ISSUE TITLE
Allow PyYAML >= 5

### ISSUE THREAD

**Issue by GeyseR** [docker/compose#6619]
The PyYAML team recently released version 5.1 of their lib to properly fix CVE-2017-18342 vulnerability. It would be great to add support for this version in docker-compose.

**Comment by ijc** [comment]
Thanks for the suggestion.

According to https://github.com/yaml/pyyaml/issues/265 there some incompatibilities, I'm not sure how much of that affect compose but more importantly I see also there is a suggestion to wait for 5.2 in that thread, due to some known issues with 5.1. I think we probably ought to wait for that (although a PR which contained a convincing rationale as to why compose is not affected might also be acceptable).

**Comment by rca** [comment]
Because docker-compose is a project dependency in one of my repo's, I have these alerts on the repo.  I'm not suggesting these should be _the_ reasons to upgrade, but it is a little concerning that an update is being dragged.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/53537/56687475-5d730700-66a4-11e9-9c37-748021ed9df9.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/53537/56687436-492f0a00-66a4-11e9-8040-310ad32738e5.png">

**Comment by GeyseR** [comment]
I think the issue is still actual

**Comment by rca** [comment]
Yes, still a problem.

**Comment by jdyer09** [comment]
One of my builds has downstream dependencies on this and is completely hosed, what's going on here?

**Comment by dorpvom** [comment]
This is also interesting since Kali comes pre installed with PyYAML 5.1.2 through dist utils and a dozen packages depending on it. This makes using docker-compose on Kali a bit tricky.

**Comment by rca** [comment]
Even worse is that the community has deemed the PyYAML version docker-compose points to a security risk and, many months in, Docker has done nothing about it.  :(

**Comment by gangadhar01a** [comment]
Is there any update on this?
