### ISSUE TITLE
Docker Compose release notes out-of-date

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#6620]
The [Docker Compose release notes page](https://docs.docker.com/release-notes/docker-compose/) on the official Docker website is out-of-date. It's missing both a patch release (1.23.2) and the latest major release (1.24.0). Should I subscribe to the [GitHub releases page](https://github.com/docker/compose/releases), instead?

**Comment by ijc** [comment]
Thanks for the report. The update is in flight at https://github.com/docker/docker.github.io/pull/8544 ,which is merged but not live it seems. I trust everything is moving along and it'll appear before long so I'm going to close rather than forget to do it later. If it hasn't updated in a day or two please do ping!

**Comment by AnthonyMastrean** [comment]
Are you going to pickup the release notes for 1.23.2, too? I don't see any [relevant issues](https://github.com/docker/docker.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+1.23.2). There's some hubbub around 1.24.0 (https://github.com/docker/compose/issues/6617) that I think will keep a lot of people on 1.23 and it would be nice to get the latest release notes up, too.

**Comment by AnthonyMastrean** [comment]
Am I interpreting your issue on docker.github.io correctly that this is a manual process? If that's so, then I think I'll just subscribe to the GitHub release notes directly 😢
