### ISSUE TITLE
`docker-compose build` Error message needs improvement: "[thing] uses an image, skipping"

### ISSUE THREAD

**Issue by nhooey** [docker/compose#6633]
**Is your feature request related to a problem? Please describe.**
When I run:
```
docker-compose build
```
I get this error:
```
thing1 uses an image, skipping
thing2 uses an image, skipping
...
```

**Describe the solution you'd like**
The error message should be more informative and suggest what to do.

**Describe alternatives you've considered**
None.

**Comment by alubbock** [comment]
This message is not really an error, it's informing you that `thing1` and `thing2` use images and are therefore pre-built, so they're skipped by the `build` command.

> The error message should be more informative...

Other than making the message more verbose by adding something like "no build necessary", I'm not sure what could be changed. Do you have a suggestion?

> ...and suggest what to do

These messages are just informational and don't require any special action by the user. The user can usually just continue on with `docker-compose up`, or whatever the next part of their workflow is.

**Comment by devuxer** [comment]
@alubbock,

I came to this issue because I was trying to figure out how to get docker to download the latest images. My docker-compose.yml has `image: name_of_image:latest`, but when I run `docker-compose build --pull`, I get "name_of_image uses an image, skipping". Maybe this makes sense to others, but I agree with the OP that this is an incomplete warning message and doesn't answer the most obvious question: "Why isn't it pulling the latest image and how do I get it to?"

Incidentally, after scouring the docs and some trial and error, I discovered that `docker-compose pull` (when not used in conjunction with `docker-compose build`) does what I want. So, besides being confused by the warning, I'm also confused what `--pull` actually does.

**Comment by skavadias** [comment]
Sorry to comment on a closed issue. In my opinion, the message would be clearer if it was something like:

`thing1: latest image found; nothing to build (no Dockerfile)`
`thing2: latest image found; nothing to build (no Dockerfile)`

Thank you.
