### ISSUE TITLE
ABOUT VERSION

### ISSUE THREAD

**Issue by xytnba** [docker/compose#6662]
Could anyone told me why I install the version is 1.8.0 ? 
OS：Debian 9 X64
I  got this by using  `apt install docker-compose` and the same ,`pip install docker-compose` 
I considered if my python version is too low ,it is 2.7.13 ,
   Thanks a lot for replying me！

**Comment by ulyssessouza** [comment]
Hello @xytnba, for the first you should do a `apt update` just to be sure you are using the last version of the index. But anyways, that depends on your distro version. For Debian it looks accurate https://packages.debian.org/search?searchon=names&keywords=docker-compose

Since the distribution packages are not maintained by the project we cannot help with that, since that would be an insane amount of work to manage for each distro.

For the second, it looks like your `pip` is not up to date. Have you tried `pip install --upgrade pip` before installing?

Please, have a look at the documentation on official ways to install `docker-compose` at https://docs.docker.com/compose/install/
