### ISSUE TITLE
Dockerfile: Group some RUN and COPY commands to decrease amount of layers

### ISSUE THREAD

**Issue by joakimr-axis** [docker/compose#6663]
Some RUN and COPY commands in the Dockerfile could be grouped in order to decrease the amount of layers used.

**Comment by ulyssessouza** [comment]
In commit https://github.com/docker/compose/commit/c217bab7f6123de80dbd55c99c2254666d766fb3 the optimization is for buildkit caching, taking in account the usage rate of files to influence in the cache invalidation. That's why we have some individual files been copied, a RUN and the final copy, which is the global copy.

This just makes sense when we have the build cache in mind.
