### ISSUE TITLE
Restarting Unhealthy Containers

### ISSUE THREAD

**Issue by lig** [docker/compose#6669]
There was this one about 2 years ago on that topic https://github.com/docker/compose/issues/4826

It looks like Docker Compose is pointing to Docker and Docker is pointing to orchestration tools.

Is it possible to have restart policy to depend on health status? It looks like the job for Docker Compose for me.

Also, it was there for version 2 compose files in `depends_on` section.

**Comment by InsOpDe** [comment]
Please open again as it is still relevant

**Comment by th3mis** [comment]
When it will be able to?

**Comment by PhilippHomann** [comment]
Imho there is no way to do this in compose, because compose is not running during runtime of a container or services (except you omit `-d` on up).
To monitor the health state of a container and do actions on change you need to have a daemon.
Implementing those actions into docker daemon looks much smarter to me.

**Comment by t3chn0m4g3** [comment]
Dirty, but works fine if `docker-compose` uses `restart=always`:
```
STOPSIGNAL SIGINT
HEALTHCHECK CMD if [ $(ps -C mpv -p 1 -o %cpu | tail -n 1 | cut -f 1 -d ".") -gt 99 ]; then kill -2 1; else exit 0; fi
```

- `-p 1` Monitors PID 1 only and kills process if process CPU usage is > 99%.
