### ISSUE TITLE
Container all timed out

### ISSUE THREAD

**Issue by zxf969175364** [docker/compose#6752]
![image](https://user-images.githubusercontent.com/12622610/59546982-98d5d780-8f69-11e9-8030-f5919b7e5aff.png)

![image](https://user-images.githubusercontent.com/12622610/59546995-e18d9080-8f69-11e9-9d89-472ecf071549.png)

![image](https://user-images.githubusercontent.com/12622610/59546997-e6524480-8f69-11e9-9b3b-30671f90667f.png)

![image](https://user-images.githubusercontent.com/12622610/59547040-cbcc9b00-8f6a-11e9-8dc7-e2d86d1e06ca.png)

![image](https://user-images.githubusercontent.com/12622610/59547043-da1ab700-8f6a-11e9-804b-9ebf61649be4.png)

I start docker every day after the company, and then start redis, mariadb, consul, but every docker container can not link successfully every half an hour or so including navicat chrome java program but docker ps found everything is normal,
Telnet localhost 3306 is also normal, even docker exec redis, but I did not find this problem when using docker at home, is it related to the company network, restarting once every half an hour, I am going to collapse

**Comment by chris-crone** [comment]
Hi @zxf969175364,

Thanks for reporting this issue. Can you please provide a simple reproduction for this issue?

Without being able to reproduce this, my hunch is that this is a Docker Desktop issue. Have you tried with an [edge release](https://docs.docker.com/docker-for-mac/edge-release-notes/) instead of the stable release?
