### ISSUE TITLE
Variable name may not contain whitespace

### ISSUE THREAD

**Issue by alfredopalhares** [docker/compose#6838]
## Description of the issue

Docker compose does not recnognize a valid yaml file, even when validated with a yamlint.org. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
-> % docker-compose version
docker-compose version 1.24.1, build unknown
docker-py version: 4.0.2
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: In file /home/masterkorp/Documents/prozis/repos/prozis-events/events-backend/docker/env/its.yaml: environment variable name 'host: hostname' may not contains whitespace.

```

## Steps to reproduce the issue
Just tun any docker command
### Observed result
Docker compose fails to run
### Expected result
Should run

## Additional information

**OS** Arch Linux Updated, but it happens accroos all OS.

**Comment by ulyssessouza** [comment]
@alfredopalhares Could you please, provide the YAML file?

**Comment by tjb-wiley** [comment]
i experienced this same issue, and after spending most of the afternoon, it looks like like maybe something changed with the way docker-compose processes `.env` files. and the only reason i hit this is because i upgraded docker on my mac laptop from `docker for mac` to `docker desktop`.

# current behavior on macos
```sh
docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
```

With a `.env` file that looks like this:
```sh
cat .env
# POSTGRES
export POSTGRES_USER=foo
export POSTGRES_DB=secret
```

and a `docker-compose.yaml` that looks like this:
```sh
version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      -  ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTRES_USER:-appcat_dev}
      POSTGRES_DB: ${POSTGRES_DB:-appcat_dev}

[ ... ]
```

run any `docker-compose` command will result in this error:
```sh
docker-compose ps
ERROR: In file ./.env: environment variable name 'export POSTGRES_USER' may not contains whitespace.
```
If I remove the `export` from the .env file and re-run the above, everything works.

# Current behavior on Linux (ubuntu 19.0.4)
Running the same commands as above, with the same setup as above, the same command works as expected.

That said, the `docker.io` package on my ubuntu installation is `18.09.7`.

I should point out that I figured the above out in most part due to this blog post:
https://vsupalov.com/docker-arg-env-variable-guide/

**Comment by tjb-wiley** [comment]
Looks like this behavior changed with this commit:
https://github.com/docker/compose/commit/9d2508cf585261f0f7167df1dbfb363940ebe5c6

**Comment by Quintasan** [comment]
Can't we just have docker-compose treat lines beginning as normal lines? So
`export VAR=foo` behaves the same as `VAR=foo`?

**Comment by tjb-wiley** [comment]
Looks like this is a known issue, going back to Feb of this year:
https://github.com/docker/compose/issues/6511
