### ISSUE TITLE
Compose creates only one container if name of parent directory of compose file is same 

### ISSUE THREAD

**Issue by codeasashu** [docker/compose#6898]
## Description of the issue
I have the following folder structure:

```
├── project_a
│   └── docker
│       └── docker-compose.yml
└── project_b
    └── docker
        └── docker-compose.yml
```

as you can see, I have the same name for parent dir of docker-compose.yml (docker in this case).

Content of `docker-compose.yml` for both the folders is the same: 
```yml
version: '3'

services:
    app:
        image: alpine
        command: "/bin/sh -c \"while true; do echo hello world; sleep 1; done\""
```

I executed the command inside both the `project_a` and `project_b` directory:
```sh
docker-compose -f docker/docker-compose.yml up
```
which "ups" my app service.

## Observations
- `docker ps` outputs only one running container `docker_app_1` 
- I `Ctrl-C` the `app` service in `project_a`, which also sends SIGTERM to app service in `project_b`.
- Initially, I thought this has to do with the name `container_name`. Hence I added `container_name` to compose yml (project_a, project_b respectively), which didn't solve the issue.

**Temporary fix**: If I rename `docker` to `docker1` in any of the directories, it works as expected (i.e. SIGTERM doesn't go across all the containers and two containers are launched)

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```yml
services:
  app:
    command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
    image: alpine
version: '3.0'
```

## Steps to reproduce the issue

1. Create two directories. Create a subdirectory within them with the same name (eg. docker)
2. Write same compose file within the `docker` subdirectory. 
3. run `docker-compose -f subdir/docker-compose.yml up` from both the directories

### Observed result
- Only one container with the same name is launched (`subdirectory_servicename`)
- `Ctrl C` will kill the container

### Expected result
- Separate containers should be launched for both the directories.
- Killing one container should not affect the other one. S

## Additional information
OS: MacOS Mojave ver. 10.14.6

**Comment by sudeepk82** [comment]
I'm having the same issue right now. @codeasashu Do you have a solution for this??
If not, can we please reopen this ticket??

**Comment by laurazard** [comment]
Hiya @sudeepk82 (and @codeasashu). This is expected behavior, so I'll clarify what's going on and then lock the issue.

When you run a Compose command inside of a folder (such as `docker compose up`), unless you specify the project name (through the `-p` flag such as `compose -p myname up`, or through setting a top level `name: myname` attribute on your Compose file, or using the `COMPOSE_PROJECT_NAME` environment variable), Compose will derive your project name from the name of the folder you're running the command in. Since the name of those two folders is the same, and the service name in both Compose files is the same, Compose does not see fit to create another container/rebuild the current one.

You can solve this by running Compose with a `-p` flag to specify the project name, or use the environment var or update your Compose file to specify a project name, to prevent collisions.
