### ISSUE TITLE
ERROR: Duplicate mount points:

### ISSUE THREAD

**Issue by bhemeswararao** [docker/compose#6999]
Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

bp_network2$ ./start.sh 

# don't rewrite paths for Windows Git Bash users
export MSYS_NO_PATHCONV=1

docker-compose -f docker-compose.yml down
ERROR: Duplicate mount points: [/home/sowedane/HLPOC/bp_network2/crypto-config/peerOrganizations/org1.blockprovenance.net/ca:/etc/hyperledger/fabric-ca-server-config:rw, /home/sowedane/HLPOC/bp_network2/crypto-config/peerOrganizations/org2.blockprovenance.net/ca:/etc/hyperledger/fabric-ca-server-config:rw]

**Comment by jcsirot** [comment]
Hello @bhemeswararao 
If you have a question about docker Compose please add a post in the [Compose forum](https://forums.docker.com/c/open-source-projects/compose).
If you think you found a bug in Docker Compose and want to submit a report, could you please open a ticket with the provided bug report template.

**Comment by Salmandabbakuti** [comment]
@bhemeswararao did you able to figure out the issue??. The problem here is that, you're trying mount two different host paths(org1.provenance.net and org2.provenance)  to same directory of the container(etc/hyperledger/fabric-ca-server-config). It will never allow you do that. Make sure you mount paths to separate directory in compose file..
