### ISSUE TITLE
Docker-Compose - Multiple port mapping 

### ISSUE THREAD

**Issue by Pankajdtrainer** [docker/compose#7017]
Hi there, Greetings.  

I am using docker-compose on GCP and exposing two ports with same server port numbers(80).  
However, when I am exposing external ports, port conflict is happening.  Can you please advise how I can fix it?  Example for the images and ports mentioned below.
wordpress:
  image: wordpress
  ports:
    - 80:80

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - 80:80

However, qhen I run in Localhost, it works fine with different port numbers(e.g. 8282 & 8181)

wordpress:
  image: wordpress
  ports:
    - 8282:80

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - 8181:80

**Comment by rumpl** [comment]
Hi @Pankajdtrainer,

you cannot expose twice the same port on a machine, you need to expose different ports.

With your setup you can either:

* expose phpmyadmin on another port
* add a third service (nginx for example) what will serve as a proxy to the two services, you could for example setup http://HOST/ to proxy to your wordpress and http://HOST/phpmyadmin to proxy to yout phpmyadmin service

I am going to close this since it is not an issue, please use [our forum](https://forums.docker.com/) or stackoverflow to ask questions.

Cheers.

**Comment by Pankajdtrainer** [comment]
Can you please advise how can that be achieved? Sorry, new to this technology. 

add a third service (nginx for example) what will serve as a proxy to the two services, you could for example setup http://HOST/ to proxy to your wordpress and http://HOST/phpmyadmin to proxy to yout phpmyadmin service

**Comment by rumpl** [comment]
[This looks like a great post that explains how to do it](https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose)

I can't really go into details, this is not the place for this knind of things.

**Comment by Pankajdtrainer** [comment]
Sure.  Thanks!
