### ISSUE TITLE
Issue accessing ENV from linked container

### ISSUE THREAD

**Issue by dkirrane** [docker/compose#702]
Reproduce:
https://github.com/dkirrane/docker-env-issue

When I run fig up the parent container 'web' does not have access to the ENV variables of the linked child container 'db'

docker version 1.3.2
fig 1.0.0

Same issue does not occur when I run the containers directly with docker

**Comment by dreamcat4** [comment]
@dkirrane Perhaps I can try a shot at explaining this for you.

When you run on the command line with `docker run ….` it has a tty. So the CMD `bash` gets run in the linked container and keeps going, it does not exit.

However when you run `fig up`. Then the same CMD `bash` will exit immediately. It might be because there is no tty input, so bash realizes it has nothing to do and just exits. Or for some other reason. I cannot say for sure. Anyway the important thing to know is that from fig, many similar cmds like `bash`, `bash -c read`, `sh`, and even some standalone programs that wait for read() on stdin like `ed`, `bc` or `vi` seem to exit immediately. A bug in fig or not? I really can't be sure.

However one thing is for sure (at least in docker v1.4.1). If a container is currently in a stopped state, then docker does not show it up as a linked container in the other continer. Or on docker inspect. The container(s) specified by the `link` directive must be running in order to show up. In the other container's environment variables, in `docker inspect`, and in the /etc/hosts file.

Now. You can (if you wish), replace `bash` with `tail -f < /dev/null`. And that sort of thing really aught to keep the process blocking forever. However for some reason, it seems like the docker daemon keeps it open for a little while (longer than bash). But soon detects that nothing at all is happening in that process and probably for the sake of saving resources stops the container automatically anyway. Else I don't really know what is going on there.

Another way might be to do `CMD sleep inf` which is the same as saying `sleep for (uint64) -1 seconds`. So that isn't quite forever. Also `sleep inf` won't work on containers like `busy box` that don't have GNU core utils installed in them. The `debian` and `ubuntu` containers can take `sleep inf` however you might just try replacing CMD with `sleep -1` or some real db process (that persists and does not exit) instead.

If anyone else can clarify those bits and pieces which I am still unsure about, please do so!

We know that by default CMD <prog arg1 arg2 …> is wrapped in sh -c by default. But using a go array like 'c argv[]' and specifying `CMD ["prog", "arg1", "arg2" …]` does not invoke sh -c. Could that help here? Not just when CMD is specified in the Dockerfile, but also when the `command` directive is used to override that in fig.yml too.

And are these really bugs in fig, docker, in the both of them, or neither?

**Comment by dnephin** [comment]
Closing this issue since it's not actionable and there hasn't been any recent activity.
