### ISSUE TITLE
Proposal: rely on docker CLI

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#7078]
In a few circumstances, docker-compose demonstrates some problematic differences with the docker CLI, from slowness to actual bugs (typically: ssh URL support).

People end-up writing their own scripts as workarounds, see https://github.com/docker/compose/issues/4748#issuecomment-561438269

There's a few places docker-compose do _not_ rely on docker-py API client implementation, but just execute the plain docker CLI, to run interactive mode on Windows, or to benefit BuilKit for image builds (see compose.cli.main.call_docker).

We don't expect many users to have docker-compose installed but not the docker CLI, and having to maintain both docker Go client library and docker-py in perfect sync is a challenge.

This proposal is about introducing `COMPOSE_USE_CLI` environment variable, default to `false` as initial round, so that we can offer a plain CLI implementation of the most problematic commands (maybe all of them, long terms).

Side benefits is that this offers a simple way for people to check a reported issue is caused by some docker-py implementation glitches, or just a plain docker-compose bug.

**Comment by thaJeztah** [comment]
Thanks; this is matching my proposal for “native” build through the docker cli; see my comments on https://github.com/docker/compose/pull/6584#issuecomment-501680138, https://github.com/docker/compose/pull/6584#issuecomment-502099098 and https://github.com/docker/compose/pull/6584#issuecomment-513210065

Which (roughly) translates to;

1. Introduce an option (environment variable for now?) allowing users to opt-in on delegating functionality to the docker cli
2. Where applicable, mark the “python” equivalent as “frozen” (no new features, but continue fixing bugs)
3. Encourage people to opt-in, and collect feedback (catch side-effects that we didn't think about, or due to esoteric use-cases/situations "in the wild”)
4. After X release(s), make it the default
5. Allow users to opt-out (`FEATURE_ENV_VAR=0`)
6. (where applicable) work on improvements in other projects (docker cli, docker app) to gain native support for Compose files (improving the experience further).


Worth discussing:

- are environment variables the most convenient construct for this, or should we have other ways? (configuration file(s)? also a way to integrate with `docker context`?)
    - env-vars are convenient for "per shell" / "per session" opt-in/out and easy to implement, but don't integrate easily into `docker context`, nor is it easy to configure them through (e.g.) the Docker Desktop UI
- is a single environment variable ok, or should we have individual env-vars for separate features (allowing more granular "promotion" of features to default to using the cli)
    - currently, we have `COMPOSE_NATIVE_BUILDER=1` to use the cli for building


Related to the "collect feedback"; we should create an epic or tracking issue for each feature/functionality that we delegate to the CLI so that we can describe outstanding issues / roadmap, and make it easier to refer to feedback related to it.

**Comment by ndeloof** [comment]
I fully agree with your execution scenario, for a smooth transition

opt-in by environment variable seems a good option (docker CLI does already for experimental features, or buildkit support). We could in parallel consider improvements in the context management and Desktop integration to make this even simpler, including one click opt-in/out and per-context configuration.

I also considered option to have individual fine grained variables to opt-in/out per command, but I wonder this will just make configuration a terrible experience, and source for many more confusion. With a shorter release cycle, I expect we are able to provide fixes for reported issues, as we introduce CLI implementation for a command.

**Comment by philomory** [comment]
Personally, I'd really love to see the flag for this moved into the `docker-compose.yaml` file; either as an option under the `build` key for a service (my preferred solution), or maybe globally as a header comment similar to the `# syntax = docker/dockerfile:1.0-experimental` header in Dockerfiles.

**Comment by ndeloof** [comment]
Implemented for run and exec
