### ISSUE TITLE
can i legally use docker/docker-compose in a commercial, educational video?

### ISSUE THREAD

**Issue by codefather-labs** [docker/compose#7194]
can i legally use docker/docker-compose in a commercial, educational video?

**Comment by thaJeztah** [comment]
I think (but I'm not a lawyer) that should be fine; be sure to follow the trademark guidelines; https://www.docker.com/legal/trademark-guidelines (and check other documents in the "legal" section; https://www.docker.com/legal)

However, it may be good to send an e-mail to `legal<at>docker.com` with details (to double-check)

I'll close this issue here, because this doesn't directly relate to the code in this repository, but feel free to continue the conversation
