### ISSUE TITLE
Question: What is the proper way to run rootless dockerd?

### ISSUE THREAD

**Issue by Kreyren** [docker/compose#7244]
**Disclaimer:** The documentation is unclear for to handle this scenario and so i am asking here assuming that this is the only repo that i've found that accepts issues that is remotely relevant.

What is the proper way to implement rootless dockerd on a production system?

Ideally some kind of upstream maintained hardening checklist i.e https://github.com/trimstray/linux-hardening-checklist would be appreciated

Partially-blocks: https://github.com/gitpod-io/gitpod/issues/1251

**Comment by JOduMonT** [comment]
Being rootless is not really possible for Docker

but you could isolate is in the [userspace](https://docs.docker.com/engine/security/userns-remap/) with the userns option by declaring `"userns-remap": "dockremap"` in `/etc/docker/daemon.json`
then every docker image will run as a user instead of root. You will have to jiggle with the subuid and subgid such as you would do with LXC.

The common way to counter this is to run service inside each container as a user, such as you would do if you were running the server directly on the server (without docker)

A good example are by [linuxserver](https://github.com/linuxserver/docker-letsencrypt#docker) where the PUID and PGID are dynamic and you could change

[Here more explanation](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15)

**Comment by oleng** [comment]
Just a comment:
Some official docker maintainers uses `gosu` to make their app runs as non root, but for more relevant development on actual non-root containers AFAIK there's at least a few people actively working on this, one of them is Akihiro Suda, the author of the moby's Rootless mode, and the other is cyphar https://rootlesscontaine.rs/.

**Comment by JOduMonT** [comment]
@oleng in the slideshow (slide 8) they mention the option I suggested
![image](https://user-images.githubusercontent.com/5204724/75414700-02610f00-595c-11ea-8d00-b740040891fd.png)

**Comment by oleng** [comment]
Yeah, I was just pointing out some other possible venue/resources if you or Kreyren are interested on following the progress of efforts from non-root container engineers, and by the way I forgot to include Jess Frazelle... 
I'm a mere passer by here :)

**Comment by Kreyren** [comment]
Thanks for all the info which is appreciated, options are being investigated as we speak.

**Comment by flavienbwk** [comment]
Docker is now [available with a rootless version](https://docs.docker.com/engine/security/rootless/) !

**Comment by Kreyren** [comment]
cc @jankeromnes

**Comment by Kreyren** [comment]
@flavienbwk Could you make your article into an open-source security checklist alike https://github.com/trimstray/linux-hardening-checklist so that it can be community (and ideally upstream maintained) to ensure that production systems using docker are up to this standard?

**Comment by thaJeztah** [comment]
### Rootless mode

Running docker in rootless mode is still an "experimental" feature in Docker 19.03 (it requires the daemon to run in "experimental" mode); for the upcoming 20.x release, it's moved out of experimental, but still has some caveats / limitations (e.g. you can't install using `apt` or `yum`, but have to download a static package, in addition to the [known limitations](https://docs.docker.com/engine/security/rootless/#known-limitations); 

- no support for cgroups being the most prominent, which means you can't (e.g.) limit resources such as `memory` or `cpu` in the container.
- requires the host to be running Ubuntu or Debian 10 to support the overlay2 storage driver (otherwise only `vfs` can be used, which is very inefficient as each container will have a _full_ copy of the rootfs, which makes starting a container slow, and space-inefficient.

### User namespaces

Running with user namespaces (https://docs.docker.com/engine/security/userns-remap/) is another option (I see mentioned above), is another option, but comes with its own limitations / constraints (see [known limitations](https://docs.docker.com/engine/security/userns-remap/#user-namespace-known-limitations)). For example, if you want to use bind-mounts, then the files on the host must have their user/owner "remapped" to match the remapped user in the container. This is by design, because usernamespaces are to protect against a container obtaining access to files on the host.

Perhaps a page in the documentation outlining the pro's and con's for these options would be good to have; the documentation repository is open source, and can be found at https://github.com/docker/docker.github.io; contributions in this area are welcome if someone is interested.

**Comment by tin6150** [comment]
> Docker is now [available with a rootless version](https://docs.docker.com/engine/security/rootless/) !
> 
> Tho has many caveats including the fact you can't properly manage its networking parameters as it runs as any other software (no bridge network for example).
> 
> As it is run as **one daemon per user**, I decided to apply classic permissions rules for folders and to use iptables for managing the internet access : I have one user dedicated to its docker daemon. That way, I can use iptables to allow specific IP to reach the containers of **this** user.
> 
> [I've written an article about securing this version of Docker](https://medium.com/@flavienb/installing-and-securing-docker-rootless-for-production-use-8e358d1c0956).

So tootless docker need to be installed differently (by user instead of system apt/yum).  What about docker-compose?  That could still be installed via system's apt/yum, and it would invoke the user's PATH for rootless docker?

Thx!

**Comment by thaJeztah** [comment]
To install compose, you can follow the installation instruction in https://docs.docker.com/compose/install/. Docker currently doesn't have apt/yum packages for compose (but I know the Ubuntu package maintainers build a compose package); I think those compose packages should not _require_ `dockerd` to be installed (at most _recommend_), because docker-compose (like the docker cli itself) only need access to the `docker` API (which doesn't have to be on the same machine, and could just as well be a remote dockerd running in the cloud). It might be worth opening a ticket for that in your distro's issue tracker.

The reason for not using `apt` / `yum` to install the rootless package of docker, is that those commands perform a system-wide install of docker, so not for the _current user_, and as such require `root` permissions.

That said, it _should be_ possible to have a "regular" installation of docker, and _run_ it in rootless mode, but will require some additional steps  (tracking issue for that in https://github.com/moby/moby/issues/40761)

**Comment by AkihiroSuda** [comment]
The compose binary is available at https://github.com/docker/compose/releases/tag/1.26.0 and doesn't require root

**Comment by flavienbwk** [comment]
These stale bot and auto close are fully useless!!! Remove them!

**Comment by edvinkuric** [comment]
If still relevant: Docker introduced a new feature in Docker Engine v20.10 called "rootless mode", which allows to run the dockerd-daemon as a non-root user.

Check this link for more information, maybe it helps: https://docs.docker.com/engine/security/rootless/
