### ISSUE TITLE
The Dockerfile could not find the docker-compose volume file

### ISSUE THREAD

**Issue by jiangyanglinlan** [docker/compose#7314]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  pyweb:
    build:
      context: E:\dev\compose_demo
    ports:
    - 8000:5000/tcp
    volumes:
    - E:\dev\compose_demo:/code:rw
version: '3.0'
```

## Steps to reproduce the issue

This is a demo where I can reproduce the problem。I have 4 files in the same path：
1. app.py
``` python
# app.py
from flask import Flask


app = Flask(__name__)


@app.route('/')
def index():
    return 'Hello World'


if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```

2. requirements.txt
``` 
click==7.1.1
Flask==1.1.1
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
Werkzeug==1.0.0
```

3. docker-compose.yml
``` yml
version: '3'

services:
  pyweb:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
```
4. Dockerfile
``` docker
FROM ubuntu:18.04

RUN apt update
RUN apt -y install python3 python3-pip
RUN pip3 install -r /code/requirements.txt

WORKDIR /code

CMD ["python3", "app.py"]
```

5. run `docker-compose up`

### Observed result
`RUN pip3 install -r /code/requirements.txt` error

### Expected result
It should work

### Stacktrace / full error message

```
Could not open requirements file: [Errno 2] No such file or directory: '/code/requirements.txt'
Service 'pyweb' failed to build: The command '/bin/sh -c pip3 install -r /code/requirements.txt' returned a non-zero code: 1
```

## Additional information
OS: Windows and Linux

I found these files exist when I entered the docker container, and `pip 3 install -r /code/requirements.txt` was able to run successfully in the docker container.

**Comment by aar3** [comment]
Any updates here? 

Have spent the past 2 days trying to figure out whether I was crazy or whether or not this was an actual issue. 

Same exact thing with me on `Docker version 19.03.12, build 48a66213fe` and `docker-compose version 1.26.2, build eefe0d31` on OSX 10.15.6

`docker-compose` refuses to see the files mounted at the volume -- giving me a `container exited with status code 127 -- /bin/bash files not found`. 

However, if I `exec` into the container they are clearly there and work as expected. 

Is there any temporary workaround here?

**Comment by rmNyro** [comment]
Hi,

Still no update here ?

I'm having the same issue

command  `cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

command `docker-compose version`
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

command `docker version`
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

Example Dockerfile
```
FROM alpine

RUN ls /var/www
```
Example docker-compose.yml
```
version: "3.3"
services:
  test:
    build: .
    volumes:
      - .:/var/www
```
Command to build `docker-compose --file docker-compose.yml build`

The output is :
```
Building test
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
596ba82af5aa: Pull complete
Digest: sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378
Status: Downloaded newer image for alpine:latest
 ---> 7731472c3f2a
Step 2/2 : RUN ls /var/www
 ---> Running in 1bef6f5d866a
ls: /var/www: No such file or directory
ERROR: Service 'test' failed to build: The command '/bin/sh -c ls /var/www' returned a non-zero code: 1
```
Volume seems not mounted in the build process. It seems like it is the exact same issue as in march 2020, is this still a known bug? I've updated docker to latest version (20.10.2) but it doesn't seem to fix the issue.

If there is no fix, is there a workaround? @jiangyanglinlan and @aar3, did you manage to do what you wanted and if so did you find a workaround or something?

Thank you all in advance!

P.S.: Docker used to be my "way to go" but I must say that I'm lately having a hard time with it. I've had a problem with volume bind on windows and the issue never get a fix and never even get an answer... I entirely abandoned using docker on windows since but I know docker is not the perfect fit for windows so it bothered me but I accepted. I know that if I'll have similar problems on linux I'll stop using and recommending docker entirely (and try to switch to lxc)... Also the update procedure are more and more complex and are changing all the time. The doc is getting worse, I find that is has become hard to get info on command usage or at least it seems harder than 3 years ago and the "version" indication for docker-compose seems wrong in examples as when you try the command given they often do not work and you have to modify them based on the cli recommendation. Lastly the "root" issue has never really been addressed (now it's not even recommended at all) or never get a proper response (people on the internet write about their way of doing it but it is either wrong or just not safe) so in the end using docker on your computer is in most (if not all) case bad for security. Very disapointing...

**Comment by gwerbin** [comment]
I am having this problem as well.

I too would appreciate a workaround, if it's not something that can be fixed easily.

My system specs are:

```
$ docker-compose version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by gwerbin** [comment]
It'd be nice if we could get an official explanation on why this is the case. Is this simply not a supported feature? If so, close it as "wontfix". If it is a bug, letting the issue go stale seems like burying it, rather than resolving it.

**Comment by jsrobin888** [comment]
still having issue here, does not seems fixed
