### ISSUE TITLE
Docker daemon not available in docker/compose container

### ISSUE THREAD

**Issue by clement-igonet** [docker/compose#7351]
## Description of the issue
I can not launch docker-compose inside docker/compose container

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620
```

**Output of `docker version`**
```
Docker version 19.03.5, build 633a0ea838
```

## Steps to reproduce the issue

1. Create a docker/compose Dockerfile
```
FROM docker/compose:1.25.4
RUN docker-compose --version
RUN docker --version
RUN docker run hello-world
```
2. Build it
```
docker build . --no-cache
```

### Observed result
docker daemon not availalbe

```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```
### Expected result
docker daemon available

### Stacktrace / full error message

```
$ docker build . --no-cache
Sending build context to Docker daemon  4.096kB
Step 1/14 : FROM docker/compose:1.25.4
 ---> 5f3e29650cbc
Step 2/14 : RUN docker-compose --version
 ---> Running in eeb930c40c9f
docker-compose version 1.25.4, build 8d51620
Removing intermediate container eeb930c40c9f
 ---> 34c0e38cb4e5
Step 3/14 : RUN docker --version
 ---> Running in f2497e16cb73
Docker version 19.03.5, build 633a0ea838
Removing intermediate container f2497e16cb73
 ---> d570f738bba2
Step 4/14 : RUN docker run hello-world
 ---> Running in e94d9bb7321f
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
The command '/bin/sh -c docker run hello-world' returned a non-zero code: 125
```

## Additional information

My host system is debian buster (10)
docker installation by adding the repo:

```
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```

and installing these packages:

```
docker-ce docker-ce-cli containerd.io
```

**Comment by regzon** [comment]
Hello, @clement-igonet! I think that this is not the problem with the `docker/compose` image. If you try to do this with the `docker` image (which is a base image for `docker/compose`) the result will be the same. I suppose that the problem is in the fact that docker requires access to some system files that are not present during the build stage. You can ask for more details in [this repository](https://github.com/docker-library/docker).

Also, if you don't necessarily need to run this during the build stage you can put `docker run hello-world` into the `CMD` layer, like this:
```
FROM docker/compose:1.25.4
RUN docker-compose --version
RUN docker --version
CMD docker run hello-world
```
