### ISSUE TITLE
Option on `docker-compose up` to do a pull even if it already exists

### ISSUE THREAD

**Issue by jamshid** [docker/compose#7437]
**Is your feature request related to a problem? Please describe.**
I know I can do it in separate commands:
`docker-compose pull svc1 svc2 && docker-compose up -d --no-deps svc1 svc2`
but it would be very convenient and feels right for it to be available as an option on `up`. 
If not, I'd almost rather `up` not pull images at all, always require the pull step. (though yeah, matches `docker run`)

All the arguments in https://github.com/docker/compose/issues/3574 like consistency with `docker build --pull` probably still apply. 
Looks like the related https://github.com/docker/cli/pull/1498 will be available in docker v20.x.

**Describe the solution you'd like**
The `--pull` option on `up` e.g. `docker-compose up --pull -d --no-deps svc1 svc2` should attempt to pull and update the images even if they already exist. It should fail with a helpful message if the image registry is not accessible.

The `restart` command should probably also support `--pull`, if that's command is moving forward.

**Describe alternatives you've considered**
In fairness I can see the counter argument that "pull" should be a separate step from "up", to force admins to be aware of it, to avoid unnecessary failure due to a registry server being down.

**Comment by hholst80** [comment]
if you need start to do a pull, simply do a run/up with --pull.

**Comment by hholst80** [comment]
The rationale why build offers a --pull option is that is not possible to solve it in another way within the tool. It also matches docker build --pull...

**Comment by dozer75** [comment]
As the mentioned #3574 states, there is also a a view where it should be configurable in the docker-compose file. I think that it is a better solution since it may be that some images are more frequent do pull than others. E.g. I have a docker compose that consists of three services, but I only need to pull one of the images all the time, the others can live as they are.

**Comment by adriancole** [comment]
this would be fixed by #7213 I think. If a pull option is unacceptable, possibly all the various issues asking for it should be closed as a dupe and say won't fix? It is hard for someone to navigate current status which I believe is wontfix

Possibly as this is such a popular missing feature, it could warrant a FAQ or RATIONALE in the source base to summarize why it is never going to be allowed (presumably due to hoping for a better solution one year)

**Comment by hholst80** [comment]
> If not, I'd almost rather `up` not pull images at all, always require the pull step. (though yeah, matches `docker run`)

docker run only attempts a pulls if there is no image available. There is no `--pull` option for `docker run`.

**Comment by hholst80** [comment]
The ("valid") rationale for a `--pull` for up would be that `docker create` indeed does accept a `--pull` option:

```
       --pull="missing"      Pull image before creating ("always"|"missing"|"never")
```

The default, backwards compatible option, for `up --pull` would be `"missing"`.
