### ISSUE TITLE
docker-run + --use-aliases behaviour

### ISSUE THREAD

**Issue by jonathanclarke** [docker/compose#7481]
**Is your feature request related to a problem? Please describe.**
Given I have defined aliases under a network in docker-compose.yml and I run the command
`docker-compose -f docker-compose.yml run --rm webapp /bin/sh -e -c /bin/bash`
Then I would expect that the network aliases defined in docker-compose.yml be honored as requested and the --use-aliases flag would default to true.  

**Describe the solution you'd like**
--use-aliases flag should default to true.  docker-compose run + docker-compose up should exhibit the same behaviour, including network specified settings. 

**Describe alternatives you've considered**

**Additional context**
Additional containers are required to know alias hostnames + ips that are set using the alias function.

**Comment by evictor** [comment]
It seems to me that `run` is for one-off script running that uses the given otherwise long-running service as a template of sorts for some other short-lived command, whereas of course `up` is for bringing up the long-running services as-is. So using `run` in this way is unintuitive; normally you do not need a one-off script to have network aliases and be reachable since it can be run at any time and it is ephemeral, i.e. no one can be expected to be able to reach it anyway.

For your case, why wouldn't you just put the `webapp ...` command in the service `command` spec and use `up`?
