### ISSUE TITLE
using multiple compose files in different directories leads to undefined behavior

### ISSUE THREAD

**Issue by Zorigt** [docker/compose#7649]
Depending on what directory I am calling docker compose, my docker service names reflect the local directory `docker-compose.yml` file. To get around it, I have to use -p flag like so.

`docker-compose -p desired-prefix -f /path/docker-compose.yml`

It should use the docker-compose.yml file specified in the path.

**Comment by franzwong** [comment]
It is more like a design decision instead of bug to me. I guess the maintainer chose the current folder instead of the folder of yaml file because you can provide multiple yaml files to `docker-compose`. Then some people will ask to use the first one while some other people will ask to use the last one.
