### ISSUE TITLE
Please expose current user and group ID as new variables for use inside docker-compose.yml

### ISSUE THREAD

**Issue by hartwork** [docker/compose#7853]
**Is your feature request related to a problem? Please describe.**
Hi, docker-compose rocks, keep up the good work! :pray: 
I had cases where the container should be running with the same user and group ID as the docker-compose process, e.g. so that files created inside the container will start out with the right owner without any need for initial root permissions (which is not cool for security) or `chown`'ing files et cetera.

As of today, inside `docker-compose.yml` a service definition can already ask for a specific user by means of syntax `user: "<user_id>:<group_id>"` but there are no predefined variables to effectively achieve something *like* `user: "$(id -u):$(id -g)"` from inside the YAML file with convenice. The list of [Compose file and CLI variables](https://docs.docker.com/compose/env-file/#compose-file-and-cli-variables) does not document any variables like that.

Here's a few documented examples for other people trying to achieve the same, and they all need to resort to means *outside* the `docker-compose.yml` file: [[1]](https://stackoverflow.com/questions/55916455/export-current-user-id-in-makefile-for-docker-compose) [[2]](https://medium.com/faun/set-current-host-user-for-docker-container-4e521cef9ffc#b470) [[3]](https://jtreminio.com/blog/running-docker-containers-as-current-host-user/) [[4]](https://gist.github.com/prog/48341108404cae266d72ed4a470c1bc3) [[5]](https://stackoverflow.com/questions/56844746/how-to-set-uid-and-gid-in-docker-compose/56844765) [[6]](https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e).

**Describe the solution you'd like**
It would be great to have two more predefined variables:
- `COMPOSE_USER_ID` predefined with the effective user ID, as return by `$(id -u)`
- `COMPOSE_GROUP_ID` predefined with the effective group ID, as return by `$(id -g)`

With those two variables, a docker-compose.yml file could now use syntax `user: "${COMPOSE_USER_ID?}:${COMPOSE_GROUP_ID?}"` to conveniently have a container running as the same user as the one calling docker-compose. Wouldn't that be nice! :smiley: 

Feature request #3849 seems to be rooted in a similar need, but my impression was that the door to arbitrary code execution has been kept shut for security reasons so far and adding two variables should work without questioning the current threat model.

**Describe alternatives you've considered**
You could define `COMPOSE_USER_ID` and `COMPOSE_GROUP_ID` *outside* of `docker-compose.yml` e.g.
```
COMPOSE_USER_ID="$(id -u)" COMPOSE_GROUP_ID="$(id -g)" docker-compose run ...
```
but it's not very convenient, does not work out of the box, and it's not standardized.

**Additional context**
```console
# cat docker-compose.yml 
version: "3"

services:
  debian:
    image: debian:sid
    user: "${COMPOSE_USER_ID?}:${COMPOSE_GROUP_ID?}"

# COMPOSE_USER_ID="$(id -u)" COMPOSE_GROUP_ID="$(id -g)" docker-compose run debian sh -c id  # unpatched
Creating tmpyvecgpc8mx_debian_run ... done
uid=1000 gid=1000 groups=1000

# docker-compose run debian sh -c id  # patched future release, same effect
Creating tmpyvecgpc8mx_debian_run ... done
uid=1000 gid=1000 groups=1000
```

**Comment by hartwork** [comment]
Any thoughts?

**Comment by prokher** [comment]
Honestly, I am waiting for this feature for years already, this is the last thing keeping me from throwing away scriptware around the Docker Compose.

**Comment by muxator** [comment]
Hi, I think this is a much needed feature. Currently, security-sensitive users need to invert all sorts of alternatives to run containers as a restricted user. Or worse, there may be someone who just does not care and leaves files owned by root laying around in the system.

This proposal seems to be sufficiently simple to be embraced by the sheer majority of the community.

**Comment by vmgustavo** [comment]
I am currently working on a project where I need exactly this: to run the container with the same user and group as the host to avoid permission problems.

The solution given in the "Additional context" of @hartwork comment is enough, but a more robust solution would be interesting.

**Comment by hartwork** [comment]
@docker any thoughts?

**Comment by MetalArend** [comment]
I saw some mentions of a variable called `$DC_UID`, but it does not seem to work.

**Comment by hartwork** [comment]
Ping, this is still relevant.

**Comment by briceburg** [comment]
yes, there is a common need for this and if it were supported natively instead of requiring a wrapper, the better!

**Comment by grantwest** [comment]
Still a very relevant feature request. If you are using volume mounts with any of your compose containers and the container writes anything to the mount you end up with root owned files.

**Comment by shaileshaanand** [comment]
> yes, there is a common need for this and if it were supported natively instead of requiring a wrapper, the better!

@briceburg  What wrapper are you referring to?

**Comment by ndeloof** [comment]
While we acknowledge the issue managing container permission to access a bind mounted path, as UID/GID is not a portable concept (there's no such thing on Windows) we can't introduce support for this in compose (has been requested in the past, debated then rejected).

AFAICT this is a general Docker issue, as a bind mount can't remap host's file owner with container's `USER`. This would require ID-shifting filesystems as detailed on https://lwn.net/Articles/812504/, which _should_ be feasible with user namespace enabled (already supported by Docker engine, while not enabled by default)

There's a bunch of related issue on docker engine repository, for example https://github.com/moby/moby/issues/2259 but maybe not the most relevant here. Anyway, I'm closing this issue as exposing UID/GID is an option we already rejected in the past, and I can't see any reason we change our mind.

Also to be considered: with the addition of `develop` section and `watch` feature, it _should_ be feasible to avoid using a bind mount inside container to let it access local files, as long as a single-direction sync is required.

**Comment by hartwork** [comment]
@ndeloof I think this is making the topic bigger than it really is: All I was asking for is auto-filled environment variables with the IDs for (a significant increase in) convenience. If it's not happening on Windows, alright, fail with an error or fill 0. Is that really something that needs rejection?

**Comment by garymoon** [comment]
@hartwork's take matches my initial thinking also - the scope as described by @ndeloof seems to have grown beyond what was requested in the original issue description. It also seems to me like this scope expansion is where Windows compatibility concerns have crept in. Could you clarify please @ndeloof?

**Comment by nanaya** [comment]
fwiw my current workaround is to run the image as root and have the entrypoint script do uid/gid lookup/sudo (gosu) ceremony

https://github.com/ppy/osu-web/blob/9ab73e006fc9f6bc0835cb83ee612271ffe201b6/docker/development/entrypoint.sh#L17-L35

also, I thought with virtiofs, bind mount is becoming more relevant than ever?

**Comment by ndeloof** [comment]
@hartwork this issue is asking we expose user's uid/gid (from client) as a variable to be used for interpolation. What you need to consider: 
1. "how hard is this to introduce this feature" (i.e. https://github.com/compose-spec/compose-go/pull/572) 
2. what are the limitations
3. understand the actual use-case this feature is required for. 
 


On (1):  UID/GID only can be resolved on Linux/Mac, and has no equivalent on Windows. Setting `0` by default would be wrong as this is `root` user on Unix. So the portability issue. I don't like the idea Windows users will all run containers as root without knowing _because_  compose.yaml can't give a reasonable UID. That would just bring security issues.

On (2): This only applies to non-Windows **and** locally running docker daemon. Client UID doesn't make any sense for those targeting a remote docker host. Nothing will warn them about this and this can bring weird usability issues. From a general point of view, client UID _should not_ (notice use of conditional) have any impact on resources managed by (maybe remote) docker engine. The "_bind mount local path inside container_" is just a common pattern, mostly used for development purpose.

On (3): people asking for `UID` don't actually _need_  UID, but they would like to get this as a workaround for another issue.
The reason user ask for this "feature" is to workaround permission mismatch between host and container _running locally_ (which is a common usage, but not a requirement. In many cases, docker host is remote). This mismatch is not specific to compose, this is a global docker issue with bind mounts. So adding such a feature would basically hard-code a workaround

There's no trivial fix for this issue proposed on docker engine. Use of [bindfs](https://bindfs.org/) with `-map` option _could_ allow binding a host path inside container with mapping between host uid and container uid, but that's just my assumption and I'm not aware of any experiment in this area. The best I'm aware is https://github.com/StudioEtrange/docker-volume-bindfs which allow to declare a `volume` with a host path and an explicit uid mapping. Maybe something to be investigated.

A possible workaround is to rely on `watch` feature we introduced to cover the "development in container" pattern. 

Alternatively, with recent addition of `post_start` hooks, one could run some `chown` command, which isn't very pleasant but could also offer a workaround for this uid mismatch issue.

**Comment by hartwork** [comment]
@ndeloof we're still at bigger picture than necessary: Docker compose supports [`user:`](https://docs.docker.com/reference/compose-file/services/#user) for a long time and helping with filling certain values into it does not make it more of a portability thing than it already is. I'm happy with avoiding 0 on Windows if you want, that's a detail. https://github.com/compose-spec/compose-go/pull/572 looked great except `> 0` versus `>= 0` and mixing *effective* GID (`get_e_gid`) with *real* UID (`getuid`). (Would be easy to offer all four (real and effective for both user and group ID).) Hard-coding this workaround is for (3) is the right move while waiting for a better solution in my book.

**Comment by garymoon** [comment]
RE the removed comment suggesting looking up the IDs and passing them into compose - I can't speak for everyone else in the thread, but wrapping compose in bash is what I'd be most excited to avoid if this issue were implemented.

**Comment by hartwork** [comment]
@ndeloof if an error message would be considered convenient I could have added that right into `user: "${COMPOSE_USER_ID?}:${COMPOSE_GROUP_ID?}"` from the start. So that's not more convenient.

**Comment by ndeloof** [comment]
sure, I'm just documenting support for error message for missing variable, which only a few users know about.
Again, I fully acknowledge there's a major issue with bind mount permission, still having compose to expose an unportable variable as a workaround isn't a "fix" we have considered valid, after this has been requested many times. That's a team decision, not just me

**Comment by hartwork** [comment]
@ndeloof I agree it's not a fix but an enhancement, an increase in convenience, it makes things work with less user intervention.

**Comment by ndeloof** [comment]
while I understand the frustration, this isn't a question of debating bug fix vs feature. This has been discussed many times between maintainers, as you noticed I even went with a PR to propose a "reasonable" implementation, still no consensus on approval. Closed

**Comment by hartwork** [comment]
@ndeloof the discussion in https://github.com/compose-spec/compose-go/pull/572 was about portability which is not the right question and hence was not the right discussion.

**Comment by nanaya** [comment]
> RE the removed comment suggesting looking up the IDs and passing them into compose - I can't speak for everyone else in the thread, but wrapping compose in bash is what I'd be most excited to avoid if this issue were implemented.

the one I'm using isn't wrapping compose in bash but the entrypoint itself - the image is run as root and but the entrypoint script switches to the correct user (by checking bind mount permission) when running any commands. Users of the image won't have any idea what's going on underneath and most of the things _should_ just work.

**Comment by shaileshaanand** [comment]
> > RE the removed comment suggesting looking up the IDs and passing them into compose - I can't speak for everyone else in the thread, but wrapping compose in bash is what I'd be most excited to avoid if this issue were implemented.
> 
> the one I'm using isn't wrapping compose in bash but the entrypoint itself - the image is run as root and but the entrypoint script switches to the correct user (by checking bind mount permission) when running any commands. Users of the image won't have any idea what's going on underneath and most of the things _should_ just work without them specifying anything or using any specific scripts.

@nanaya Interesting solution, could you please share the entrypoint script if possible?

**Comment by nanaya** [comment]
> Interesting workaround, could you please share the entrypoint script if possible?

it's relatively straightforward:

https://github.com/ppy/osu-web/blob/9ab73e006fc9f6bc0835cb83ee612271ffe201b6/docker/development/entrypoint.sh#L17-L35

(now I look at it again, I should've split out the actual entrypoint script and have it run by a wrapper instead)

although note that this won't do anything when using `docker compose exec`

**Comment by scriptogre** [comment]
Still very relevant in 2025. 

I understand the portability concerns, but since the `user:` field already exists with the same Windows limitations, it seems like these variables would just make an existing feature more convenient to use rather than introducing new portability issues. 

The current workarounds (env vars, wrapper scripts) work but aren't standardized. 

Would love to see this reconsidered.
