### ISSUE TITLE
Proposal: add docker-compose rmi

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#790]
The command would remove the images built for a specific service. 

I thought `fig rm` would do that or did I overlook something?

**Comment by nathanleclaire** [comment]
If you want to build them from scratch, you can use `fig build --no-cache`

**Comment by thaJeztah** [comment]
Maybe a `fig rmi [service]` command should be added as a convenience wrapper for `docker rmi`?

**Comment by aanand** [comment]
Yes, `fig rmi` should exist. My gut says it should only work by default on fig-built images, not pulled images, because you don't want to accidentally delete `redis` (you've likely got other apps using it).

**Comment by thaJeztah** [comment]
Good point. Basically, that's why I suggested using `[service]` as argument, not the image-name or id. So `fig rmi redis` would remove image `myproject_redis`

In future, keeping track of images that are / are not created by Fig will probably get easier if https://github.com/docker/docker/pull/9882 without having to rely on the image-name itself

**Comment by pospispa** [comment]
+1 for `docker-compose rmi` that removes images built with `docker-compose built` or as a result of `docker-compose up` for services with `build:` in .yml file.

**Comment by mariolameiras** [comment]
Any news regarding the destruction of images with docker-compose ?

**Comment by decoomanj** [comment]
Is this feature planned for the near future?

**Comment by samuelololol** [comment]
+1 need `docker-compose rmi`

**Comment by gnarea** [comment]
This would be very handy. Would you accept a pull request for this?

**Comment by dnephin** [comment]
We need to flush out how this will work with #2092

If every service has an image name, should `docker-compose rmi` remove only the images without a `build` field? Only services that don't have an `image` field? Or all the images?

I think we can support any of these (with command line flags), but I'm not sure which should be default.

A pull request is always welcome! Maybe start with just the docstring of the new subcommand `def rmi(...)`, so we can figure out the right flags and defaults?

**Comment by dnephin** [comment]
docker-compose 1.6.0 RC1 was just released which includes `docker-compose down` (#2277).

`down` has an option to remove images after removing containers. Since it's not good to remove an image without first removing the containers I believe that feature satisfies this feature request.

I'm going to close this issue, but if there is a case you feel isn't handled by `down`, please comment and let us know.

**Comment by slieker-d** [comment]
`docker-compose down` does not have the ability to target specific services, so I'm not sure that this issue should be closed yet.
