### ISSUE TITLE
Add basic support for Swarm

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#814]
You should be able to define a simple application with Fig and run it on [Swarm](https://github.com/docker/swarm) with `fig up -d`.

This work was started in #763. One remaining issue is that Swarm returns names with more slashes in it than the normal Docker daemon, so Fig needs to parse this correctly.

Assumptions:

 - links won't work
 - volumes probably won't work

**Comment by dnephin** [comment]
Is this closed by #851 ?

**Comment by aanand** [comment]
Not quite - we need to ascertain exactly what does and doesn't work, verify that a satisfactory subset of functionality is supported, and document it.

**Comment by aanand** [comment]
So, once https://github.com/docker/swarm/pull/388 is merged, Swarm should have all the pieces in place for basic integration. Unfortunately, Compose doesn't, and the problem is `volumes_from`.

Swarm correctly co-schedules containers that use `volumes_from` to share volumes, but only if `volumes_from` is specified at *creation time*, whereas Compose specifies it at *start time*. This means that, with Compose as it currently works:

- `recreate_container()` is not guaranteed to place the new (or the intermediate) container on the right node.
- If it doesn't, starting the new container will fail.
- `docker-compose up` will therefore randomly fail on clusters of size > 1.

The "correct" solution is to specify `volumes_from` at creation time. There are two hiccups here:

- It may break backwards compatibility with Docker <1.4, unless the API allows you to specify it at both creation and start time. In any case don't think this is much of an issue, as we're pushing out a breaking version increment and Docker 1.4 is now two months old.
- docker-py doesn't let you pass `volumes_from` to `create_container()`, so we'll have to fix docker-py first.

A more hacky solution is to pass an affinity filter in when creating both the intermediate and the new container, i.e.

- Add an environment variable `affinity:container==<id of old container>` to the intermediate container
- Add an environment variable `affinity:container==<id of intermediate container>` to the new container

**Comment by aanand** [comment]
Regarding previous comment: see #972. I turned out to be wrong about docker-py - you can pass in a `host_config` as of API version 1.15.

**Comment by bfirsh** [comment]
https://github.com/docker/compose/blob/master/SWARM.md

**Comment by aanand** [comment]
![giphy 3](https://cloud.githubusercontent.com/assets/1062/8549274/de5d2b12-24c1-11e5-9ee5-489d4fe67973.gif)
