### ISSUE TITLE
path set by --env-file must be considered absolute

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#8197]
## Description of the issue

User passing an explicit path as `--env-file` can use a relative path to the command's working directory. Loading env from this file must consider this path unrelated to the project-directory. 

I suggest https://github.com/docker/compose/blob/master/compose/cli/main.py#L328 is updated to resolve relative paths (`./xx`, `../xx` or `~/xx`) and https://github.com/docker/compose/blob/5b7851f55b4ae9533f42eed282ffad7c442778f5/compose/config/environment.py#L57 use this explicit path "as-is".

## Context information (for bug reports)
Follow-up on https://github.com/docker/compose/issues/6581#issuecomment-797320216 discussion

**Comment by DrVanScott** [comment]
Maybe this is related to #8173

**Comment by ndeloof** [comment]
@DrVanScott it is indirectly. `.env` location is relative to project-directory, but passing --env-file should just ignore this convention

**Comment by melaquias** [comment]
Just want to confirm this issue.   Definitely was not there prior to upgrading to 1.28.2 (from 1.26.5) yesterday.  It does not occur on a system that I still have at the older version.

This breaks existing scripts that invoke docker-compose using the --env-file switch.   It also possibly breaks with use of multiple "-f /path/to/compose.yml" files that may not be co-located, since the resolved path suddenly seems to be relative to the compose file directory.  I have not tested that though.

**Comment by ndeloof** [comment]
Just a side note that, prior to 1.28, you would have the same issue when using both `--env-file ./foo/myenv` _and_ `--project-directory ./bar`. This combination used to resolve env file path as `(pwd)/bar/foo/myenv` which is most probably NOT what you'd have expected.

so 1.28 definitively came with a fix to the bad interaction between `--project-directory` (or indirectly `-f`) and resolution of the env files relative path.

**Comment by ljrahn** [comment]
docker-compose --env-file ./.env.development -f ./deploy/development/docker-compose.yml up --build -d                                                           test-monogo-db
open /Users/lucasrahn/batcave/projects/lendus/lendus-app/deploy/.env.development: no such file or directory

my current working directory is lendus-app, but for some reason its looking for my .env.development file in lendus-app/deploy.
