### ISSUE TITLE
Compose Profiles should allow for additional services

### ISSUE THREAD

**Issue by ucheNkadiCode** [docker/compose#8243]
With the new addition of Compose profiles, the way they were implemented is sort of rigid. Either you can use a profile to group which services you can run (services that have no profile will always get run) or you have to list out each individual service you want to run in the compose up command. 

I want the ability to declare whichever profile I want to run, and also allow me to select a few additional services as I'm debugging. This makes it so I don't have to constantly edit my compose file to include an arbitrary service in the service list.

For instance, if I have two services `debug_service` and `backend_service`, running this command would ONLY run the `debug_service` even though I'm trying to explicitly declare to add in the `backend_service` as an additional service.
```bash
docker-compose -f docker-compose.foo.yml --profile debug up backend_service
```

**Comment by ndeloof** [comment]
According to the Compose specification, when `docker compose up` is ran with an explicit service name, this service MUST be automatically enabled
see https://github.com/compose-spec/compose-spec/blob/master/spec.md#profiles

This is fully supported in [Compose v2](https://github.com/docker/compose-cli). Maybe docker-compose is buggy regarding this expected behavior?
