### ISSUE TITLE
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by Exclusive-gfj** [docker/compose#8326]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '2'
services:
  sk-cloud-auth:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    #volumes_from:
    # - container:pinpoint-agent
    container_name: sk-cloud-auth
    image: xxxx/xxxx
    network_mode: host
    volumes:
      - /xxx/xx/xxxx/.env:/.env
    ports:
      - 3000:3000
```

## Steps to reproduce the issue

1.docker-compose up -d

### Stacktrace / full error message

```
ERROR: for xxxx  "host" network_mode is incompatible with port_bindings
ERROR: for xxxxx  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.8/site-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1189, in up
    to_attach = up(False)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1169, in up
    return self.project.up(
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 559, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 473, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 478, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 457, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 939, in _get_container_create_options
    container_options['host_config'] = self._get_container_host_config(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 1014, in _get_container_host_config
    return self.client.create_host_config(
  File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 598, in create_host_config
    return HostConfig(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/types/containers.py", line 338, in __init__
    raise host_config_incompatible_error(
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by lunajiang2020** [comment]
[https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode)
Note: Port mapping is incompatible with network_mode: host

**Comment by fshields** [comment]
I couldn't let this go without researching how & when this new behavior was introduced.  It wasn't easy to find out. I could not find any trace of it in the docker-compose source code.  I started to wonder if it might be in one of the included packages.  So, I took a closer look at the stack trace where the error happened. The last lines were:

```
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[4218] Failed to execute script docker-compose
```
Some Google searching on "docker/types/containers.py" led me to the `docker-py` Python package (which is used by docker-compose). After that the rest was more straightforward.
* Found [pull-request 2511](https://github.com/docker/docker-py/pull/2511)
* Which led to the [offending commit](https://github.com/docker/docker-py/commit/6da140e26c1cbe8e362b328b1c78d9c736f3a1a2)
* That commit was included in version 4.4.0 of `docker-py` on November 23, 2020
* `docker-compose` version 1.28.0 was released on January 20, 2021 and bumped its version of `docker-py` to 4.4.1 (skipping 4.4.0) as seen in the [release notes](https://github.com/docker/compose/releases/tag/1.28.0)

So any version of docker-compose v1.28.0 or higher is subject to throwing these error messages if you specify BOTH "network_mode: host" and "ports:"

**Comment by tedtramonte** [comment]
For additional context, I'll provide our use case and why this should be fixed to be a warning: 

We have two docker-compose files, one with the typical development environment setup, and another with some overrides necessary for the composed services to connect to our infrastructure over our VPN connection. E.g. `docker-compose -f docker-compose.yml -f docker-compose.vpn.yml up`

This means the base docker-compose has port bindings for us to work with locally, but the vpn override specifies host networking mode to use our running VPN. This has always been fine, we understand the implications of host networking mode and that the port bindings are then ignored.

My initial thought, and what I think is quite reasonable, is to explicitly add `ports: []` to `docker-compose.vpn.yml`, but that of course doesn't work because docker-compose merges the arrays when specifying multiple files with `-f` rather than replacing them.

Setting host networking mode is a much less common use than setting port bindings, and so it should probably carry more weight when it is set. It makes sense, then, to have that take precedence over port bindings in a case like this. The message content is good, but it should *not* be a show stopper, considering this has worked fine for years.

**Comment by thohng** [comment]
Hi, I got same issue, I current use v3. Removing **all port bindings** works for me.

OLD:

```
version: "3.8"
    ...
    network_mode: host
    volumes:
      - /xxx/xx/xxxx/.env:/.env
    ports:
      - 3000:3000
```

NEW:
```
version: "3.8"
    ...
    network_mode: host
    volumes:
      - /xxx/xx/xxxx/.env:/.env
    ## ports: Do not use port bindings with "host"
    ##  - 3000:3000
```

**Comment by Omar-Belghaouti** [comment]
Why is this a stale issue? How is it okay to run an image with `docker run -p ...` works but not with `docker-compoes up`?

**Comment by plewkowycz** [comment]
Any update on above?

**Comment by laurazard** [comment]
Hiya,

This is an old issue but I figured I'd give some context for anyone coming across this in the future.

For context about `network_mode: host` – as per the [docs](https://docs.docker.com/network/host/):
> If you use the host network mode for a container, that container’s network stack is not isolated from the Docker host (the container shares the host’s networking namespace), and the container does not get its own IP-address allocated. For instance, if you run a container which binds to port 80 and you use host networking, the container’s application is available on port 80 on the host’s IP address.

As such, using the host networking mode together with specifying ports does not make since. Indeed, if you run the following command:
```bash
$ docker run --rm --network host -p 3000:3000 nginx:latest
...
> WARNING: Published ports are discarded when using host network mode
```

We get a warning about published ports being discarded, since the container just directly binds to ports on the host's networking stack.

Asides from that, this issue was reported for Compose V1 (the Python version) which is now [EOL and not receiving updates anymore](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/). If you're still using Compose V1 you should really consider updating to Compose V2, which also features a bunch of new functionality.

Using Compose V2, and a Compose file such as:
```yaml
services:
  a:
    image: nginx
    ports:
      - 3000:3000
    network_mode: host
```

We get:
```bash
[+] Running 2/0
 ✔ Container dev-a-1                                            Created                                                                                                                                                                                                                                                                                                0.0s
 ! a Published ports are discarded when using host network mode
```

which is the same warning mentioned above.
