### ISSUE TITLE
[BUG?] docker-compose exec does not accept the container name

### ISSUE THREAD

**Issue by yyaremenko** [docker/compose#8343]
**Is your feature request related to a problem? Please describe.**
According to the [documentation](https://docs.docker.com/compose/reference/exec/)
```
docker-compose exec
```
is an equivalent of
```
docker exec
```
but this is not true, as docker-compose exec does not accept container's name, it only accepts the service name.
If you try to use container name, you get
```
ERROR: No such service: my-super-container-name
```

**Describe the solution you'd like**
Add such functionality to docker-compose exec.

**Describe alternatives you've considered**
Add a corresponding warning to the documentation? And/Or make the error message more informative, e.g.
```
ERROR: No such service: my-super-container-name. Make sure you use service name, not container name.
```

**Comment by bartier** [comment]
I think the best way to deal with this is to clarify the warning because the documentation shows already that you need to reference a `SERVICE` instead of the container name or ID:

**docker-compose exec [options] [-e KEY=VAL...] `SERVICE` COMMAND [ARGS...]**

If you would like to access the container using its name or ID you could use the `docker` command itself.

Do you have any thoughts on it? Feel free to share!

**Comment by yyaremenko** [comment]
Yes, I agree, you are correct, the documentation says ```SERVICE```, I overlooked it somehow. My bad. If it is not possible / does not make sense for ```docker-compose``` to accept container name / id, yes, I believe a nice warning message would be great, e.g.

```ERROR: No such service: "my-super-container-name". Make sure you address an existing service. If you instead need to access a container by its name / id, please use the "docker" command.```

**Comment by ndeloof** [comment]
All docker-compose commands target `services` as defined in your compose file, not containers.
If you wish to target container, just use `docker exec`.
