### ISSUE TITLE
docker-compose pull --dry-run or docker-compose pull --update-available

### ISSUE THREAD

**Issue by OoLunar** [docker/compose#8345]
**Is your feature request related to a problem? Please describe.**
I'm attempting to create a "Docker update" script, which has all my docker-containers pull the `:latest` tag from their respective repositories. Due to me not knowing which images have updated, I have to `docker-compose up -Vd` all of my containers, which takes quite a bit of time on some containers, thus interrupting the services I provide.

**Describe the solution you'd like**
A `docker-compose update` or some variant. The first and simplest solution that comes to mind is adding a `--dry-run`. An "update available" can be conveyed by exit codes or through text that can be used by `xargs` or `grep`

**Describe alternatives you've considered**
I have found no simple alternatives to determining if an image has an update, without updating the image.

**Additional context**
N/A

**Comment by bartier** [comment]
@OoLunar I don't think it's a good practice to use the latest tag version in production containers because you can face the problem you stated: a simple docker pull will get the latest version and may be incompatible with the current settings.

Are you considering this use case in which cases? Could you please share more details about your use case if possible so we can clarify more possibilities?

**Comment by OoLunar** [comment]
Of course! Two of my containers are published by me, as in I'm pulling the latest tags from my images. Most of my other containers are pulling from the latest-release/latest-stable, which updates monthly/weekly. Finally, 2 of my containers are running nightly (`:latest` tag). I'm using the nightly tag because the two containers have been doing a huge rewrite, and the next release won't be happening for awhile now.
