### ISSUE TITLE
docker-compose not seeing the .env file in parent project directory

### ISSUE THREAD

**Issue by fpoulin09** [docker/compose#8347]
## Description of the issue
When docker-compose doesn't find a compose file in the current directory it searches in the parent directories until one is find. However, doing so, it doesn't interpret the .env file.

As per the doc:

> Starting with +v1.28, .env file is placed at the base of the project directory

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: The TAG variable is not set. Defaulting to a blank string.
services:
  web:
    image: 'node:'
version: '3'
```

## Steps to reproduce the issue

1.Reproduce de following file structure
```
myproject/
|__.env
|__docker-compose.yml
|__config/
    |__ ....

# .env
TAG=14

# docker-compose.yml
version: '3'
services:
  web:
    image: "node:${TAG}"
```
2. Go into the config folder or any other sub-directory
3. run `docker-compose config`

### Observed result
1. When no docker-compose.yml file is found, it is looking into the parent folders for a compose file

2. the `.env` is not interpreted

### Expected result
the `.env` file should be used.

I didn't find any documentation specifying that docker-compose searches in all parents for the first docker-compose file it finds. However, if it was the case, I would expect the directory containing the compose file to be the project directory and therefore interpret the `.env` file correctly.

This issue is not encountered if you specify the `-f` flag. However, it should be documented or fixed.

### Stacktrace / full error message

```
`WARNING: The TAG variable is not set. Defaulting to a blank string.`
```

**Comment by markuskeunecke** [comment]
I can confirm this bug using

**Docker-Compose version**
`docker-compose version 1.29.1, build c34c88b2`^
**Docker version**
```
docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

However a workaround is to manually specify .env-file via _--env-file_ parameter.

**Comment by ndeloof** [comment]
I don't think we should change the way .env file is searched for.

For sure docker-compose searches parent folders for a compose file, but this doesn't mean we should extend this (debatable) behavior to `.env` file, as this might result into loading a file that is unrelated to current project. 

dotEnv file is a _de facto_ standard without a clear definition, but according to Ruby and Python development usages, it's **only** loaded from current directory. 
1.28 introduced a fix, as previously the path to `.env` file was dependent on the usage of an explicit `--project-directory`. Starting with this release, docker-compose align with other tools which rely on dotEnv files to store configuration.

**Comment by olastor** [comment]
@ndeloof If it is expected behaviour, then the documentation does not obviously reveal it IMO. Please let me explain what I mean:

[Here](https://docs.docker.com/compose/environment-variables/#the-env-file) the docs say:

> - Starting with +v1.28, .env file is placed at the base of the project directory
> - For previous versions, it is placed in the current working directory where the Docker Compose command is executed unless a --project-directory is defined which overrides the path for the .env file. This inconsistency is addressed in +v1.28 by limiting the filepath to the project directory.

The way I read this is that for earlier versions you by default load the `.env` file from the current directory, but for `>= v1.28` the default is that the `.env` file is always loaded from the project directory (in which the `docker-compose.yml` lies).

Later it says:

> The .env file is loaded by default:

So since it first states the file should be placed in the the base of the project directory and shortly later that it's loaded by default, I assume as a reader that only the `.env` in the project directory will be loaded when I run `docker-compose`.

I find that confusing given that docker-compose `>= v1.28` seems to load the `.env` file from the current directory. The documentation could be clearer about that IMO.

Also I am a bit biased, because I am mostly using dotenv with Node.JS where the convention is that it's placed in the project directory and the current directory doesn't matter when running your script that imports it. That might be different for Ruby and Python, though.

**Comment by satotake** [comment]
Thank you for your comment @ndeloof 

OK. This topic might be controversial. I'm careful about it.

I have studied more.

---

> 1.28 introduced a fix, as previously the path to .env file was dependent on the usage of an explicit --project-directory. Starting with this release, docker-compose align with other tools which rely on dotEnv files to store configuration.

Probably, this is related to [this change](https://github.com/docker/compose/pull/8198).

it says that

> .env remains relative to the project directory

It seems to be sure that the current behaviour will be intentional.

---

I searched dotenv practices in python but cannot find (as you described it as defacto).

Next, I checked some usages of python libs.
I found the followings have a similar functionality (`.env` file search).

- [python-dotenv](https://github.com/theskumar/python-dotenv/blob/303423864ae00f8d5f21cb39d6421a7d775a3daf/src/dotenv/main.py#L252)
- [django-dotenv](https://github.com/jpadilla/django-dotenv/blob/c68fd4bf3ae330c7160a620210f760f0a52359fd/dotenv.py#L42)
- [pipenv](https://github.com/pypa/pipenv/blob/275f7e151eb0aa17702215165a371df7da9ad476/pipenv/vendor/dotenv/main.py#L264)
  - though pipenv might be inspired by npm

(This is my opinion but) it might be good to discuss the possibility to implement the search.

---

So, what should we do now?

If we will not reach our conclusion of this issue soon, I agree with @olastor  's opinion.

I am ok to retry it by myself or for someone (maintainer?) to implement it on behalf of me after finishing discussion, in the future.
It might be better just to update documentation currently.

**Comment by markuskeunecke** [comment]
@ndeloof from my point of view it is problemativ that docker-compose breaks existing environments with the change mentioned before.

We for example have a deployment with a compose file shared between multiple projects and the `.env` being placed in the project folder. This kind of deployment suddenly became somehow broken as we'll need to carefully look into our scripts.

* applications
** docker-compose.yml
** application-a
*** .env
** application-b
*** .env

**Comment by ndeloof** [comment]
change introduced in 1.28 obviously broke a few usages, but it was required as docker-compose was inconsistent before regarding the way it resolved path for dotEnv file.

**Comment by satotake** [comment]
At first, I created [PR](https://github.com/docker/docker.github.io/pull/12978) to update doc for the current behaviour.
Any comments are welcome.

What is confusing us is that the definition of `project directory` as @olastor pointed out.
So, I added some words for it.

**Comment by benatkin** [comment]
To me it's clear that `.env` should be in the project directory, a sibling of `docker-compose.yml`, like `django-dotenv` ([it only looks in one location](https://github.com/jpadilla/django-dotenv/blob/master/dotenv.py#L53)) but not like `python-dotenv` ([it walks to the root](https://github.com/theskumar/python-dotenv/blob/master/src/dotenv/main.py#L285)). It shouldn't search upward for `.env` but should search for `docker-compose.yml` and find the sibling `.env`. Also this change would be nice to get into 2.0 because it is breaking behavior.

**Comment by benatkin** [comment]
Maybe the existing behavior is more common than I thought - it seems django-dotenv could be just getting `.env` from the current directory like docker-compose currently does. It is too bad that it renders docker-compose's searching for `docker-compose.yml` useless for someone using project-wide `.env` files.

**Comment by benatkin** [comment]
I agree with keeping the current (1.28) behavior and just updating the documentation. There are three that appear to be common:

- getting `.env` from the current working directory (current behavior, [dotenv on npm does this](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L83))
- getting `.env` from the current working directory, and if it is not found, walking to the root and getting the `.env` from the nearest ancestor directory that has it ([pipenv does this](https://github.com/pypa/pipenv/blob/275f7e151eb0aa17702215165a371df7da9ad476/pipenv/vendor/dotenv/main.py#L297))
- looking for something else indicating where the project root is, and getting `.env` from that ([django-dotenv](https://github.com/jpadilla/django-dotenv/blob/master/dotenv.py#L41) looks for `manage.py`)

I've seen the [subdirectory technique used](https://github.com/docker/compose/issues/8347#issuecomment-855990730), and because of that, my second favorite option is mimicing pipenv's behavior, of searching upward for the nearest `.env`, and my least favorite is finding the project directory and getting the `.env` that is in the same directory.

**Comment by dotancohen** [comment]
> Another option is doing what `pipenv` does but not go above the project directory - that is, look upward from the current directory but not all the way to root, stopping when `docker-compose.yml` is found.

In my opinion this is the correct, expected behaviour. It is user-friendly, it is consistent with how the compose file is found, yet it does not open security issues by searching too far up.

**Comment by sakalys** [comment]
> > Another option is doing what `pipenv` does but not go above the project directory - that is, look upward from the current directory but not all the way to root, stopping when `docker-compose.yml` is found.
> 
> In my opinion this is the correct, expected behaviour. It is user-friendly, it is consistent with how the compose file is found, yet it does not open security issues by searching too far up.

I agree to the reply of @dotancohen. To me this bevharios seems like the only logical approach - we are walking up the directory stack to find the compose file, which signals the end of the furthest point where we should look for the .env file.

## Examples

### Base example
```
protected-parent/
├── .env
└── project-root/
    ├── src/
    ├── docker-compose.yml
    └── .env
```
Starting the project from within `src` directory loads the sibling `protected-parent/project-root/.env` file which is a sibling of docker-compose.yml.

The `protected-parent/.env` file should be ignored because it is outside the directory where `docker-compose.yml` lives.

### Nested env files
Which is the case mentioned by @markuskeunecke.
```
protected-parent/
├── .env
└── project-root/
    ├── docker-compose.yml
    ├── src/
    │   └── .env
    ├── sub-project-1/
    │   └── .env
    └── sub-project-2/
        └── .env
```
Starting the project from any a directory other than `sub-project-1` or  `sub-project-1` (or their children) should not detect any .env files. Whereas if started from either the tree of `sub-project-1` or `sub-project-2`, it should detect their respective .env files.

The `protected-parent/.env` file should be ignored.


### Recursively nested env files

This is the _problematic case_ which might be controversial, but here's my take on this... Given the following structure, where there are multiple .env files in various directories, we ought to take the outer-most .env file, but no more out than the project root (where the docker compose file lives - in this case `protected-parent/project-root/.env`).
```
protected-parent/
├── .env
└── project-root/
    ├── .env
    ├── docker-compose.yml
    ├── src/
    │   └── .env
    ├── sub-project-1/
    │   └── .env
    └── sub-project-2/
        └── .env
```

### Nested docker compose files with .env file outside:
```
protected-parent/
├── .env
└── project-root/
    ├── sub-project-1/
    │   └── docker-compose.yml
    └── sub-project-2/
        └── docker-compose.yml
```
In this case no.env file should get loaded in any case.

---

What do you think?

**Comment by ArturWebtech** [comment]
The documentation does not only confuse humans but also LLMs which say to put `env_file: ../.env` into `docker-compose` which does not work. Enabling either this or making docker-compose see `.env` file in parent directory would be very beneficial for project setup.
