### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by leklid** [docker/compose#8436]
Hi there! I am writing my own script that should autocomplete the names of the commands and the flags of these commands. I am happy to use docker-compose and I know that you have a great auto-completion. How did you do that? Can you show in which files it is stored in your project, how it is coded and how to use them?

**Comment by jarulsamy** [comment]
This file probably has what you are looking for: [contrib/completion/bash/docker-compose](https://github.com/docker/compose/blob/c81046aac0ce1360f1bab64368f9a318c593d82a/contrib/completion/bash/docker-compose).

**Comment by stefanocudini** [comment]
where is this file in v2 version?

**Comment by jarulsamy** [comment]
> where is this file in v2 version?

Since v2 is a major rewrite, and the intention is to use `docker compose` instead of `docker-compose`, I believe the autocompletion information got moved to the [docker/cli](https://github.com/docker/cli/blob/master/contrib/completion/bash/docker) repository.

There is some mention of `docker compose` [here](https://github.com/docker/cli/blob/master/contrib/completion/bash/docker#L5491). I think most of the autocompletion entries are yet to be ported for the new interface, so there may be more changes in the future. But if your intention is just to use this as guidance for writing your own autocompletion entries, the existing items in that file should be more than satisfactory. 

Feel free to correct me here, this is just what I found from a few minutes of searching :smile:.
