### ISSUE TITLE
/usr/local/bin/docker-compose: line 1: Not: command not found

### ISSUE THREAD

**Issue by malawi7** [docker/compose#8445]
Hey guys,

I want to use docker-compose on my raspberrypi 4 with ``Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1041-raspi aarch64)``.

I go through the official docker compose installation guide (https://docs.docker.com/compose/) and when I try to use ``docker-compose --version`` I got this error:

ubuntu@ubuntu:~$ docker-compose version 
``/usr/local/bin/docker-compose: line 1: Not: command not found``

The file ``/usr/local/bin/docker-compose`` seems to be empty.

Docker-Version: ``Docker version 20.10.7, build f0df350``

I'm a newby and I can't find the solution for this mistake.

CURL output is:
~~~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     37      0 --:--:-- --:--:-- --:--:--    37
~~~

My commands:

~~~
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
~~~

~~~
sudo chmod +x /usr/local/bin/docker-compose
~~~

~~~
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
~~~

Last command output:
ubuntu@ubuntu:~$ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
``ln: failed to create symbolic link '/usr/bin/docker-compose': File exists``

**Comment by marti1125** [comment]
I have the same problem with flag -v in pycharm also

![dockererror](https://user-images.githubusercontent.com/223240/126794594-cd5e6867-1865-4293-9c52-b53ca3efe3ec.png)

$ docker-compose version
Docker Compose version v2.0.0-beta.6

$ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by cgrycki** [comment]
I assisted a friend that was also encountering this issue on a Raspberry Pi and thought I'd share the solution.
Release 1.29.2 of Docker Compose does not include a binary that was compiled for ARM64. On the Raspberry Pi, uname -m returns "aarch64".  The resulting URL from the command becomes [https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-aarch64](https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-aarch64). This does not exist and returns a 404 Not Found status. As a result, curl creates a 9B file at /usr/local/bin/docker-compose with the contents "Not Found".
Binaries for ARM64 have been available since v2.0.1. (see #7472) Unless you are dependent on v1, the solution is to simply update the URL to download a more recent version of docker-compose. Note that the releases starting with version 2.0 prefix the version number with a 'v'. The following command should successfully download docker-compose on a Raspberry Pi.
`sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

**Comment by vudnd18** [comment]
> 

thank bro

**Comment by leonheess** [comment]
Encountering the same problem but unfortunately @cgrycki solution didn't work for me

**Comment by Chever-John** [comment]
Thanks @[cgrycki](https://github.com/cgrycki), I'm a raspberry pi user and this really helped me, thanks again.

**Comment by sajalmia381** [comment]
> Encountered the same problem but unfortunately, @cgrycki solution didn't work for me. The link that is created is https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-Linux-armv71 which doesn't exist.
> 
> Just use this command:
> 
> ```
> sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
> ```

SOLVED: my ubuntu arm base machine problem solved

**Comment by Remzi1993** [comment]
> Encountered the same problem but unfortunately, @cgrycki solution didn't work for me. The link that is created is https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-Linux-armv71 which doesn't exist.
> 
> Just use this command:
> 
> ```
> sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-armv7" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
> ```

This command is better: `sudo curl -L "https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose`

**Comment by leonheess** [comment]
further activity
