### ISSUE TITLE
Add delay to starting containers

### ISSUE THREAD

**Issue by LordMilutin** [docker/compose#8450]
Hello!

I know this might have been a discussion topic in the past, but for many of my projects that run multiple containers which depend on each other, a feature like a delay of starting a container would be incredibly beneficial.

For example, we would put in docker-compose a delay value in seconds and after that amount of time has passed since docker compose up that container would start. 

This would give the time for each container to breathe on its own and not only would we start everything successfully due to their dependency on each other, but we would also be able to specify starting order, which is something a lot of people have been asking for.

I ask you nicely not to dismiss this idea lightly but think about it since it would certainly bring a huge improvement to docker-compose.

Thank you in advance!

**Comment by pnjakste** [comment]
You can specify
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3

to restart crashed containers after some time.        
This works for the latest version of docker-compose [v2.2.3]
I don't know if it's intended to work, but its nice.

**Comment by istvandesign** [comment]
Hello, yes this is a feature that is really missing from docker-compose.

The wait-for-it is not a solution when you have to go into an existing project with 20 microservices owned by 10 different teams that don't have your problem because they develop on Windows/Linux and their docker is fast enough to restart as many times as necessary if the services are not in the right order to register in time with a service registry like Eureka.

Now since many projects have amd64 builds they will be even slower and starting a project is basically random on a mac with M1 if you can't delay other services before the critical ones.

**Comment by LordMilutin** [comment]
Bump since I think it is still relevant.

**Comment by snspinn** [comment]
Even though `depends_on` solves most use cases for this, I think this is still a nice to have.
