### ISSUE TITLE
Option to set hostname to container_name

### ISSUE THREAD

**Issue by arvenil** [docker/compose#8475]
Please consider adding a possibility to set hostnames to container names instead of ID.

Currently you can set hostname in yaml file to whatever you want, however if you want to scale service with `--scale web=2` **this is not possible**.

`docker-compose ps` outputs container names,
```
❯ docker-compose ps
NAME          COMMAND                  SERVICE             STATUS              PORTS
app_web_1     "account -env docker…"   app                 running (healthy)   0.0.0.0:63167->80/tcp
app_web_2     "account -env docker…"   app                 running (healthy)   0.0.0.0:63165->80/tcp
```

Thanks to embeded DNS server, within container you can reach another one by container name:
```
❯ docker-compose exec nginx bash
bash-5.0# ping app_web_1
PING app_web_1 (172.22.0.6) 56(84) bytes of data.
64 bytes from app_web_1.app_default (172.22.0.6): icmp_seq=1 ttl=64 time=0.132 ms
```

However with `--scale web=2` there is no way to have nice hostname, making it very hard to understand which ID corresponds to which container.

Could we have e.g. a flag `docker-compose up --set-hostname-to-container-name`?

p.s. Is there a way to get container name within container?

**Comment by BloodyRain2k** [comment]
I'm surprised that docker compose prefers using scrambled alpha numerics for hostnames instead of just taking the same approach as for the network name, just with the container's name added as well.
If the container's name is "nginx" and the compose folder is "wordpress" it could just assign the hostname to "wordpress_nginx".
And if scaling is used as described, add the instance ID aswell: "wordpress_nginx-1", "wordpress_nginx-2".
