### ISSUE TITLE
REQUESTS_CA_BUNDLE

### ISSUE THREAD

**Issue by iambernics** [docker/compose#8634]
Docker Compose is working only if the REQUESTS_CA_BUNDLE variable is point to the CA.

Otherwise getting SSL error:

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate"`

Other Docker SSL related environment variables has been already used and also passing the certificates with argument of the Compose CLI without result.

```
DOCKER_CERT_PATH=/folder/of/the/certificates
DOCKER_TLS_VERIFY=1
```

TLS related arguments of docker-compose CLI:

`--tlsverify --tlscacert /certs/client/ca.pem --tlscert /certs/client/cert.pem --tlskey /certs/client/key.pem`

Why needed the REQUESTS_CA_BUNDLE?

....

The REQUESTS_CA_BUNDLE has been widely used, not clear the side effects if this variable point to the internal Docker certificate.

**Comment by ndeloof** [comment]
please provide `docker-compose version``
(why didn't you used the issue template?)

**Comment by iambernics** [comment]
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Comment by thohng** [comment]
I dont need to use `REQUESTS_CA_BUNDLE` when deal with the error `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate"`

![image](https://user-images.githubusercontent.com/9668549/165028573-ba3f03cc-03a0-4a04-a4b1-1cdba262443d.png)

The way I resolved the issue is build the certificates chain and put to `ca.pem` at client side, instead of put only the `Intermediate Cerfification Authority` into `ca.pem` for client side. At server side of docker engine just need to put the Intermediate Cerfification Authority into `ca.pem` is enough to verify the client cert. Then certificates chain `ca.pem` at client side order will be:

```
-----BEGIN CERTIFICATE-----
(Intermediate Cerfification Authority)
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(Root Cerfification Authority)
-----END CERTIFICATE-----
```
