### ISSUE TITLE
Error response from daemon: invalid restart policy 'any'

### ISSUE THREAD

**Issue by dopry** [docker/compose#8756]
**Description**
I am running `docker compose up` and getting the error `Error response from daemon: invalid restart policy 'any'`

**Steps to reproduce the issue:**
1. create a docker-compose.yml and set the deploy key
   
```
  deploy:
    restart_policy:
      condition: any
```
2. docker compose up

**Describe the results you received:**
`Error response from daemon: invalid restart policy 'any'`

**Describe the results you expected:**
The service should have started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 17
  Running: 2
  Paused: 0
  Stopped: 15
 Images: 13
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 25.01GiB
 Name: docker-desktop
 ID: REDI:KQPL:PKK5:YC7O:NPTM:SXFT:EYLM:KALZ:NCR3:MPIX:KT6H:E4HY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by gilbsgilbs** [comment]
Same issue with `none` policy. The problem is that [compose file specification](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) defines three allowed values for a restart policy condition: `none`, `on-failure` and `any` which doesn't map well with those from [the engine](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy): `no`, `on-failure`, `always` and `unless-stopped`. So I guess compose is wrong to forward the condition directly to the engine, this would only work for `on-failure`.

I guess a non-breaking way to fix this would be to map `none` to `no`, `any` to `always`, and otherwise forward to the docker engine just like today. WDYT?

**Comment by dopry** [comment]
I just did a test by updating the restart condition to use the values understood by the engine. I was able to start the environment.  So it appears these have been added to the specification and the old values were removed, but the documentation was not updated to reflect this change. It seems like major version should have ticked for a breaking change in the spec.

**Comment by mlissner** [comment]
FWIW, we use the `none` restart policy, and the breaking changes here are really annoying. It means that all of our developers and our servers have to upgrade to docker compose v2 just for the change from `none` to `no`. Good example of code churn that has *very* little reason.

**Comment by joffremota** [comment]
_> Same issue with `none` policy. The problem is that [compose file specification](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) defines three allowed values for a restart policy condition: `none`, `on-failure` and `any` which doesn't map well with those from [the engine](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy): `no`, `on-failure`, `always` and `unless-stopped`. So I'd say compose is wrong to forward the condition directly to the engine, this only works for `on-failure` condition.
> 
> I guess a non-breaking way to fix this would be to map `none` to `no`, `any` to `always`, and otherwise forward to the docker engine just like today. WDYT?_

Worked for me using Docker's version 2.6.0.

**Comment by jacohend** [comment]
>So it appears these have been added to the specification and the old values were removed, but the documentation was not updated to reflect this change. It seems like major version should have ticked for a breaking change in the spec.

Exactly. This is a major breaking change for everyone who dual-used compose and swarm.

**Comment by WayneYe** [comment]
Submitted a PR for fixing this: https://github.com/docker/docs/pull/15936
