### ISSUE TITLE
How to expose a Docker container port to one specific Docker network only, when a container is connected to multiple networks?

### ISSUE THREAD

**Issue by ElleshaHackett** [docker/compose#8795]
From the Docker documentation: 
- `--publish or -p flag. Publish a container's port(s) to the host.`
- `--expose. Expose a port or a range of ports.`
- `--link. Add link to another container. Is a legacy feature of Docker. It may eventually be removed.`

I am using docker-compose with several networks. I do not want to publish any ports to the host, yet when I use expose, the port is then exposed to all the networks that container is connected to. It seems that after a lot of testing and reading I cannot figure out how to limit this to a specific network.

For example in this `docker-compose` file with where `container1` joins the following three networks: `internet`, `email` and `database`.

    services:
        container1:
           networks:
               - internet
               - email
               - database

Now what if I have one specific port that I want to expose to ONLY the `database` network, so NOT to the host machine and also NOT to the `email` and `internet` networks in this example? If I would use `ports:` on `container1` it is exposed to the host or I can bind it to a specific IP address **of the host**. *I also tried making a custom overlay network, giving the container a static IPv4 address and trying to set the ports in that format in `ports:` like `- '10.8.0.3:80:80'`, but that also did not work because I think the binding can only happen to a HOST IP address. If i use `expose:` on `container1` the port will be exposed to all three networks: `internet`, `email` and `database`.

I am aware I can make custom firewall ruling but it annoys me that I cannot write such simple config in my docker-compose file. Also, maybe something like `80:10.8.0.3:80` (HOST_IP:HOST_PORT:CONTAINER_IP:CONTAINER_PORT) would make perfect sense here (did not test it).*

Am I missing something or is this really not possible in Docker and Docker-compose?

Also posted here: https://stackoverflow.com/questions/69563159/how-to-expose-a-docker-container-port-to-one-specific-docker-network-only-when

**Comment by ericslandry** [comment]
Is this a dup of https://github.com/moby/moby/issues/21798 ?

**Comment by KES777** [comment]
Really interesting feature. I think, it should a worth to implement it.

In my situation, I have two stacks and want to expose only one port to one specific container.

**Comment by juan11iguel** [comment]
Second this!

I have two networks connected to my container, a proxied one with external access where I would not like to expose any ports, and an internal network where I would like to have some isolated internal communication between containers that expose ports

**Comment by LuxBibi** [comment]
Hi,
Looking around for some hours ... but nothing found yet. Did anybody found a solution to this topic, to bind port maping to a specific network, if a service has multiple networks in a docker compose file? I solved this by starting my service with only the network (MacVlan) I want the port forwarding applied, and added the second brideged network later manually, as container was started, having all these errors in the log file, because he was not able to comnnect to the DB.

Greeting from Luxembourg/Europe ;-)
Thanks in advance ;-)

**Comment by bestrocker221** [comment]
+1 This would be really good to have.

**Comment by jerry-sky** [comment]
This feels like such an oversight. Could be dangerous if you use same ports on different networks for one container.

A partial solution, that I had to pick was to just use different ports so they don't overlap and bind those to all network interfaces on that container. So in Traefik for example, instead of binding to a specific IP `10.0.21.37:80` you bind to `:8080` and than you can expose port `8080` to host as port `80` in Docker Compose config (`ports: [ "127.0.0.1:80:8080" ]`).

This works, but is not very elegant. I agree with OP that ideally, one could define a port mapping where you get to specify the container's internal IP, just like you specify host's IP.
