### ISSUE TITLE
Unexpected exec behaviour for docker-compose run against docker-compose up

### ISSUE THREAD

**Issue by GenaANTG** [docker/compose#8827]
I have `docker-compose.yml` file with one service named `maintenance`.
I tried to run same service from `docker-compose up` & `docker-compose run`.

### docker-compose up

`docker-compose -p example up -d --no-deps maintenance`

### docker-compose run

`docker-compose -p example run -d --no-deps --name maintenance_run -p 8080:80 maintenance`

Both containers runs as expected

<img width="1266" alt="Screenshot 2021-10-25 at 05 20 19" src="https://user-images.githubusercontent.com/12715550/138625144-1e681db5-6673-42b2-9b28-1acc291e231b.png">

Problem is that `docker-compose exec` works correctly only for container which was created by `docker-compose up` command. Container which was created by `docker-compose run` returns exit code 1.

### Run next commands

`docker-compose -p example exec maintenance ls -l`
`docker-compose -p example exec maintenance_run ls -l`

<img width="940" alt="Screenshot 2021-10-25 at 05 25 53" src="https://user-images.githubusercontent.com/12715550/138625611-32066e87-7b53-4c60-a82e-cb6287bcaf98.png">

## Expected behaviour

`docker-compose exec` should works correctly for containers which runs by `run` and `up` commands, for the same service.
Both containers should print same output for `ls -l`.

```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by drewgingerich** [comment]
It'll be easier to help if you post the contents of your `docker-compose.yml`.

`docker compose exec` takes a ___service name___, as defined in `docker-compose.yml`. You are trying to give it the ___container name___. On the other hand `docker exec` expects a container name (or id), which is why it's working for you.

I think you are misunderstanding what `docker compose run` is for. It's designed to run "one-off" commands in a new container, with the same image and config as the given service. It's great for things like running tests. To run the primary command for a service you should use `docker compose up`. 

But what I've told you doesn't solve your problem: how to open ports to your container. This has to be done in `docker-compose.yml` by adding a ports section to the service. I don't really understand your goal, but you may be interested to know that you can layer multiple compose files, which can be a way to expose ports only when you want by including or not including an override file that contains the ports section. [Here are the docs on that](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration).

**Comment by GenaANTG** [comment]
Look at screenshots, we have different behaviour for same commands. It's frustrating.
`docker-compose.yml` in this case no matter.

**Comment by GenaANTG** [comment]
@drewgingerich Okay! Thank you.

**Comment by GenaANTG** [comment]
@drewgingerich 

> docker compose exec takes a service name, as defined in docker-compose.yml. You are trying to give it the container name. 

`docker-compose exec --help`
`Execute a command in a running container` <- container, should be service?

`docker exec --help`
`Run a command in a running container` <- container

**Comment by ndeloof** [comment]
`docker-compose run` create "one-off" container, with a random ID, so there's no way for `compose exec` to be deterministic selecting a container to exec into. Or you would have to pass an explicit container ID, ... but then why not just use `docker exec <ID>`?

> Execute a command in a running container <- container, should be a service?

this executes a command in "one of the container for the service"

**Comment by GenaANTG** [comment]
@ndeloof Exactly, `docker exec` works fine.

> this executes a command in "one of the container for the service"

Service is a declared container or set of containers (docker swarm replicas).
You can run container with same options without docker compose by `docker run` command. 
That's why it's looks a bit confusing.
