### ISSUE TITLE
docker-compose fails when trying to map many ports

### ISSUE THREAD

**Issue by leeflix** [docker/compose#9085]
I am trying to map as many ports as possible (1001-65535) of my container to the host machine, but docker-compose build fails in the last steps.

This is my docker-compose.yaml that works:
```
version: '3.8'

services:
  frapi:
    restart: always
    build: .
    ports:
      - "8080:8080/tcp"
      - "50000-50009:50000-50009/udp"
```

When I try to expose the ports 1001-65535 instead of just 50000-50009 it fails:

```
version: '3.8'

services:
  frapi:
    restart: always
    build: .
    ports:
      - "1001-8079:1001-8079/udp"
      - "8080:8080/tcp"
      - "8081-65535:8081-65535/udp"
```

**Describe the results you received:**

```
root@...# docker-compose build --no-cache && docker-compose up -d --force-recreate
...
Step 10/10 : CMD ["-m", "openapi_server"]
 ---> Running in 9021e8665944
Removing intermediate container 9021e8665944
 ---> d778b1f5e103
Successfully built d778b1f5e103
Successfully tagged frapi_flask_frapi:latest
WARNING: Found orphan containers (frapi_flask_service_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating frapi_flask_frapi_1 ...
Recreating frapi_flask_frapi_1 ... error

ERROR: for frapi_flask_frapi_1  Cannot start service frapi: driver failed programming external connectivity on endpoint frapi_flask_frapi_1 (6f152bdc1598106500fc0be22db5c7281297eb3921468424df10741d59eae472): Error starting userland proxy:

ERROR: for frapi  Cannot start service frapi: driver failed programming external connectivity on endpoint frapi_flask_frapi_1 (6f152bdc1598106500fc0be22db5c7281297eb3921468424df10741d59eae472): Error starting userland proxy:
ERROR: Encountered errors while bringing up the project
root@...
```

**Describe the results you expected:**

I expected that the container is up and running, but it is not.

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 19
  Running: 0
  Paused: 0
  Stopped: 19
 Images: 777
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.15.0
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 8GiB
 Name: h2899006.stratoserver.net
 ID: AIE6:LG6K:WIBV:GCCE:3EAT:KR72:JIX6:JC7J:MEBM:HNHQ:TAY2:4DBM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by snooops** [comment]
i can confirm. I just wanted to open the same issue.

**Comment by ndeloof** [comment]
Can you please confirm you can run a comparable container with a bunch of ports exposed on host using plain `docker run -p RANGE:RANGE ...` and that this issue is a Compose one, not a limitation for docker engine in some circumstances ?

**Comment by nkartem** [comment]
If I use the driver host do not have a problem with the starting container and port range.


`cat docker-compose.yaml`
```
version: '3.1'

services:

  asterisk:
    image: nkartem/asterisk
    container_name: asterisk
    restart: always
    command: systemctl start asterisk
    network_mode: "host"
```
![image](https://user-images.githubusercontent.com/16717725/210959822-7a36afc7-46e1-4c31-a5a1-17df2d8b607d.png)

**Comment by ndeloof** [comment]
If you get this issue, please try running your service image with `docker run -p RANGE:RANGE ...` (doesn't matter it can't run isolated, just an attempt to understand if this is a docker engine limitation or compose bug)

**Comment by nkartem** [comment]
`sudo docker run -it -d -p 10000-20000:10000-20000/udp -p 5022:5022 nkartem/asterisk `

It`s not working too. Docker used all RAM and the host stopped responding.

**Comment by ndeloof** [comment]
@thaJeztah are you aware of a known issue with moby on this topic?

**Comment by thaJeztah** [comment]
Yes, this is a known issue; it’s slightly better on Docker Desktop as we disable the userland-proxy on Desktop (which would run 1 proxy per port :grimacing:), but libnetwork creates an iptables rule for every port mapped, not a port-range.
If you're running on Linux, you can opt to use `host` networking for specific cases (VOIP etc), but make sure you do so with trusted workloads only, as doing so disables the networking sandbox of the container (the container is using the host's network stack, so won't have its own networking namespace, or its own IP-address). Host networking is not currently supported on Docker Desktop (you can use it, but it would use the VM's host network, not the macOS/Windows machine's host). Disabling the userland-proxy  in the daemon configuration also helps (but likely will still be an issue with a _large_ port-range)

Related issues in moby (there’s probably more) that may contain useful information;

* https://github.com/moby/moby/issues/11185
* https://github.com/moby/moby/issues/16284
* https://github.com/moby/moby/issues/19017

I think there was a PR once to update libnetwork to use a _range_ of ports for port-mapping (instead of individual ports), but that never made it in (contributions welcome for that though, but may not be an easy job).

**Comment by ndeloof** [comment]
Closing as "not a compose issue". Please follow relevant Moby issues listed
