### ISSUE TITLE
Healthchecks vs. waitfor.sh in docker-compose?

### ISSUE THREAD

**Issue by patientplatypus6** [docker/compose#9223]
What is the preferred method for checking the health of docker containers in v3? The documentation recommends using `waitfor.sh` https://docs.docker.com/compose/startup-order/ but another developer is successfully running a docker-compose instantiation using healthchecks. Which is the preferred method, given that both appear to work, and why?

**Comment by eabykov** [comment]
@patientplatypus6 if one service needs another to be started before it starts (for example, the database must be available before the start of the web application), then the wait for database logic is best implemented in the application itself so that when switching from docker compose to Kubernetes or anywhere else, you do not need to re-do the wrapper for each application there

In docker compose
- The easiest way is to make `depends_on` and `healthcheck`'s for dependent applications (when switching to Kybernetes for example you will have to create init containers and probes there)
- A more complicated way is to do your `entrypoint`/`command` with `wait for` logic in a entry script (it looks like the following option)
- Support the wait for algorithm in the applications themselves and that they exit with an error code by timeout
   > In this case, it is also better to make `healthcheck` so that when you start, you immediately notice that the application is not working (Start by the command `docker compose up -d --wait` to wait for all `healthcheck`'s and `depends_on` will be passed)

**Comment by eabykov** [comment]
@patientplatypus6 example of combination `depends_on` and `healthcheck` you can find here: https://github.com/eabykov/keycloak-compose

**Comment by ndeloof** [comment]
from an architecture point of view, having your code to be resilient regarding database availability is indeed the best approach, but maybe you need to run some service you didn't designed, or you just don't care :P Then using `depends_on` is the way docker compose allows you address this issue, and you can configure `condition: service_healthy` so that container will only be started after it's dependency reports a healthy state.
