### ISSUE TITLE
Make --rm flag default for `fig run`

### ISSUE THREAD

**Issue by psychowico** [docker/compose#943]
why --rm is not default for `fig run`? I find containers created by run often useless. Maybe it could be some 'no-rm' flag instead of --rm ?

People who I presents fig are confused by this flag.

**Comment by kojiromike** [comment]
:+1: (but I would prefer `--keep` to `--no-*`)

**Comment by aanand** [comment]
It's not the default because that would've been a breaking change.

We could make it the default for the next version increment. `--no-rm` would be consistent with other flags.

**Comment by Starefossen** [comment]
+1 to default `--rm` and optional `--no-rm` for next major version increment!

**Comment by schmunk42** [comment]
:+1:

**Comment by ssreekanth** [comment]
:+1:

**Comment by taiidani** [comment]
:+1:

**Comment by hugochinchilla** [comment]
+1

**Comment by baptistedonaux** [comment]
+1

**Comment by ged15** [comment]
:+1:

**Comment by zedtux** [comment]
+1 !!

**Comment by dnephin** [comment]
I think defaulting to `--rm` may be confusing in some cases, because that's not the `docker run` default.

**Comment by Visgean** [comment]
Well this should be, at least, configurable in some way.

**Comment by shin-** [comment]
I don't think we're looking to change the default behavior of `run` anymore at this point - #3178 should mitigate the pain on this though.

**Comment by weibeld** [comment]
Another workaround is the following Bash function that sets `--rm` for any `docker run` and `docker container run` command:

``` bash
docker() {
  local args=("$@")
  if [[ "$1" = run ]]; then
    args=(run --rm "${args[@]:1}")
  elif [[ "$1" = container && "$2" = run ]]; then
    args=(container run --rm "${args[@]:2}")
  fi
  command docker "${args[@]}"
}
```
If you don't want the `--rm` flag for a specific command, you can run `command docker run <...>` in order to invoke the actual `docker` command and not the Bash function.

**Comment by r-hoogenboom** [comment]
This is nice (albeit quirky) for when you're on linux where bash is the default shell, but cmd.exe doesn't have such facility.
I don't understand why this cannot be put in the config file of docker for instance (look at git). Everybody is talking about not breaking current behavior; so make it persist-able for people who don't care about such backward compatibility and just want 'sane' behavior.
Or at least create a short option for --rm, so that is can be merged in the options your fingers automatically type. Something like -r, so that 'docker run -rit' becomes the standard, which nobody actually needs to know what the letters mean, because it just does what you want.
