### ISSUE TITLE
Use on windows

### ISSUE THREAD

**Issue by SteveALee** [docker/compose#947]
It appears that Boot2Docker works on Windows so will Fig also? The Fig install instructions only mention OS X

https://docs.docker.com/installation/windows/
http://www.fig.sh/install.html

**Comment by girvo** [comment]
From what I recall, it can in theory work, however it has to run *inside* the `boot2docker` virtual machine, not on the host system. The problem with that, is that `boot2docker` is an odd duck, where it's a 64-bit kernel and a 32-bit userspace, so `fig` never ran on it correctly.

I'm unsure whether that's still the case for `docker-compose` instead. Worth giving it a try, run `boot2docker ssh` and install `docker-compose` inside the VM.

**Comment by kristofferpeterhansel** [comment]
Running the binaries on the boot2docker VM does not work (https://github.com/docker/compose/issues/1032). And installing it on Windows don't either due to reliance on the fcntl module (https://github.com/docker/compose/issues/417).

So running a more complete Linux VM seems to be the only way to go right now

**Comment by bfirsh** [comment]
I have created an issue to keep track of this: #1085. Thanks for reporting!
