### ISSUE TITLE
Remove dependency timebomb from old v1 docker-compose package

### ISSUE THREAD

**Issue by ssbarnea** [docker/compose#9510]
The ceiling of dependencies from https://github.com/docker/compose/blob/master/setup.py is causing conflicts with newer tools and acting as a timebomb, even if there is no proof that any of the newer versions are effectively incompatible with the library.

**Description**

Good examples are pyyaml and jsonschema at least which both have newer releases which are backwards compatible, but docker-compose v1 is preventing their use.

Other tools and libraries might require newer versions, causing impossible to resolve dependencies.

We need to remove these dependencies in order to defuse the situation and give users more time to refactor their code to stop using the python library and switch to command line use of the newer v2 docker-compose. Still, doing this needs time as such switch is far from simple.

**Comment by ndeloof** [comment]
As we deprecated docker-compose v1 we made it clear we would only offer maintenance for security fixes. There won't be a new release with "just" updated dependencies.
I understand the inconvenience for tools and libraries relying on docker-compose as a dependency, but wonder you can't use your dependency management toolset to override compose dependencies with your own version?

**Comment by exhuma** [comment]
I just needed to re-create an `ansible` environment on a new machine and ran into https://github.com/yaml/pyyaml/issues/724

I cannot safely upgrade to pyyaml 6.x because docker-compose has too restrictive version constraints of its dependencies. Gathering from https://github.com/ansible-collections/community.docker/issues/364 it looks like docker-compose is dead. But, would it be possible to at least remove the version restrictions from the Python package dependencies as a light-weight maintenance release?

As this only touches the package meta-data it won't be a huge time-invest. And that way, the dependency resolution/pinning will be pushed down to "downstream" packages. This will give those tools more time to migrate, and the docker team would not be impacted by any such issues anymore.

**Comment by ndeloof** [comment]
@exhuma python Docker compose v1 is End Of life, you should remove it from your ansible recipies.
No further maintenance effort is planed, even "light weight" ones

**Comment by felixfontein** [comment]
@exhuma you can force PyYAML == 5.3.1, that version is acceptable for docker-compose v1 and doesn't have the problem later PyYAML 5.x versions have (https://github.com/ansible-collections/community.docker/issues/672#issuecomment-1649318258).

**Comment by ndeloof** [comment]
I'm closing this issue as obsolete: Docker Compose V1 has reached end-of-life and we are not accepting any more changes. Please try and reproduce your issue with Compose V2 and create a new issue or PR with the relevant Compose V2 information.
