### ISSUE TITLE
Call Fig from Python

### ISSUE THREAD

**Issue by rudimk** [docker/compose#954]
Is there a way I can use Fig as a library from Python code? I'm looking at something along these lines:

```
import fig

os.chdir('test/dockerfiles/')
fig.build()
# returns a container ID, maybe?

```

Thanks!

**Comment by dnephin** [comment]
You *can* use it as a library (it's something I do), but you shouldn't expect the internal interfaces to be consistent between versions  Functions may lose arguments or be removed entirely without a major version bump, because fig (docker compose) is primarily a cli, not a library. So you should make sure that you're comfortable having to potentially make code changes when you upgrade versions.

That said, I think you can expect `compose.project.Project` to remain pretty consistent for the most part. You can do something like this:

```python
import compose.cli.command

command = compose.cli.command.Command()
project = command.get_project(command.get_config_path())
project.build()
project.up()
...
```

**Comment by the-destro** [comment]
I am working on a project where it extensively uses it as a library and it works pretty well with only a few oddities. I think it would be useful to think about standardizing it down as I think there is a need to have a composition library. Otherwise projects like Panamax end up using their own format for templates and such.

**Comment by funkyfuture** [comment]
Just my two cents: API-changes should be an exception and be documented in the release notes of a new version.

**Comment by slank** [comment]
This is a use case I'm very interested in for driving stack tests. It would be awesome if Compose had an API similar to the CLI that could be driven directly. Right now I'm using subprocess. Bonus points if the API included context managers to handle teardown.

**Comment by dnephin** [comment]
Related questions #1033, #1860

https://github.com/docker/libcompose was released recently which aims to be a golang library for compose. Of course if you're writing in any other language that doesn't help you!

I think it's worth considering how hard it would be to expose a `docker-compose` API over http/json so that it could be used from any language.

**Comment by funkyfuture** [comment]
> I think it's worth considering how hard it would be to expose a docker-compose API over http/json so that it could be used from any language.

i also thought about that once. but especially since there is `libcompose` now that'd be the library to offer such interface. using compose as a python library is far more powerful and the effort for a rest-interface isn't worth it if you had it in `libcompose`. (python users would prefer a python-api; for other languages libcompose is enough.)

nonetheless, there's quiet some leverage to improve compose's public api.

**Comment by the-destro** [comment]
What I selfishly want is the yaml bits and the rest of compose separate. If there was a nice public python api that would take a dict that would be great. The yaml bits could take care of building the dict and resolving all of the new nifty features.

**Comment by dnephin** [comment]
Let's track this in #230

**Comment by francescou** [comment]
I've developed a (python) RESTful API on top of docker compose: https://github.com/francescou/docker-compose-ui
