### ISSUE TITLE
`docker compose logs` (v2) strip colors when outputting to a pipe

### ISSUE THREAD

**Issue by DanielRamp** [docker/compose#9573]
**Description**

`docker compose logs` (v2) do not keep colored output when writing through a pipe.
It's easy to see. Just run `docker compose logs | cat` and the colors are gone.

This "bug" already appeared in v1, see #4795.

**Steps to reproduce the issue:**
1. get into a docker compose folder (folder with any working `docker-compose.yml` inside).
2. run `docker compose logs | cat` in your shell
3. see the logs are NOT colored
4. _optional:_ run `docker compose logs` (without `| cat`) in your shell
5. _optional:_ see the logs ARE colored

**Describe the results you received:**
The logs are NOT colored.

**Describe the results you expected:**
The logs are colored when needed.
Maybe the flag `--no-color` could be used with `false` to force coloring logs.

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Comment by ndeloof** [comment]
This is by design: Using `docker compose logs | ... ` compose doesn't get access to a TTY anymore, but only to plain POSIX stdout/stderr piped to another process. This is why ANSI color codes are not used in such a context
You can force ANSI code to be used by passing `--ansi=always`

`docker compose --ansi=always logs | cat`
