### ISSUE TITLE
Catch 22 with `external_links` mutual dependency

### ISSUE THREAD

**Issue by zeeraw** [docker/compose#978]
As it turns out, when you got two or more projects that want to communicate with each other, docker-compose support is lacking. Starting up **project_a** requires me to have **project_b** running and vice versa.

```
# project_a/docker-compose.yml
app:
  external_links: projectb_app:b
```

```
# project_b/docker-compose.yml
app:
  external_links: projecta_app:a
```

For now I can circumvent this by running an ambassador proxy but it makes me wonder if this is something that should be solved by tooling in docker-compose. I'd love to hear your ideas.

Currently this increases developer sadness quota by 42%

![sadness 42%](http://mylittlefacewhen.com/media/f/rsz/mlfw4305_small.jpg)

**Comment by dnephin** [comment]
I am pretty sure this is a limitation of docker links, they can't be circular.

**Comment by zeeraw** [comment]
@dnephin Yeah, that's what I've gathered reading through documentation. It brings up a good question though. What is the preferred way of dealing with circular dependency?

**Comment by dnephin** [comment]
I think avoiding them is always nice, but if that's not an option, I've been suggesting you can use a dns service as part of your compose setup (since links are really just an easy way of doing dns).

There seem to be a lot of options for this:
* https://github.com/crosbymichael/skydock
* https://github.com/progrium/registrator
* https://github.com/bnfinet/docker-dns
* http://jasonwilder.com/blog/2014/07/15/docker-service-discovery/

I haven't had a chance to use any of these myself yet, but I would like to get around to it.

**Comment by aviau** [comment]
> Currently this increases developer sadness quota by 42%

I can confirm that I feel the sadness.

Any updates on this?

**Comment by zeeraw** [comment]
@aviau As far as I've understood, this type of thing is fundamentally not compatible with how docker works.

**Comment by dnephin** [comment]
I believe the new docker networking will allow circular "links" to exist. You can follow #1676 for the compose side of things.

**Comment by zeeraw** [comment]
@dnephin Cheers.
