### ISSUE TITLE
issue when using multiple .yml files and external network

### ISSUE THREAD

**Issue by aradgonengk8** [docker/compose#9826]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Steps to reproduce the issue:**
1. create two .yml files
2. one creating a network and the second file is joining to it with external:true
3. when running docker-compose -f a.yml -f b.yml up -d -> sometimes it fails because it cant find the external network, but running the same command again works.

**Describe the results you expected:**
expected it to work..

**Output of `docker compose version`:**

```
Docker Compose version v2.10.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)
WARNING: Plugin "/home/arad/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: fork/exec /home/arad/.docker/cli-plugins/docker-compose: permission denied

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 83
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1051-oem
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.48GiB
 Name: arad-ThinkPad-P1-Gen-3
 ID: 23CD:HFNL:LBRK:EYZL:KEOG:2GAS:S2TA:MVFW:HJA5:KDX4:KQTL:5ABF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.1.13:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by laurazard** [comment]
Hi @aradgonengk8, thanks for the report!

What happens when two compose files are provided is that compose merges them before attempting to execute the compose model. If we have two compose files with network sections such as
```yaml
[...]
networks:
  a:
```
and
```yaml
[...]
networks:
  a:
    external: true
```
is that they get merged into:
```
[...]
networks:
  a:
    name: a
    external: true
[...]
```
Which will not work since the network will not be created.

You can test the compose model that two compose files will get merged into by running: `compose -f a.yaml -f b.yaml convert`.

However, in this case, if the compose files are being ran together, it's fine to only define the network in one of them, without `external: true`, and just reference it by name in the services in the 2nd file where you want services to connect to it.

I'm closing the issue for now, but feel free to comment with more information if I've missed something.
