### ISSUE TITLE
One service failed to be started with the same name, and all services are in the created state ?

### ISSUE THREAD

**Issue by othersonlyme** [docker/compose#9860]
![image](https://user-images.githubusercontent.com/55185255/191159402-121d18c8-1457-497e-9b9f-a522f12059b3.png)

![image](https://user-images.githubusercontent.com/55185255/191158999-dad4a477-941e-4b08-80b3-7afe49abed95.png)

**Comment by othersonlyme** [comment]
@laurazard

**Comment by milas** [comment]
Compose will only manage containers it previously created.

If you are using the `container_name` operation and created a container in another way with the same name, you'll see this error.

If you do not _need_ the `container_name` option, I would recommend removing it and allowing Compose to name your containers.

Otherwise, you'll need to do as the error says: remove or rename the existing container with the same name, e.g. `docker rm -f black-exporter` and then run `docker compose up` again.

**Comment by milas** [comment]
Also, in the future, please use the issue template as provided or as close to it as possible and use GitHub code blocks (` ``` ` regions) instead of screenshots.

Issues without these details will be likely to be closed without providing support, as it's very time-consuming to triage otherwise.
